/* Generated by Pyrex 0.9.8.5 on Thu Oct 30 10:45:35 2008 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "m_clist.h"


typedef struct {PyObject **p; int i; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static int __Pyx_GetException(PyObject **type, PyObject **value, PyObject **tb); /*proto*/

static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static void __Pyx_WriteUnraisable(char *name); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from clist */


/* Declarations from implementation of clist */

typedef unsigned char __pyx_t_5clist_BYTE;

typedef unsigned long __pyx_t_5clist_DWORD;

typedef unsigned short __pyx_t_5clist_WORD;

typedef unsigned short __pyx_t_5clist_WCHAR;

typedef int (*__pyx_t_5clist_MIRANDAHOOK)(long,long);

static PyObject *__pyx_f_5clist_AddMenuItem(char *,char *,int,char *,char *,int,char *,int,int); /*proto*/
static int __pyx_f_5clist_OnEventStatusChange(long,long); /*proto*/
static int __pyx_f_5clist_OnPreBuildContactMenu(long,long); /*proto*/
static PyObject *__pyx_f_5clist___clistAddEventHook(PyObject *,__pyx_t_5clist_MIRANDAHOOK); /*proto*/

static char __pyx_k1[] = "MirPy";
static char __pyx_k2[] = "CallService";
static char __pyx_k3[] = "Clist/RemoveEvent";
static char __pyx_k4[] = "CList/SetStatusMode";
static char __pyx_k5[] = "CList/GetStatusMode";
static char __pyx_k6[] = "CList/GetStatusModeDescription";
static char __pyx_k7[] = "CList/GetContactDisplayName";
static char __pyx_k8[] = "CList/AddMainMenuItem";
static char __pyx_k9[] = "CList/AddContactMenuItem";
static char __pyx_k10[] = "CList/AddStatusMenuItem";
static char __pyx_k11[] = "CList/ModifyMenuItem";
static char __pyx_k12[] = "__clistLock";
static char __pyx_k13[] = "acquire";
static char __pyx_k14[] = "HookedClistEventsCallbacks";
static char __pyx_k15[] = "Error calling '%s' (%s)";
static char __pyx_k16[] = "__name__";
static char __pyx_k17[] = "release";
static char __pyx_k18[] = "HookedClistEvents";
static char __pyx_k19[] = "has_key";
static char __pyx_k20[] = "append";
static char __pyx_k21[] = "NoSuchEventError";
static char __pyx_k22[] = "The event '%s' was not found.";
static char __pyx_k23[] = "remove";
static char __pyx_k24[] = "NoSuchCallbackForEventError";
static char __pyx_k25[] = "The event '%s' has no callback '%s'";
static char __pyx_k26[] = "__CallEventCallbacks";
static char __pyx_k27[] = "CList/StatusModeChange";
static char __pyx_k28[] = "CList/PreBuildContactMenu";
static char __pyx_k29[] = "HookEvent";
static char __pyx_k30[] = "values";
static char __pyx_k31[] = "UnhookEvent";
static char __pyx_k32[] = "Unhooking Clist events";
static char __pyx_k33[] = "__UnhookClistEvents";
static char __pyx_k34[] = "threading";
static char __pyx_k35[] = "RLock";
static char __pyx_k36[] = "STATUS_CONNECTING";
static char __pyx_k37[] = "STATUS_OFFLINE";
static char __pyx_k38[] = "STATUS_ONLINE";
static char __pyx_k39[] = "STATUS_AWAY";
static char __pyx_k40[] = "STATUS_DND";
static char __pyx_k41[] = "STATUS_NA";
static char __pyx_k42[] = "STATUS_OCCUPIED";
static char __pyx_k43[] = "STATUS_FREECHAT";
static char __pyx_k44[] = "STATUS_INVISILE";
static char __pyx_k45[] = "STATUS_ONTHEPHONE";
static char __pyx_k46[] = "STATUS_OUTTOLUNCH";
static char __pyx_k47[] = "STATUS_IDLE";
static char __pyx_k48[] = "__HookClistEvents";

static PyObject *__pyx_n_CallService;
static PyObject *__pyx_n_HookEvent;
static PyObject *__pyx_n_HookedClistEvents;
static PyObject *__pyx_n_HookedClistEventsCallbacks;
static PyObject *__pyx_n_MirPy;
static PyObject *__pyx_n_NoSuchCallbackForEventError;
static PyObject *__pyx_n_NoSuchEventError;
static PyObject *__pyx_n_RLock;
static PyObject *__pyx_n_STATUS_AWAY;
static PyObject *__pyx_n_STATUS_CONNECTING;
static PyObject *__pyx_n_STATUS_DND;
static PyObject *__pyx_n_STATUS_FREECHAT;
static PyObject *__pyx_n_STATUS_IDLE;
static PyObject *__pyx_n_STATUS_INVISILE;
static PyObject *__pyx_n_STATUS_NA;
static PyObject *__pyx_n_STATUS_OCCUPIED;
static PyObject *__pyx_n_STATUS_OFFLINE;
static PyObject *__pyx_n_STATUS_ONLINE;
static PyObject *__pyx_n_STATUS_ONTHEPHONE;
static PyObject *__pyx_n_STATUS_OUTTOLUNCH;
static PyObject *__pyx_n_UnhookEvent;
static PyObject *__pyx_n___CallEventCallbacks;
static PyObject *__pyx_n___HookClistEvents;
static PyObject *__pyx_n___UnhookClistEvents;
static PyObject *__pyx_n___clistLock;
static PyObject *__pyx_n___name__;
static PyObject *__pyx_n_acquire;
static PyObject *__pyx_n_append;
static PyObject *__pyx_n_has_key;
static PyObject *__pyx_n_release;
static PyObject *__pyx_n_remove;
static PyObject *__pyx_n_threading;
static PyObject *__pyx_n_values;

static PyObject *__pyx_k3p;
static PyObject *__pyx_k4p;
static PyObject *__pyx_k5p;
static PyObject *__pyx_k6p;
static PyObject *__pyx_k7p;
static PyObject *__pyx_k11p;
static PyObject *__pyx_k15p;
static PyObject *__pyx_k22p;
static PyObject *__pyx_k25p;
static PyObject *__pyx_k27p;
static PyObject *__pyx_k28p;
static PyObject *__pyx_k32p;

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_n_CallService, 1, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_n_HookEvent, 1, __pyx_k29, sizeof(__pyx_k29)},
  {&__pyx_n_HookedClistEvents, 1, __pyx_k18, sizeof(__pyx_k18)},
  {&__pyx_n_HookedClistEventsCallbacks, 1, __pyx_k14, sizeof(__pyx_k14)},
  {&__pyx_n_MirPy, 1, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_n_NoSuchCallbackForEventError, 1, __pyx_k24, sizeof(__pyx_k24)},
  {&__pyx_n_NoSuchEventError, 1, __pyx_k21, sizeof(__pyx_k21)},
  {&__pyx_n_RLock, 1, __pyx_k35, sizeof(__pyx_k35)},
  {&__pyx_n_STATUS_AWAY, 1, __pyx_k39, sizeof(__pyx_k39)},
  {&__pyx_n_STATUS_CONNECTING, 1, __pyx_k36, sizeof(__pyx_k36)},
  {&__pyx_n_STATUS_DND, 1, __pyx_k40, sizeof(__pyx_k40)},
  {&__pyx_n_STATUS_FREECHAT, 1, __pyx_k43, sizeof(__pyx_k43)},
  {&__pyx_n_STATUS_IDLE, 1, __pyx_k47, sizeof(__pyx_k47)},
  {&__pyx_n_STATUS_INVISILE, 1, __pyx_k44, sizeof(__pyx_k44)},
  {&__pyx_n_STATUS_NA, 1, __pyx_k41, sizeof(__pyx_k41)},
  {&__pyx_n_STATUS_OCCUPIED, 1, __pyx_k42, sizeof(__pyx_k42)},
  {&__pyx_n_STATUS_OFFLINE, 1, __pyx_k37, sizeof(__pyx_k37)},
  {&__pyx_n_STATUS_ONLINE, 1, __pyx_k38, sizeof(__pyx_k38)},
  {&__pyx_n_STATUS_ONTHEPHONE, 1, __pyx_k45, sizeof(__pyx_k45)},
  {&__pyx_n_STATUS_OUTTOLUNCH, 1, __pyx_k46, sizeof(__pyx_k46)},
  {&__pyx_n_UnhookEvent, 1, __pyx_k31, sizeof(__pyx_k31)},
  {&__pyx_n___CallEventCallbacks, 1, __pyx_k26, sizeof(__pyx_k26)},
  {&__pyx_n___HookClistEvents, 1, __pyx_k48, sizeof(__pyx_k48)},
  {&__pyx_n___UnhookClistEvents, 1, __pyx_k33, sizeof(__pyx_k33)},
  {&__pyx_n___clistLock, 1, __pyx_k12, sizeof(__pyx_k12)},
  {&__pyx_n___name__, 1, __pyx_k16, sizeof(__pyx_k16)},
  {&__pyx_n_acquire, 1, __pyx_k13, sizeof(__pyx_k13)},
  {&__pyx_n_append, 1, __pyx_k20, sizeof(__pyx_k20)},
  {&__pyx_n_has_key, 1, __pyx_k19, sizeof(__pyx_k19)},
  {&__pyx_n_release, 1, __pyx_k17, sizeof(__pyx_k17)},
  {&__pyx_n_remove, 1, __pyx_k23, sizeof(__pyx_k23)},
  {&__pyx_n_threading, 1, __pyx_k34, sizeof(__pyx_k34)},
  {&__pyx_n_values, 1, __pyx_k30, sizeof(__pyx_k30)},
  {&__pyx_k3p, 0, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_k4p, 0, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_k5p, 0, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_k6p, 0, __pyx_k6, sizeof(__pyx_k6)},
  {&__pyx_k7p, 0, __pyx_k7, sizeof(__pyx_k7)},
  {&__pyx_k11p, 0, __pyx_k11, sizeof(__pyx_k11)},
  {&__pyx_k15p, 0, __pyx_k15, sizeof(__pyx_k15)},
  {&__pyx_k22p, 0, __pyx_k22, sizeof(__pyx_k22)},
  {&__pyx_k25p, 0, __pyx_k25, sizeof(__pyx_k25)},
  {&__pyx_k27p, 0, __pyx_k27, sizeof(__pyx_k27)},
  {&__pyx_k28p, 0, __pyx_k28, sizeof(__pyx_k28)},
  {&__pyx_k32p, 0, __pyx_k32, sizeof(__pyx_k32)},
  {0, 0, 0, 0}
};

static int __pyx_d1;
static PyObject *__pyx_d2;
static PyObject *__pyx_d3;
static PyObject *__pyx_d4;
static PyObject *__pyx_d5;
static PyObject *__pyx_d6;
static PyObject *__pyx_d7;
static PyObject *__pyx_d8;
static PyObject *__pyx_d9;
static PyObject *__pyx_d10;
static PyObject *__pyx_d11;
static PyObject *__pyx_d12;
static PyObject *__pyx_d13;
static PyObject *__pyx_d14;
static PyObject *__pyx_d15;


/* Implementation of clist */

static PyObject *__pyx_f_5clist_EventRemove(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5clist_EventRemove[] = "Removes an event for a contact from the clist.\n	hContact - the contact handle to remove the event for\n	hEvent - the event handle to remove\n	";
static PyObject *__pyx_f_5clist_EventRemove(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_hContact = 0;
  PyObject *__pyx_v_hEvent = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"hContact","hEvent",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_hContact, &__pyx_v_hEvent)) return 0;
  Py_INCREF(__pyx_v_hContact);
  Py_INCREF(__pyx_v_hEvent);
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_CallService); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyTuple_New(3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
  Py_INCREF(__pyx_k3p);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_k3p);
  Py_INCREF(__pyx_v_hContact);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_v_hContact);
  Py_INCREF(__pyx_v_hEvent);
  PyTuple_SET_ITEM(__pyx_1, 2, __pyx_v_hEvent);
  __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("clist.EventRemove");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_hContact);
  Py_DECREF(__pyx_v_hEvent);
  return __pyx_r;
}

static PyObject *__pyx_f_5clist_SetStatusMode(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5clist_SetStatusMode[] = "SetStatusMode(int mode)\n	Sets the global status to mode.\n	";
static PyObject *__pyx_f_5clist_SetStatusMode(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_mode;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"mode",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "i", __pyx_argnames, &__pyx_v_mode)) return 0;
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_CallService); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyInt_FromLong(__pyx_v_mode); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  Py_INCREF(__pyx_k4p);
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_k4p);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_1);
  PyTuple_SET_ITEM(__pyx_4, 2, __pyx_3);
  __pyx_1 = 0;
  __pyx_3 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("clist.SetStatusMode");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static PyObject *__pyx_f_5clist_GetStatusMode(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5clist_GetStatusMode[] = "GetStatusMode().\n	Returns the current global status mode. Returns one of the clist.STATUS_* constants. \n	";
static PyObject *__pyx_f_5clist_GetStatusMode(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_CallService); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
  Py_INCREF(__pyx_k5p);
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_k5p);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_1);
  PyTuple_SET_ITEM(__pyx_4, 2, __pyx_3);
  __pyx_1 = 0;
  __pyx_3 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("clist.GetStatusMode");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static PyObject *__pyx_f_5clist_GetStatusDescription(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5clist_GetStatusDescription[] = "GetStatusDescription(int mode, int flags = 0).\n	Returns the status description for the given mode. Returns None if the statums mode is unknown.\n	";
static PyObject *__pyx_f_5clist_GetStatusDescription(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_mode;
  int __pyx_v_flags;
  char *__pyx_v_buff;
  long __pyx_v_tmp;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  long __pyx_5;
  int __pyx_6;
  static char *__pyx_argnames[] = {"mode","flags",0};
  __pyx_v_flags = __pyx_d1;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "i|i", __pyx_argnames, &__pyx_v_mode, &__pyx_v_flags)) return 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":68 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_CallService); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyInt_FromLong(__pyx_v_mode); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_v_flags); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
  Py_INCREF(__pyx_k6p);
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_k6p);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_1);
  PyTuple_SET_ITEM(__pyx_4, 2, __pyx_3);
  __pyx_1 = 0;
  __pyx_3 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_5 = PyInt_AsLong(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_v_tmp = __pyx_5;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":69 */
  __pyx_v_buff = ((char *)__pyx_v_tmp);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":70 */
  __pyx_6 = (__pyx_v_buff == NULL);
  if (__pyx_6) {
    Py_INCREF(Py_None);
    __pyx_r = Py_None;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":72 */
  __pyx_3 = PyString_FromString(__pyx_v_buff); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("clist.GetStatusDescription");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static PyObject *__pyx_f_5clist_GetContactDisplayName(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5clist_GetContactDisplayName[] = "GetContactDisplayName(hContact, flags = 0).\n	Returns the contact\'s display name.\n	";
static PyObject *__pyx_f_5clist_GetContactDisplayName(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  long __pyx_v_hContact;
  PyObject *__pyx_v_flags = 0;
  char *__pyx_v_buffer;
  long __pyx_v_tmp;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  long __pyx_4;
  static char *__pyx_argnames[] = {"hContact","flags",0};
  __pyx_v_flags = __pyx_d2;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "l|O", __pyx_argnames, &__pyx_v_hContact, &__pyx_v_flags)) return 0;
  Py_INCREF(__pyx_v_flags);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":80 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_CallService); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyInt_FromLong(__pyx_v_hContact); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(3); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  Py_INCREF(__pyx_k7p);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_k7p);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_1);
  Py_INCREF(__pyx_v_flags);
  PyTuple_SET_ITEM(__pyx_3, 2, __pyx_v_flags);
  __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_4 = PyInt_AsLong(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_v_tmp = __pyx_4;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":81 */
  __pyx_v_buffer = ((char *)__pyx_v_tmp);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":82 */
  __pyx_2 = PyString_FromString(__pyx_v_buffer); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("clist.GetContactDisplayName");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_flags);
  return __pyx_r;
}

static PyObject *__pyx_f_5clist_AddMenuItem(char *__pyx_v_menuType,char *__pyx_v_name,int __pyx_v_position,char *__pyx_v_service,char *__pyx_v_contactOwner,int __pyx_v_flags,char *__pyx_v_popupName,int __pyx_v_popupPosition,int __pyx_v_icon) {
  CLISTMENUITEM __pyx_v_clmi;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":86 */
  __pyx_v_clmi.cbSize = (sizeof(CLISTMENUITEM));

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":87 */
  __pyx_v_clmi.pszName = __pyx_v_name;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":88 */
  __pyx_v_clmi.flags = __pyx_v_flags;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":89 */
  __pyx_v_clmi.position = __pyx_v_position;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":90 */
  __pyx_v_clmi.hIcon = __pyx_v_icon;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":91 */
  __pyx_v_clmi.pszService = __pyx_v_service;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":92 */
  __pyx_v_clmi.pszPopupName = __pyx_v_popupName;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":93 */
  __pyx_v_clmi.popupPosition = __pyx_v_popupPosition;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":94 */
  __pyx_v_clmi.hotKey = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":95 */
  __pyx_v_clmi.pszContactOwner = __pyx_v_contactOwner;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":96 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_CallService); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyString_FromString(__pyx_v_menuType); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
  __pyx_4 = PyInt_FromLong(((long)(&__pyx_v_clmi))); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_1);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_3);
  PyTuple_SET_ITEM(__pyx_5, 2, __pyx_4);
  __pyx_1 = 0;
  __pyx_3 = 0;
  __pyx_4 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_5); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("clist.AddMenuItem");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static PyObject *__pyx_f_5clist_AddMainMenuItem(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5clist_AddMainMenuItem[] = "Adds a new menu item in miranda\'s main menu.\n	AddMainMenuItem(name, position, service, flags = 0, popupName = None, popupPosition = 0, icon = 0)\n		name - the name of the menu item.\n		position - item position in menu\n		service - service string. Will be called when the user selects the menu entry. wParam = 0, lParam = hwndContactList.\n		flags - 1 = grayed, 2 = checked, keep untranslated = 1024, iconfromicolib = 2048.\n		popupName - Name of the popup menu that this item is on. If this item is None then menu item is on the root of the menu.\n		popupPosition - valid only if popupName != None. Position of the popup menu in the root menu.\n		icon - icon handle. windows api stuff ...\n	Returns a handle to the menu item. \n	";
static PyObject *__pyx_f_5clist_AddMainMenuItem(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_name = 0;
  PyObject *__pyx_v_position = 0;
  PyObject *__pyx_v_service = 0;
  PyObject *__pyx_v_flags = 0;
  PyObject *__pyx_v_popupName = 0;
  PyObject *__pyx_v_popupPosition = 0;
  PyObject *__pyx_v_icon = 0;
  char *__pyx_v_buffer;
  PyObject *__pyx_r;
  int __pyx_1;
  char *__pyx_2;
  char *__pyx_3;
  int __pyx_4;
  int __pyx_5;
  int __pyx_6;
  PyObject *__pyx_7 = 0;
  static char *__pyx_argnames[] = {"name","position","service","flags","popupName","popupPosition","icon",0};
  __pyx_v_flags = __pyx_d3;
  __pyx_v_popupName = __pyx_d4;
  __pyx_v_popupPosition = __pyx_d5;
  __pyx_v_icon = __pyx_d6;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO|OOOO", __pyx_argnames, &__pyx_v_name, &__pyx_v_position, &__pyx_v_service, &__pyx_v_flags, &__pyx_v_popupName, &__pyx_v_popupPosition, &__pyx_v_icon)) return 0;
  Py_INCREF(__pyx_v_name);
  Py_INCREF(__pyx_v_position);
  Py_INCREF(__pyx_v_service);
  Py_INCREF(__pyx_v_flags);
  Py_INCREF(__pyx_v_popupName);
  Py_INCREF(__pyx_v_popupPosition);
  Py_INCREF(__pyx_v_icon);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":111 */
  __pyx_v_buffer = NULL;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":112 */
  __pyx_1 = __pyx_v_popupName != Py_None;
  if (__pyx_1) {
    __pyx_2 = PyString_AsString(__pyx_v_popupName); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
    __pyx_v_buffer = __pyx_2;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":114 */
  __pyx_2 = PyString_AsString(__pyx_v_name); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
  __pyx_1 = PyInt_AsLong(__pyx_v_position); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
  __pyx_3 = PyString_AsString(__pyx_v_service); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
  __pyx_4 = PyInt_AsLong(__pyx_v_flags); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
  __pyx_5 = PyInt_AsLong(__pyx_v_popupPosition); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
  __pyx_6 = PyInt_AsLong(__pyx_v_icon); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
  __pyx_7 = __pyx_f_5clist_AddMenuItem(__pyx_k8,__pyx_2,__pyx_1,__pyx_3,NULL,__pyx_4,__pyx_v_buffer,__pyx_5,__pyx_6); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
  __pyx_r = __pyx_7;
  __pyx_7 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_7);
  __Pyx_AddTraceback("clist.AddMainMenuItem");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_name);
  Py_DECREF(__pyx_v_position);
  Py_DECREF(__pyx_v_service);
  Py_DECREF(__pyx_v_flags);
  Py_DECREF(__pyx_v_popupName);
  Py_DECREF(__pyx_v_popupPosition);
  Py_DECREF(__pyx_v_icon);
  return __pyx_r;
}

static PyObject *__pyx_f_5clist_AddContactMenuItem(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5clist_AddContactMenuItem[] = "Adds a new menu item in a contact\'s menu.\n	AddContactMenuItem(hContact, name, position, service, contactOwner = None, flags = 0, icon = 0)\n		name - the name of the menu item.\n		position - item position in menu\n		service - service string. Will be called when the user selects the menu entry. wParam = contact handle, lParam = 0.\n		contactOwner - the protocol for which the item will be shown. If contactOwner is None then the item will be shown for all protocols.\n		flags - 1 = grayed, 2 = checked, hidden = 4, notoffline = 8 (won\'t appear for offline contacts), notonline = 16, notonlist = 32 (will appear for contacts that aren\'t on the user\'s list), notofflist = 64, keep untranslated = 1024, iconfromicolib = 2048.\n		icon - icon handle. windows api stuff ...\n	Returns a handle to the menu item.\n	";
static PyObject *__pyx_f_5clist_AddContactMenuItem(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_name = 0;
  PyObject *__pyx_v_position = 0;
  PyObject *__pyx_v_service = 0;
  PyObject *__pyx_v_contactOwner = 0;
  PyObject *__pyx_v_flags = 0;
  PyObject *__pyx_v_icon = 0;
  char *__pyx_v_buffer;
  PyObject *__pyx_r;
  int __pyx_1;
  char *__pyx_2;
  char *__pyx_3;
  int __pyx_4;
  int __pyx_5;
  PyObject *__pyx_6 = 0;
  static char *__pyx_argnames[] = {"name","position","service","contactOwner","flags","icon",0};
  __pyx_v_contactOwner = __pyx_d7;
  __pyx_v_flags = __pyx_d8;
  __pyx_v_icon = __pyx_d9;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO|OOO", __pyx_argnames, &__pyx_v_name, &__pyx_v_position, &__pyx_v_service, &__pyx_v_contactOwner, &__pyx_v_flags, &__pyx_v_icon)) return 0;
  Py_INCREF(__pyx_v_name);
  Py_INCREF(__pyx_v_position);
  Py_INCREF(__pyx_v_service);
  Py_INCREF(__pyx_v_contactOwner);
  Py_INCREF(__pyx_v_flags);
  Py_INCREF(__pyx_v_icon);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":128 */
  __pyx_v_buffer = NULL;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":129 */
  __pyx_1 = __pyx_v_contactOwner != Py_None;
  if (__pyx_1) {
    __pyx_2 = PyString_AsString(__pyx_v_contactOwner); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 130; goto __pyx_L1;}
    __pyx_v_buffer = __pyx_2;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":131 */
  __pyx_2 = PyString_AsString(__pyx_v_name); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  __pyx_1 = PyInt_AsLong(__pyx_v_position); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  __pyx_3 = PyString_AsString(__pyx_v_service); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  __pyx_4 = PyInt_AsLong(__pyx_v_flags); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  __pyx_5 = PyInt_AsLong(__pyx_v_icon); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  __pyx_6 = __pyx_f_5clist_AddMenuItem(__pyx_k9,__pyx_2,__pyx_1,__pyx_3,__pyx_v_buffer,__pyx_4,NULL,0,__pyx_5); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  __pyx_r = __pyx_6;
  __pyx_6 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_6);
  __Pyx_AddTraceback("clist.AddContactMenuItem");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_name);
  Py_DECREF(__pyx_v_position);
  Py_DECREF(__pyx_v_service);
  Py_DECREF(__pyx_v_contactOwner);
  Py_DECREF(__pyx_v_flags);
  Py_DECREF(__pyx_v_icon);
  return __pyx_r;
}

static PyObject *__pyx_f_5clist_AddStatusMenuItem(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5clist_AddStatusMenuItem[] = "Adds a new menu item in the status menu.\n	AddStatusMenuItem(hContact, name, position, service, contactOwner = None, flags = 0, icon = 0)\n		name - the name of the menu item.\n		position - item position in menu\n		service - service string. Will be called when the user selects the menu entry. wParam = contact handle, lParam = 0.\n		contactOwner - the protocol for which the item will be shown. If contactOwner is None then the item will be shown for all protocols.\n		flags - 1 = grayed, 2 = checked, hidden = 4, notoffline = 8 (won\'t appear for offline contacts), notonline = 16, notonlist = 32 (won\'t appear for contacts that aren\'t on the user\'s list), notofflist = 64, keep untranslated = 1024, iconfromicolib = 2048.\n		icon - icon handle. windows api stuff ...\n	Returns a handle to the menu item.\n	";
static PyObject *__pyx_f_5clist_AddStatusMenuItem(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_name = 0;
  PyObject *__pyx_v_position = 0;
  PyObject *__pyx_v_service = 0;
  PyObject *__pyx_v_contactOwner = 0;
  PyObject *__pyx_v_flags = 0;
  PyObject *__pyx_v_icon = 0;
  char *__pyx_v_buffer;
  PyObject *__pyx_r;
  int __pyx_1;
  char *__pyx_2;
  char *__pyx_3;
  int __pyx_4;
  int __pyx_5;
  PyObject *__pyx_6 = 0;
  static char *__pyx_argnames[] = {"name","position","service","contactOwner","flags","icon",0};
  __pyx_v_contactOwner = __pyx_d10;
  __pyx_v_flags = __pyx_d11;
  __pyx_v_icon = __pyx_d12;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO|OOO", __pyx_argnames, &__pyx_v_name, &__pyx_v_position, &__pyx_v_service, &__pyx_v_contactOwner, &__pyx_v_flags, &__pyx_v_icon)) return 0;
  Py_INCREF(__pyx_v_name);
  Py_INCREF(__pyx_v_position);
  Py_INCREF(__pyx_v_service);
  Py_INCREF(__pyx_v_contactOwner);
  Py_INCREF(__pyx_v_flags);
  Py_INCREF(__pyx_v_icon);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":145 */
  __pyx_v_buffer = NULL;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":146 */
  __pyx_1 = __pyx_v_contactOwner != Py_None;
  if (__pyx_1) {
    __pyx_2 = PyString_AsString(__pyx_v_contactOwner); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
    __pyx_v_buffer = __pyx_2;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":148 */
  __pyx_2 = PyString_AsString(__pyx_v_name); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L1;}
  __pyx_1 = PyInt_AsLong(__pyx_v_position); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L1;}
  __pyx_3 = PyString_AsString(__pyx_v_service); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L1;}
  __pyx_4 = PyInt_AsLong(__pyx_v_flags); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L1;}
  __pyx_5 = PyInt_AsLong(__pyx_v_icon); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L1;}
  __pyx_6 = __pyx_f_5clist_AddMenuItem(__pyx_k10,__pyx_2,__pyx_1,__pyx_3,__pyx_v_buffer,__pyx_4,NULL,0,__pyx_5); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L1;}
  __pyx_r = __pyx_6;
  __pyx_6 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_6);
  __Pyx_AddTraceback("clist.AddStatusMenuItem");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_name);
  Py_DECREF(__pyx_v_position);
  Py_DECREF(__pyx_v_service);
  Py_DECREF(__pyx_v_contactOwner);
  Py_DECREF(__pyx_v_flags);
  Py_DECREF(__pyx_v_icon);
  return __pyx_r;
}

static PyObject *__pyx_f_5clist_ModifyMenuItem(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5clist_ModifyMenuItem[] = "Modifies a menu item. Parameters that have the value None will not be changed.\n		hMenuItem - the handle of the menu item as returned by one of the Add*MenuItem methods.\n		name - new menu item name.\n		flags - new flags for the menu item.\n		icon - new menu icon. windows api stuff ...\n		hotkey - new menu item hotkey.\n	Returns 0 on success, nonzero on failure.\n	";
static PyObject *__pyx_f_5clist_ModifyMenuItem(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_hMenuItem = 0;
  PyObject *__pyx_v_name = 0;
  PyObject *__pyx_v_flags = 0;
  PyObject *__pyx_v_icon = 0;
  PyObject *__pyx_v_hotkey = 0;
  CLISTMENUITEM __pyx_v_clmi;
  PyObject *__pyx_r;
  int __pyx_1;
  __pyx_t_5clist_DWORD __pyx_2;
  char *__pyx_3;
  long __pyx_4;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  static char *__pyx_argnames[] = {"hMenuItem","name","flags","icon","hotkey",0};
  __pyx_v_flags = __pyx_d13;
  __pyx_v_icon = __pyx_d14;
  __pyx_v_hotkey = __pyx_d15;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO|OOO", __pyx_argnames, &__pyx_v_hMenuItem, &__pyx_v_name, &__pyx_v_flags, &__pyx_v_icon, &__pyx_v_hotkey)) return 0;
  Py_INCREF(__pyx_v_hMenuItem);
  Py_INCREF(__pyx_v_name);
  Py_INCREF(__pyx_v_flags);
  Py_INCREF(__pyx_v_icon);
  Py_INCREF(__pyx_v_hotkey);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":160 */
  __pyx_v_clmi.cbSize = (sizeof(CLISTMENUITEM));

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":161 */
  __pyx_v_clmi.flags = 0;
  __pyx_v_clmi.position = 0;
  __pyx_v_clmi.popupPosition = 0;
  __pyx_v_clmi.hotKey = 0;
  __pyx_v_clmi.hIcon = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":162 */
  __pyx_v_clmi.pszName = NULL;
  __pyx_v_clmi.pszService = NULL;
  __pyx_v_clmi.pszPopupName = NULL;
  __pyx_v_clmi.pszContactOwner = NULL;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":164 */
  if (PyObject_Cmp(__pyx_v_flags, Py_None, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
  __pyx_1 = __pyx_1 != 0;
  if (__pyx_1) {

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":165 */
    __pyx_2 = PyInt_AsUnsignedLongMask(__pyx_v_flags); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 165; goto __pyx_L1;}
    __pyx_v_clmi.flags = __pyx_2;

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":166 */
    __pyx_v_clmi.flags = (__pyx_v_clmi.flags | 0x40000000);
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":167 */
  if (PyObject_Cmp(__pyx_v_name, Py_None, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 167; goto __pyx_L1;}
  __pyx_1 = __pyx_1 != 0;
  if (__pyx_1) {

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":168 */
    __pyx_v_clmi.flags = (__pyx_v_clmi.flags | 0x80000000);

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":169 */
    __pyx_3 = PyString_AsString(__pyx_v_name); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; goto __pyx_L1;}
    __pyx_v_clmi.pszName = __pyx_3;
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":170 */
  if (PyObject_Cmp(__pyx_v_icon, Py_None, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 170; goto __pyx_L1;}
  __pyx_1 = __pyx_1 != 0;
  if (__pyx_1) {

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":171 */
    __pyx_v_clmi.flags = (__pyx_v_clmi.flags | 0x20000000);

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":172 */
    __pyx_4 = PyInt_AsLong(__pyx_v_icon); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; goto __pyx_L1;}
    __pyx_v_clmi.hIcon = __pyx_4;
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":173 */
  if (PyObject_Cmp(__pyx_v_hotkey, Py_None, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 173; goto __pyx_L1;}
  __pyx_1 = __pyx_1 != 0;
  if (__pyx_1) {

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":174 */
    __pyx_v_clmi.flags = (__pyx_v_clmi.flags | 0x10000000);

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":175 */
    __pyx_2 = PyInt_AsUnsignedLongMask(__pyx_v_hotkey); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 175; goto __pyx_L1;}
    __pyx_v_clmi.hotKey = __pyx_2;
    goto __pyx_L5;
  }
  __pyx_L5:;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":177 */
  __pyx_5 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; goto __pyx_L1;}
  __pyx_6 = PyObject_GetAttr(__pyx_5, __pyx_n_CallService); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_5 = PyInt_FromLong(((long)(&__pyx_v_clmi))); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; goto __pyx_L1;}
  __pyx_7 = PyTuple_New(3); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; goto __pyx_L1;}
  Py_INCREF(__pyx_k11p);
  PyTuple_SET_ITEM(__pyx_7, 0, __pyx_k11p);
  Py_INCREF(__pyx_v_hMenuItem);
  PyTuple_SET_ITEM(__pyx_7, 1, __pyx_v_hMenuItem);
  PyTuple_SET_ITEM(__pyx_7, 2, __pyx_5);
  __pyx_5 = 0;
  __pyx_5 = PyObject_CallObject(__pyx_6, __pyx_7); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; goto __pyx_L1;}
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  Py_DECREF(__pyx_7); __pyx_7 = 0;
  __pyx_r = __pyx_5;
  __pyx_5 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  __Pyx_AddTraceback("clist.ModifyMenuItem");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_hMenuItem);
  Py_DECREF(__pyx_v_name);
  Py_DECREF(__pyx_v_flags);
  Py_DECREF(__pyx_v_icon);
  Py_DECREF(__pyx_v_hotkey);
  return __pyx_r;
}

static PyObject *__pyx_f_5clist___CallEventCallbacks(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5clist___CallEventCallbacks(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_event = 0;
  PyObject *__pyx_v_wParam = 0;
  PyObject *__pyx_v_lParam = 0;
  PyObject *__pyx_v_res;
  PyObject *__pyx_v_list;
  PyObject *__pyx_v_callback;
  PyObject *__pyx_v_e;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  static char *__pyx_argnames[] = {"event","wParam","lParam",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_event, &__pyx_v_wParam, &__pyx_v_lParam)) return 0;
  Py_INCREF(__pyx_v_event);
  Py_INCREF(__pyx_v_wParam);
  Py_INCREF(__pyx_v_lParam);
  __pyx_v_res = Py_None; Py_INCREF(Py_None);
  __pyx_v_list = Py_None; Py_INCREF(Py_None);
  __pyx_v_callback = Py_None; Py_INCREF(Py_None);
  __pyx_v_e = Py_None; Py_INCREF(Py_None);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":186 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 186; goto __pyx_L1;}
  Py_DECREF(__pyx_v_res);
  __pyx_v_res = __pyx_1;
  __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":187 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n___clistLock); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 187; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_acquire); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 187; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 187; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":188 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_HookedClistEventsCallbacks); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 188; goto __pyx_L1;}
  __pyx_1 = PyObject_GetItem(__pyx_2, __pyx_v_event); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 188; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_v_list);
  __pyx_v_list = __pyx_1;
  __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":189 */
  __pyx_2 = PyObject_GetIter(__pyx_v_list); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 189; goto __pyx_L1;}
  for (;;) {
    __pyx_1 = PyIter_Next(__pyx_2);
    if (!__pyx_1) {
      if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 189; goto __pyx_L1;}
      break;
    }
    Py_DECREF(__pyx_v_callback);
    __pyx_v_callback = __pyx_1;
    __pyx_1 = 0;

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":190 */
    /*try:*/ {
      __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 191; goto __pyx_L4;}
      Py_INCREF(__pyx_v_wParam);
      PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_wParam);
      Py_INCREF(__pyx_v_lParam);
      PyTuple_SET_ITEM(__pyx_1, 1, __pyx_v_lParam);
      __pyx_3 = PyObject_CallObject(__pyx_v_callback, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 191; goto __pyx_L4;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      Py_DECREF(__pyx_v_res);
      __pyx_v_res = __pyx_3;
      __pyx_3 = 0;
    }
    goto __pyx_L5;
    __pyx_L4:;
    Py_XDECREF(__pyx_1); __pyx_1 = 0;
    Py_XDECREF(__pyx_3); __pyx_3 = 0;

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":192 */
    __pyx_4 = PyErr_ExceptionMatches(PyExc_Exception);
    if (__pyx_4) {
      __Pyx_AddTraceback("clist.__CallEventCallbacks");
      if (__Pyx_GetException(&__pyx_1, &__pyx_3, &__pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 192; goto __pyx_L1;}
      Py_INCREF(__pyx_3);
      Py_DECREF(__pyx_v_e);
      __pyx_v_e = __pyx_3;
      __pyx_6 = PyObject_GetAttr(__pyx_v_callback, __pyx_n___name__); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 193; goto __pyx_L1;}
      __pyx_7 = PyTuple_New(2); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 193; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_7, 0, __pyx_6);
      Py_INCREF(__pyx_v_e);
      PyTuple_SET_ITEM(__pyx_7, 1, __pyx_v_e);
      __pyx_6 = 0;
      __pyx_6 = PyNumber_Remainder(__pyx_k15p, __pyx_7); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 193; goto __pyx_L1;}
      Py_DECREF(__pyx_7); __pyx_7 = 0;
      if (__Pyx_PrintItem(__pyx_6) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 193; goto __pyx_L1;}
      Py_DECREF(__pyx_6); __pyx_6 = 0;
      if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 193; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      goto __pyx_L5;
    }
    goto __pyx_L1;
    __pyx_L5:;

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":194 */
    if (PyObject_Cmp(__pyx_v_res, Py_None, &__pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 194; goto __pyx_L1;}
    __pyx_4 = __pyx_4 != 0;
    if (__pyx_4) {
      __pyx_7 = PyInt_FromLong(0); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 194; goto __pyx_L1;}
      if (PyObject_Cmp(__pyx_v_res, __pyx_7, &__pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 194; goto __pyx_L1;}
      __pyx_4 = __pyx_4 != 0;
      Py_DECREF(__pyx_7); __pyx_7 = 0;
    }
    if (__pyx_4) {
      goto __pyx_L3;
      goto __pyx_L6;
    }
    __pyx_L6:;
  }
  __pyx_L3:;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":196 */
  if (PyObject_Cmp(__pyx_v_res, Py_None, &__pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 196; goto __pyx_L1;}
  __pyx_4 = __pyx_4 == 0;
  if (__pyx_4) {
    __pyx_6 = PyInt_FromLong(0); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 197; goto __pyx_L1;}
    Py_DECREF(__pyx_v_res);
    __pyx_v_res = __pyx_6;
    __pyx_6 = 0;
    goto __pyx_L7;
  }
  __pyx_L7:;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":198 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n___clistLock); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 198; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_1, __pyx_n_release); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 198; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_5 = PyObject_CallObject(__pyx_3, 0); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 198; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":200 */
  Py_INCREF(__pyx_v_res);
  __pyx_r = __pyx_v_res;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  __Pyx_AddTraceback("clist.__CallEventCallbacks");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_res);
  Py_DECREF(__pyx_v_list);
  Py_DECREF(__pyx_v_callback);
  Py_DECREF(__pyx_v_e);
  Py_DECREF(__pyx_v_event);
  Py_DECREF(__pyx_v_wParam);
  Py_DECREF(__pyx_v_lParam);
  return __pyx_r;
}

static PyObject *__pyx_f_5clist_HookClistEvent(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5clist_HookClistEvent[] = "Hooks a clist event.\n	HookClistEvent(event, callback)\n		event - the event string. To find out all available events type \"print clist.HookedClistEvents.keys()\" (do not modify this dictionary !!!)\n		callback - python function that gets called when the event occurs. The declaration is OnEvent(wParam, lParam); the actual parameters depend on the event.\n	";
static PyObject *__pyx_f_5clist_HookClistEvent(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_event = 0;
  PyObject *__pyx_v_callback = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  static char *__pyx_argnames[] = {"event","callback",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_event, &__pyx_v_callback)) return 0;
  Py_INCREF(__pyx_v_event);
  Py_INCREF(__pyx_v_callback);
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_HookedClistEvents); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_has_key); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; goto __pyx_L1;}
  Py_INCREF(__pyx_v_event);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_event);
  __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_4 = PyObject_IsTrue(__pyx_3); if (__pyx_4 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (__pyx_4) {
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_HookedClistEventsCallbacks); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 209; goto __pyx_L1;}
    __pyx_1 = PyObject_GetItem(__pyx_2, __pyx_v_event); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 209; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_3 = PyObject_GetAttr(__pyx_1, __pyx_n_append); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 209; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 209; goto __pyx_L1;}
    Py_INCREF(__pyx_v_callback);
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_callback);
    __pyx_1 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 209; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    goto __pyx_L2;
  }
  /*else*/ {
    __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L1;}
    __pyx_2 = PyObject_GetAttr(__pyx_3, __pyx_n_NoSuchEventError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_1 = PyNumber_Remainder(__pyx_k22p, __pyx_v_event); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_1);
    __pyx_1 = 0;
    __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_1, 0, 0);
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L1;}
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("clist.HookClistEvent");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_event);
  Py_DECREF(__pyx_v_callback);
  return __pyx_r;
}

static PyObject *__pyx_f_5clist_UnhookClistEvent(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5clist_UnhookClistEvent[] = "Unhooks a previously hooked clist event.\n	UnhookClistEvent(event, callback)\n		event - the event to unhook. Must have been previously hooked with a call to HookClistEvent.\n		callback - the event callback.\n	Both parameters are required because the same callback could be used to hook multiple events.\n	";
static PyObject *__pyx_f_5clist_UnhookClistEvent(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_event = 0;
  PyObject *__pyx_v_callback = 0;
  PyObject *__pyx_v_e;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  static char *__pyx_argnames[] = {"event","callback",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_event, &__pyx_v_callback)) return 0;
  Py_INCREF(__pyx_v_event);
  Py_INCREF(__pyx_v_callback);
  __pyx_v_e = Py_None; Py_INCREF(Py_None);
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_HookedClistEvents); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 220; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_has_key); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 220; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 220; goto __pyx_L1;}
  Py_INCREF(__pyx_v_event);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_event);
  __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 220; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_4 = PyObject_IsTrue(__pyx_3); if (__pyx_4 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 220; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (__pyx_4) {
    /*try:*/ {
      __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_HookedClistEventsCallbacks); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 222; goto __pyx_L3;}
      __pyx_1 = PyObject_GetItem(__pyx_2, __pyx_v_event); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 222; goto __pyx_L3;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      __pyx_3 = PyObject_GetAttr(__pyx_1, __pyx_n_remove); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 222; goto __pyx_L3;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 222; goto __pyx_L3;}
      Py_INCREF(__pyx_v_callback);
      PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_callback);
      __pyx_1 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 222; goto __pyx_L3;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_1); __pyx_1 = 0;
    }
    goto __pyx_L4;
    __pyx_L3:;
    Py_XDECREF(__pyx_3); __pyx_3 = 0;
    Py_XDECREF(__pyx_2); __pyx_2 = 0;
    Py_XDECREF(__pyx_1); __pyx_1 = 0;

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":223 */
    __pyx_4 = PyErr_ExceptionMatches(PyExc_Exception);
    if (__pyx_4) {
      __Pyx_AddTraceback("clist.UnhookClistEvent");
      if (__Pyx_GetException(&__pyx_3, &__pyx_2, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 223; goto __pyx_L1;}
      Py_INCREF(__pyx_2);
      Py_DECREF(__pyx_v_e);
      __pyx_v_e = __pyx_2;
      __pyx_5 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 224; goto __pyx_L1;}
      __pyx_6 = PyObject_GetAttr(__pyx_5, __pyx_n_NoSuchCallbackForEventError); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 224; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      __pyx_5 = PyTuple_New(2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 224; goto __pyx_L1;}
      Py_INCREF(__pyx_v_event);
      PyTuple_SET_ITEM(__pyx_5, 0, __pyx_v_event);
      Py_INCREF(__pyx_v_callback);
      PyTuple_SET_ITEM(__pyx_5, 1, __pyx_v_callback);
      __pyx_7 = PyNumber_Remainder(__pyx_k25p, __pyx_5); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 224; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      __pyx_5 = PyTuple_New(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 224; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_5, 0, __pyx_7);
      __pyx_7 = 0;
      __pyx_7 = PyObject_CallObject(__pyx_6, __pyx_5); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 224; goto __pyx_L1;}
      Py_DECREF(__pyx_6); __pyx_6 = 0;
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      __Pyx_Raise(__pyx_7, 0, 0);
      Py_DECREF(__pyx_7); __pyx_7 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 224; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      goto __pyx_L4;
    }
    goto __pyx_L1;
    __pyx_L4:;
    goto __pyx_L2;
  }
  /*else*/ {
    __pyx_6 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 226; goto __pyx_L1;}
    __pyx_5 = PyObject_GetAttr(__pyx_6, __pyx_n_NoSuchEventError); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 226; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __pyx_7 = PyNumber_Remainder(__pyx_k22p, __pyx_v_event); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 226; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 226; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_7);
    __pyx_7 = 0;
    __pyx_2 = PyObject_CallObject(__pyx_5, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 226; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_2, 0, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 226; goto __pyx_L1;}
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  __Pyx_AddTraceback("clist.UnhookClistEvent");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_e);
  Py_DECREF(__pyx_v_event);
  Py_DECREF(__pyx_v_callback);
  return __pyx_r;
}

static int __pyx_f_5clist_OnEventStatusChange(long __pyx_v_wParam,long __pyx_v_lParam) {
  PyObject *__pyx_v_tmp;
  int __pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  __pyx_v_tmp = Py_None; Py_INCREF(Py_None);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":230 */
  __pyx_1 = (__pyx_v_lParam == 0);
  if (__pyx_1) {
    Py_INCREF(Py_None);
    Py_DECREF(__pyx_v_tmp);
    __pyx_v_tmp = Py_None;
    goto __pyx_L2;
  }
  /*else*/ {
    __pyx_2 = PyString_FromString(((char *)__pyx_v_lParam)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 233; goto __pyx_L1;}
    Py_DECREF(__pyx_v_tmp);
    __pyx_v_tmp = __pyx_2;
    __pyx_2 = 0;
  }
  __pyx_L2:;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":234 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n___CallEventCallbacks); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 234; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_v_wParam); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 234; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 234; goto __pyx_L1;}
  Py_INCREF(__pyx_k27p);
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_k27p);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_3);
  Py_INCREF(__pyx_v_tmp);
  PyTuple_SET_ITEM(__pyx_4, 2, __pyx_v_tmp);
  __pyx_3 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 234; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_WriteUnraisable("clist.OnEventStatusChange");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_tmp);
  return __pyx_r;
}

static int __pyx_f_5clist_OnPreBuildContactMenu(long __pyx_v_wParam,long __pyx_v_lParam) {
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n___CallEventCallbacks); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 237; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(__pyx_v_wParam); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 237; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_v_lParam); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 237; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 237; goto __pyx_L1;}
  Py_INCREF(__pyx_k28p);
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_k28p);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_2);
  PyTuple_SET_ITEM(__pyx_4, 2, __pyx_3);
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 237; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_WriteUnraisable("clist.OnPreBuildContactMenu");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static PyObject *__pyx_f_5clist___clistAddEventHook(PyObject *__pyx_v_event,__pyx_t_5clist_MIRANDAHOOK __pyx_v_function) {
  PyObject *__pyx_v_handle;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  Py_INCREF(__pyx_v_event);
  __pyx_v_handle = Py_None; Py_INCREF(Py_None);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":240 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 240; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_HookEvent); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 240; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyInt_FromLong(((long)__pyx_v_function)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 240; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 240; goto __pyx_L1;}
  Py_INCREF(__pyx_v_event);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_event);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_1);
  __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 240; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_v_handle);
  __pyx_v_handle = __pyx_1;
  __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":241 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_HookedClistEvents); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 241; goto __pyx_L1;}
  if (PyObject_SetItem(__pyx_2, __pyx_v_event, __pyx_v_handle) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 241; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":242 */
  __pyx_3 = PyList_New(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 242; goto __pyx_L1;}
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_HookedClistEventsCallbacks); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 242; goto __pyx_L1;}
  if (PyObject_SetItem(__pyx_1, __pyx_v_event, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 242; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("clist.__clistAddEventHook");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_handle);
  Py_DECREF(__pyx_v_event);
  return __pyx_r;
}

static PyObject *__pyx_f_5clist___HookClistEvents(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5clist___HookClistEvents(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":245 */
  __pyx_1 = __pyx_f_5clist___clistAddEventHook(__pyx_k27p,__pyx_f_5clist_OnEventStatusChange); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 245; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":246 */
  __pyx_1 = __pyx_f_5clist___clistAddEventHook(__pyx_k28p,__pyx_f_5clist_OnPreBuildContactMenu); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 246; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("clist.__HookClistEvents");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static PyObject *__pyx_f_5clist___UnhookClistEvents(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5clist___UnhookClistEvents(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_handle;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  __pyx_v_handle = Py_None; Py_INCREF(Py_None);
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_HookedClistEvents); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 249; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_values); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 249; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 249; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyObject_GetIter(__pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 249; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  for (;;) {
    __pyx_1 = PyIter_Next(__pyx_2);
    if (!__pyx_1) {
      if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 249; goto __pyx_L1;}
      break;
    }
    Py_DECREF(__pyx_v_handle);
    __pyx_v_handle = __pyx_1;
    __pyx_1 = 0;
    __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 250; goto __pyx_L1;}
    __pyx_3 = PyObject_GetAttr(__pyx_1, __pyx_n_UnhookEvent); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 250; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 250; goto __pyx_L1;}
    Py_INCREF(__pyx_v_handle);
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_handle);
    __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 250; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
  }
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("clist.__UnhookClistEvents");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_handle);
  return __pyx_r;
}

static PyObject *__pyx_f_5clist_OnMirPyClose(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5clist_OnMirPyClose(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":253 */
  if (__Pyx_PrintItem(__pyx_k32p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 253; goto __pyx_L1;}
  if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 253; goto __pyx_L1;}

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":254 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n___UnhookClistEvents); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 254; goto __pyx_L1;}
  __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 254; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("clist.OnMirPyClose");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static struct PyMethodDef __pyx_methods[] = {
  {"EventRemove", (PyCFunction)__pyx_f_5clist_EventRemove, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5clist_EventRemove},
  {"SetStatusMode", (PyCFunction)__pyx_f_5clist_SetStatusMode, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5clist_SetStatusMode},
  {"GetStatusMode", (PyCFunction)__pyx_f_5clist_GetStatusMode, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5clist_GetStatusMode},
  {"GetStatusDescription", (PyCFunction)__pyx_f_5clist_GetStatusDescription, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5clist_GetStatusDescription},
  {"GetContactDisplayName", (PyCFunction)__pyx_f_5clist_GetContactDisplayName, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5clist_GetContactDisplayName},
  {"AddMainMenuItem", (PyCFunction)__pyx_f_5clist_AddMainMenuItem, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5clist_AddMainMenuItem},
  {"AddContactMenuItem", (PyCFunction)__pyx_f_5clist_AddContactMenuItem, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5clist_AddContactMenuItem},
  {"AddStatusMenuItem", (PyCFunction)__pyx_f_5clist_AddStatusMenuItem, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5clist_AddStatusMenuItem},
  {"ModifyMenuItem", (PyCFunction)__pyx_f_5clist_ModifyMenuItem, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5clist_ModifyMenuItem},
  {"__CallEventCallbacks", (PyCFunction)__pyx_f_5clist___CallEventCallbacks, METH_VARARGS|METH_KEYWORDS, 0},
  {"HookClistEvent", (PyCFunction)__pyx_f_5clist_HookClistEvent, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5clist_HookClistEvent},
  {"UnhookClistEvent", (PyCFunction)__pyx_f_5clist_UnhookClistEvent, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5clist_UnhookClistEvent},
  {"__HookClistEvents", (PyCFunction)__pyx_f_5clist___HookClistEvents, METH_VARARGS|METH_KEYWORDS, 0},
  {"__UnhookClistEvents", (PyCFunction)__pyx_f_5clist___UnhookClistEvents, METH_VARARGS|METH_KEYWORDS, 0},
  {"OnMirPyClose", (PyCFunction)__pyx_f_5clist_OnMirPyClose, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initclist(void); /*proto*/
PyMODINIT_FUNC initclist(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  PyObject *__pyx_8 = 0;
  PyObject *__pyx_9 = 0;
  PyObject *__pyx_10 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("clist", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":7 */
  __pyx_1 = __Pyx_Import(__pyx_n_threading, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_threading, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":9 */
  __pyx_1 = __Pyx_Import(__pyx_n_MirPy, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_MirPy, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":11 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_threading); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_RLock); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n___clistLock, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":17 */
  __pyx_2 = PyInt_FromLong(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_STATUS_CONNECTING, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":18 */
  __pyx_1 = PyInt_FromLong(40071); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_STATUS_OFFLINE, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":19 */
  __pyx_2 = PyInt_FromLong(40072); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_STATUS_ONLINE, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":20 */
  __pyx_1 = PyInt_FromLong(40073); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_STATUS_AWAY, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":21 */
  __pyx_2 = PyInt_FromLong(40074); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 21; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_STATUS_DND, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 21; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":22 */
  __pyx_1 = PyInt_FromLong(40075); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 22; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_STATUS_NA, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 22; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":23 */
  __pyx_2 = PyInt_FromLong(40076); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_STATUS_OCCUPIED, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":24 */
  __pyx_1 = PyInt_FromLong(40077); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_STATUS_FREECHAT, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":25 */
  __pyx_2 = PyInt_FromLong(40078); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_STATUS_INVISILE, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":26 */
  __pyx_1 = PyInt_FromLong(40079); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_STATUS_ONTHEPHONE, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":27 */
  __pyx_2 = PyInt_FromLong(40080); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_STATUS_OUTTOLUNCH, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":28 */
  __pyx_1 = PyInt_FromLong(40081); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_STATUS_IDLE, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":62 */
  __pyx_d1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":74 */
  __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
  __pyx_d2 = __pyx_2;
  __pyx_2 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":98 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
  __pyx_d3 = __pyx_1;
  __pyx_1 = 0;
  Py_INCREF(Py_None);
  __pyx_d4 = Py_None;
  __pyx_3 = PyInt_FromLong(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
  __pyx_d5 = __pyx_3;
  __pyx_3 = 0;
  __pyx_4 = PyInt_FromLong(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
  __pyx_d6 = __pyx_4;
  __pyx_4 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":116 */
  Py_INCREF(Py_None);
  __pyx_d7 = Py_None;
  __pyx_5 = PyInt_FromLong(0); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
  __pyx_d8 = __pyx_5;
  __pyx_5 = 0;
  __pyx_6 = PyInt_FromLong(0); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
  __pyx_d9 = __pyx_6;
  __pyx_6 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":133 */
  Py_INCREF(Py_None);
  __pyx_d10 = Py_None;
  __pyx_7 = PyInt_FromLong(0); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}
  __pyx_d11 = __pyx_7;
  __pyx_7 = 0;
  __pyx_8 = PyInt_FromLong(0); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}
  __pyx_d12 = __pyx_8;
  __pyx_8 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":150 */
  Py_INCREF(Py_None);
  __pyx_d13 = Py_None;
  Py_INCREF(Py_None);
  __pyx_d14 = Py_None;
  Py_INCREF(Py_None);
  __pyx_d15 = Py_None;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":182 */
  __pyx_9 = PyDict_New(); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 182; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_HookedClistEvents, __pyx_9) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 182; goto __pyx_L1;}
  Py_DECREF(__pyx_9); __pyx_9 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":183 */
  __pyx_9 = PyDict_New(); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 183; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_HookedClistEventsCallbacks, __pyx_9) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 183; goto __pyx_L1;}
  Py_DECREF(__pyx_9); __pyx_9 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\clist\pyrex\clist.pyx":256 */
  __pyx_9 = __Pyx_GetName(__pyx_m, __pyx_n___HookClistEvents); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 256; goto __pyx_L1;}
  __pyx_10 = PyObject_CallObject(__pyx_9, 0); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 256; goto __pyx_L1;}
  Py_DECREF(__pyx_9); __pyx_9 = 0;
  Py_DECREF(__pyx_10); __pyx_10 = 0;
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  Py_XDECREF(__pyx_8);
  Py_XDECREF(__pyx_9);
  Py_XDECREF(__pyx_10);
  __Pyx_AddTraceback("clist");
}

static char *__pyx_filenames[] = {
  "clist.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static int __Pyx_GetException(PyObject **type, PyObject **value, PyObject **tb) {
    PyThreadState *tstate = PyThreadState_Get();
    PyErr_Fetch(type, value, tb);
    PyErr_NormalizeException(type, value, tb);
    if (PyErr_Occurred())
        goto bad;
    Py_INCREF(*type);
    Py_INCREF(*value);
    Py_INCREF(*tb);
    Py_XDECREF(tstate->exc_type);
    Py_XDECREF(tstate->exc_value);
    Py_XDECREF(tstate->exc_traceback);
    tstate->exc_type = *type;
    tstate->exc_value = *value;
    tstate->exc_traceback = *tb;
    return 0;
bad:
    Py_XDECREF(*type);
    Py_XDECREF(*value);
    Py_XDECREF(*tb);
    return -1;
}

static PyObject *__Pyx_GetStdout(void) {
    PyObject *f = PySys_GetObject("stdout");
    if (!f) {
        PyErr_SetString(PyExc_RuntimeError, "lost sys.stdout");
    }
    return f;
}

static int __Pyx_PrintItem(PyObject *v) {
    PyObject *f;
    
    if (!(f = __Pyx_GetStdout()))
        return -1;
    if (PyFile_SoftSpace(f, 1)) {
        if (PyFile_WriteString(" ", f) < 0)
            return -1;
    }
    if (PyFile_WriteObject(v, f, Py_PRINT_RAW) < 0)
        return -1;
    if (PyString_Check(v)) {
        char *s = PyString_AsString(v);
        Py_ssize_t len = PyString_Size(v);
        if (len > 0 &&
            isspace(Py_CHARMASK(s[len-1])) &&
            s[len-1] != ' ')
                PyFile_SoftSpace(f, 0);
    }
    return 0;
}

static int __Pyx_PrintNewline(void) {
    PyObject *f;
    
    if (!(f = __Pyx_GetStdout()))
        return -1;
    if (PyFile_WriteString("\n", f) < 0)
        return -1;
    PyFile_SoftSpace(f, 0);
    return 0;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    #if PY_VERSION_HEX < 0x02050000
    if (!PyClass_Check(type))
    #else
    if (!PyType_Check(type))
    #endif
    {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        #if PY_VERSION_HEX < 0x02050000
            if (PyInstance_Check(type)) {
                type = (PyObject*) ((PyInstanceObject*)type)->in_class;
                Py_INCREF(type);
            }
            else {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception must be an old-style class or instance");
                goto raise_error;
            }
        #else
            type = (PyObject*) type->ob_type;
            Py_INCREF(type);
            if (!PyType_IsSubtype((PyTypeObject *)type, (PyTypeObject *)PyExc_BaseException)) {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception class must be a subclass of BaseException");
                goto raise_error;
            }
        #endif
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static void __Pyx_WriteUnraisable(char *name) {
    PyObject *old_exc, *old_val, *old_tb;
    PyObject *ctx;
    PyErr_Fetch(&old_exc, &old_val, &old_tb);
    ctx = PyString_FromString(name);
    PyErr_Restore(old_exc, old_val, old_tb);
    if (!ctx)
        ctx = Py_None;
    PyErr_WriteUnraisable(ctx);
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        if (t->i)
            PyString_InternInPlace(t->p);
        ++t;
    }
    return 0;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
