/* Generated by Pyrex 0.9.8.5 on Thu Oct 30 10:45:46 2008 */

#define PY_SSIZE_T_CLEAN
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "malloc.h"
#include "m_database.h"


typedef struct {PyObject **p; int i; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static int __Pyx_GetException(PyObject **type, PyObject **value, PyObject **tb); /*proto*/

static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static void __Pyx_WriteUnraisable(char *name); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from protocols */


/* Declarations from implementation of protocols */

typedef unsigned char __pyx_t_9protocols_BYTE;

typedef unsigned long __pyx_t_9protocols_DWORD;

typedef unsigned short __pyx_t_9protocols_WORD;

typedef unsigned short __pyx_t_9protocols_WCHAR;

typedef __pyx_t_9protocols_BYTE *__pyx_t_9protocols_PBYTE;

typedef int (*__pyx_t_9protocols_MIRANDAHOOK)(long,long);

enum  {
  __pyx_e_9protocols_DBEF_FIRST = 1,
  __pyx_e_9protocols_DBEF_SENT = 2,
  __pyx_e_9protocols_DBEF_READ = 4
};

enum  {
  __pyx_e_9protocols_EVENTTYPE_MESSAGE = 0,
  __pyx_e_9protocols_EVENTTYPE_URL = 1,
  __pyx_e_9protocols_EVENTTYPE_CONTACTS = 2,
  __pyx_e_9protocols_EVENTTYPE_ADDED = 1000,
  __pyx_e_9protocols_EVENTTYPE_AUTHREQUEST = 1001,
  __pyx_e_9protocols_EVENTTYPE_FILE = 1002,
  __pyx_e_9protocols_EVENTTYPE_STATUS = 25368
};

static int __pyx_f_9protocols_OnAuthorisationRequest(long,long); /*proto*/
static void __pyx_f_9protocols___protocolAddEventHook(PyObject *,PyObject *,__pyx_t_9protocols_MIRANDAHOOK); /*proto*/

static char __pyx_k1[] = "module";
static char __pyx_k2[] = "timestamp";
static char __pyx_k3[] = "flags";
static char __pyx_k4[] = "eventType";
static char __pyx_k5[] = "hDBEvent";
static char __pyx_k6[] = "hContact";
static char __pyx_k7[] = "UIN";
static char __pyx_k8[] = "nick";
static char __pyx_k9[] = "firstName";
static char __pyx_k10[] = "lastName";
static char __pyx_k11[] = "email";
static char __pyx_k12[] = "reason";
static char __pyx_k13[] = "Module = ";
static char __pyx_k14[] = "\nTimestamp = ";
static char __pyx_k15[] = "\nhContact = ";
static char __pyx_k16[] = "\nReason = ";
static char __pyx_k17[] = "MirPy";
static char __pyx_k18[] = "CallService";
static char __pyx_k19[] = "/Authorize";
static char __pyx_k20[] = "/AuthDeny";
static char __pyx_k21[] = "__protocolLock";
static char __pyx_k22[] = "acquire";
static char __pyx_k23[] = "HookedProtocolEventCallbacks";
static char __pyx_k24[] = "Error calling '%s' (%s)";
static char __pyx_k25[] = "__name__";
static char __pyx_k26[] = "release";
static char __pyx_k27[] = "HookedProtocolEvents";
static char __pyx_k28[] = "has_key";
static char __pyx_k29[] = "append";
static char __pyx_k30[] = "NoSuchEventError";
static char __pyx_k31[] = "The event '%s' was not found";
static char __pyx_k32[] = "remove";
static char __pyx_k33[] = "NoSuchCallbackForEventError";
static char __pyx_k34[] = "The event '%s' has no callback '%s'";
static char __pyx_k35[] = "The event '%s' was not found.";
static char __pyx_k36[] = "DB/Event/Get";
static char __pyx_k37[] = "DB/Event/GetBlobSize";
static char __pyx_k38[] = "AuthRequestEvent";
static char __pyx_k39[] = "__CallEventCallbacks";
static char __pyx_k40[] = "Protocol/AuthRequest";
static char __pyx_k41[] = "HookEvent";
static char __pyx_k42[] = "DB/Event/Added";
static char __pyx_k43[] = "values";
static char __pyx_k44[] = "UnhookEvent";
static char __pyx_k45[] = "Unhooking Protocol events";
static char __pyx_k46[] = "__UnhookProtocolEvents";
static char __pyx_k47[] = "threading";
static char __pyx_k48[] = "clist";
static char __pyx_k49[] = "RLock";
static char __pyx_k50[] = "Class that holds an authorization event data.\n	METHODS:\n		__str__() - returns module + timestamp + hContact + reason\n	\n	DATA:\n		module    - the protocol module the event belongs to\n		timestamp - the timestamp of the event.\n		flags     - event flags (DBEF_FIRST = 1, DBEF_SENT = 2, DBEF_READ = 4)\n		eventType - the type of the event(EVENTTYPE_MESSAGE = 0, EVENTTYPE_URL = 1, EVENTTYPE_CONTACTS = 2, EVENTTYPE_ADDED = 1000, EVENTTYPE_AUTHREQUEST = 1001, EVENTTYPE_FILE = 1002, EVENTTYPE_STATUS = 25368 or custom)\n		hDBEvent  - handle to database event\n		hContact  - the handle of the contact requesting authorization\n		UIN       - contact UIN\n		nick      - contact nick\n		firstName - first name\n		lastName  - last name\n		email     - contact email\n		reason    - authorization reason\n	";
static char __pyx_k51[] = "__init__";
static char __pyx_k52[] = "__str__";
static char __pyx_k53[] = "__HookProtocolEvents";

static PyObject *__pyx_n_AuthRequestEvent;
static PyObject *__pyx_n_CallService;
static PyObject *__pyx_n_HookEvent;
static PyObject *__pyx_n_HookedProtocolEventCallbacks;
static PyObject *__pyx_n_HookedProtocolEvents;
static PyObject *__pyx_n_MirPy;
static PyObject *__pyx_n_NoSuchCallbackForEventError;
static PyObject *__pyx_n_NoSuchEventError;
static PyObject *__pyx_n_RLock;
static PyObject *__pyx_n_UIN;
static PyObject *__pyx_n_UnhookEvent;
static PyObject *__pyx_n___CallEventCallbacks;
static PyObject *__pyx_n___HookProtocolEvents;
static PyObject *__pyx_n___UnhookProtocolEvents;
static PyObject *__pyx_n___init__;
static PyObject *__pyx_n___name__;
static PyObject *__pyx_n___protocolLock;
static PyObject *__pyx_n___str__;
static PyObject *__pyx_n_acquire;
static PyObject *__pyx_n_append;
static PyObject *__pyx_n_clist;
static PyObject *__pyx_n_email;
static PyObject *__pyx_n_eventType;
static PyObject *__pyx_n_firstName;
static PyObject *__pyx_n_flags;
static PyObject *__pyx_n_hContact;
static PyObject *__pyx_n_hDBEvent;
static PyObject *__pyx_n_has_key;
static PyObject *__pyx_n_lastName;
static PyObject *__pyx_n_module;
static PyObject *__pyx_n_nick;
static PyObject *__pyx_n_reason;
static PyObject *__pyx_n_release;
static PyObject *__pyx_n_remove;
static PyObject *__pyx_n_threading;
static PyObject *__pyx_n_timestamp;
static PyObject *__pyx_n_values;

static PyObject *__pyx_k13p;
static PyObject *__pyx_k14p;
static PyObject *__pyx_k15p;
static PyObject *__pyx_k16p;
static PyObject *__pyx_k19p;
static PyObject *__pyx_k20p;
static PyObject *__pyx_k24p;
static PyObject *__pyx_k31p;
static PyObject *__pyx_k34p;
static PyObject *__pyx_k35p;
static PyObject *__pyx_k36p;
static PyObject *__pyx_k37p;
static PyObject *__pyx_k40p;
static PyObject *__pyx_k42p;
static PyObject *__pyx_k45p;
static PyObject *__pyx_k50p;

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_n_AuthRequestEvent, 1, __pyx_k38, sizeof(__pyx_k38)},
  {&__pyx_n_CallService, 1, __pyx_k18, sizeof(__pyx_k18)},
  {&__pyx_n_HookEvent, 1, __pyx_k41, sizeof(__pyx_k41)},
  {&__pyx_n_HookedProtocolEventCallbacks, 1, __pyx_k23, sizeof(__pyx_k23)},
  {&__pyx_n_HookedProtocolEvents, 1, __pyx_k27, sizeof(__pyx_k27)},
  {&__pyx_n_MirPy, 1, __pyx_k17, sizeof(__pyx_k17)},
  {&__pyx_n_NoSuchCallbackForEventError, 1, __pyx_k33, sizeof(__pyx_k33)},
  {&__pyx_n_NoSuchEventError, 1, __pyx_k30, sizeof(__pyx_k30)},
  {&__pyx_n_RLock, 1, __pyx_k49, sizeof(__pyx_k49)},
  {&__pyx_n_UIN, 1, __pyx_k7, sizeof(__pyx_k7)},
  {&__pyx_n_UnhookEvent, 1, __pyx_k44, sizeof(__pyx_k44)},
  {&__pyx_n___CallEventCallbacks, 1, __pyx_k39, sizeof(__pyx_k39)},
  {&__pyx_n___HookProtocolEvents, 1, __pyx_k53, sizeof(__pyx_k53)},
  {&__pyx_n___UnhookProtocolEvents, 1, __pyx_k46, sizeof(__pyx_k46)},
  {&__pyx_n___init__, 1, __pyx_k51, sizeof(__pyx_k51)},
  {&__pyx_n___name__, 1, __pyx_k25, sizeof(__pyx_k25)},
  {&__pyx_n___protocolLock, 1, __pyx_k21, sizeof(__pyx_k21)},
  {&__pyx_n___str__, 1, __pyx_k52, sizeof(__pyx_k52)},
  {&__pyx_n_acquire, 1, __pyx_k22, sizeof(__pyx_k22)},
  {&__pyx_n_append, 1, __pyx_k29, sizeof(__pyx_k29)},
  {&__pyx_n_clist, 1, __pyx_k48, sizeof(__pyx_k48)},
  {&__pyx_n_email, 1, __pyx_k11, sizeof(__pyx_k11)},
  {&__pyx_n_eventType, 1, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_n_firstName, 1, __pyx_k9, sizeof(__pyx_k9)},
  {&__pyx_n_flags, 1, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_n_hContact, 1, __pyx_k6, sizeof(__pyx_k6)},
  {&__pyx_n_hDBEvent, 1, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_n_has_key, 1, __pyx_k28, sizeof(__pyx_k28)},
  {&__pyx_n_lastName, 1, __pyx_k10, sizeof(__pyx_k10)},
  {&__pyx_n_module, 1, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_n_nick, 1, __pyx_k8, sizeof(__pyx_k8)},
  {&__pyx_n_reason, 1, __pyx_k12, sizeof(__pyx_k12)},
  {&__pyx_n_release, 1, __pyx_k26, sizeof(__pyx_k26)},
  {&__pyx_n_remove, 1, __pyx_k32, sizeof(__pyx_k32)},
  {&__pyx_n_threading, 1, __pyx_k47, sizeof(__pyx_k47)},
  {&__pyx_n_timestamp, 1, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_n_values, 1, __pyx_k43, sizeof(__pyx_k43)},
  {&__pyx_k13p, 0, __pyx_k13, sizeof(__pyx_k13)},
  {&__pyx_k14p, 0, __pyx_k14, sizeof(__pyx_k14)},
  {&__pyx_k15p, 0, __pyx_k15, sizeof(__pyx_k15)},
  {&__pyx_k16p, 0, __pyx_k16, sizeof(__pyx_k16)},
  {&__pyx_k19p, 0, __pyx_k19, sizeof(__pyx_k19)},
  {&__pyx_k20p, 0, __pyx_k20, sizeof(__pyx_k20)},
  {&__pyx_k24p, 0, __pyx_k24, sizeof(__pyx_k24)},
  {&__pyx_k31p, 0, __pyx_k31, sizeof(__pyx_k31)},
  {&__pyx_k34p, 0, __pyx_k34, sizeof(__pyx_k34)},
  {&__pyx_k35p, 0, __pyx_k35, sizeof(__pyx_k35)},
  {&__pyx_k36p, 0, __pyx_k36, sizeof(__pyx_k36)},
  {&__pyx_k37p, 0, __pyx_k37, sizeof(__pyx_k37)},
  {&__pyx_k40p, 0, __pyx_k40, sizeof(__pyx_k40)},
  {&__pyx_k42p, 0, __pyx_k42, sizeof(__pyx_k42)},
  {&__pyx_k45p, 0, __pyx_k45, sizeof(__pyx_k45)},
  {&__pyx_k50p, 0, __pyx_k50, sizeof(__pyx_k50)},
  {0, 0, 0, 0}
};



/* Implementation of protocols */

static PyObject *__pyx_f_9protocols_16AuthRequestEvent___init__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyMethodDef __pyx_mdef_9protocols_16AuthRequestEvent___init__ = {"__init__", (PyCFunction)__pyx_f_9protocols_16AuthRequestEvent___init__, METH_VARARGS|METH_KEYWORDS, 0};
static PyObject *__pyx_f_9protocols_16AuthRequestEvent___init__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_module = 0;
  PyObject *__pyx_v_timestamp = 0;
  PyObject *__pyx_v_flags = 0;
  PyObject *__pyx_v_eventType = 0;
  PyObject *__pyx_v_hDBEvent = 0;
  PyObject *__pyx_v_hContact = 0;
  PyObject *__pyx_v_UIN = 0;
  PyObject *__pyx_v_nick = 0;
  PyObject *__pyx_v_firstName = 0;
  PyObject *__pyx_v_lastName = 0;
  PyObject *__pyx_v_email = 0;
  PyObject *__pyx_v_reason = 0;
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {"self","module","timestamp","flags","eventType","hDBEvent","hContact","UIN","nick","firstName","lastName","email","reason",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOOOOOOOOOOOO", __pyx_argnames, &__pyx_v_self, &__pyx_v_module, &__pyx_v_timestamp, &__pyx_v_flags, &__pyx_v_eventType, &__pyx_v_hDBEvent, &__pyx_v_hContact, &__pyx_v_UIN, &__pyx_v_nick, &__pyx_v_firstName, &__pyx_v_lastName, &__pyx_v_email, &__pyx_v_reason)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_module);
  Py_INCREF(__pyx_v_timestamp);
  Py_INCREF(__pyx_v_flags);
  Py_INCREF(__pyx_v_eventType);
  Py_INCREF(__pyx_v_hDBEvent);
  Py_INCREF(__pyx_v_hContact);
  Py_INCREF(__pyx_v_UIN);
  Py_INCREF(__pyx_v_nick);
  Py_INCREF(__pyx_v_firstName);
  Py_INCREF(__pyx_v_lastName);
  Py_INCREF(__pyx_v_email);
  Py_INCREF(__pyx_v_reason);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":77 */
  if (PyObject_SetAttr(__pyx_v_self, __pyx_n_module, __pyx_v_module) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":78 */
  if (PyObject_SetAttr(__pyx_v_self, __pyx_n_timestamp, __pyx_v_timestamp) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":79 */
  if (PyObject_SetAttr(__pyx_v_self, __pyx_n_flags, __pyx_v_flags) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; goto __pyx_L1;}

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":80 */
  if (PyObject_SetAttr(__pyx_v_self, __pyx_n_eventType, __pyx_v_eventType) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":81 */
  if (PyObject_SetAttr(__pyx_v_self, __pyx_n_hDBEvent, __pyx_v_hDBEvent) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":82 */
  if (PyObject_SetAttr(__pyx_v_self, __pyx_n_hContact, __pyx_v_hContact) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":83 */
  if (PyObject_SetAttr(__pyx_v_self, __pyx_n_UIN, __pyx_v_UIN) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":84 */
  if (PyObject_SetAttr(__pyx_v_self, __pyx_n_nick, __pyx_v_nick) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":85 */
  if (PyObject_SetAttr(__pyx_v_self, __pyx_n_firstName, __pyx_v_firstName) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":86 */
  if (PyObject_SetAttr(__pyx_v_self, __pyx_n_lastName, __pyx_v_lastName) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":87 */
  if (PyObject_SetAttr(__pyx_v_self, __pyx_n_email, __pyx_v_email) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":88 */
  if (PyObject_SetAttr(__pyx_v_self, __pyx_n_reason, __pyx_v_reason) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("protocols.AuthRequestEvent.__init__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_module);
  Py_DECREF(__pyx_v_timestamp);
  Py_DECREF(__pyx_v_flags);
  Py_DECREF(__pyx_v_eventType);
  Py_DECREF(__pyx_v_hDBEvent);
  Py_DECREF(__pyx_v_hContact);
  Py_DECREF(__pyx_v_UIN);
  Py_DECREF(__pyx_v_nick);
  Py_DECREF(__pyx_v_firstName);
  Py_DECREF(__pyx_v_lastName);
  Py_DECREF(__pyx_v_email);
  Py_DECREF(__pyx_v_reason);
  return __pyx_r;
}

static PyObject *__pyx_f_9protocols_16AuthRequestEvent___str__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyMethodDef __pyx_mdef_9protocols_16AuthRequestEvent___str__ = {"__str__", (PyCFunction)__pyx_f_9protocols_16AuthRequestEvent___str__, METH_VARARGS|METH_KEYWORDS, 0};
static PyObject *__pyx_f_9protocols_16AuthRequestEvent___str__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_buf;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"self",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_self)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_buf = Py_None; Py_INCREF(Py_None);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":91 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_module); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_1);
  __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(((PyObject *)(&PyString_Type)), __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyNumber_Add(__pyx_k13p, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyNumber_Add(__pyx_2, __pyx_k14p); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyObject_GetAttr(__pyx_v_self, __pyx_n_timestamp); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_2 = PyObject_CallObject(((PyObject *)(&PyString_Type)), __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_3 = PyNumber_Add(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_1 = PyNumber_Add(__pyx_3, __pyx_k15p); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_2 = PyObject_GetAttr(__pyx_v_self, __pyx_n_hContact); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_2 = PyObject_CallObject(((PyObject *)(&PyString_Type)), __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_3 = PyNumber_Add(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_1 = PyNumber_Add(__pyx_3, __pyx_k16p); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_2 = PyObject_GetAttr(__pyx_v_self, __pyx_n_reason); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_2 = PyObject_CallObject(((PyObject *)(&PyString_Type)), __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_3 = PyNumber_Add(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_v_buf);
  __pyx_v_buf = __pyx_3;
  __pyx_3 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":92 */
  Py_INCREF(__pyx_v_buf);
  __pyx_r = __pyx_v_buf;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("protocols.AuthRequestEvent.__str__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_buf);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_9protocols_AuthorizeAllow(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_9protocols_AuthorizeAllow[] = "Accepts an authorisation request.\n		protocol - the protocol the contact is on\n		hDBEvent - handle to the DB event that contains the autorisation request.\n		This will not remove the event from the clist events. To remove the event you need to call clist.EventRemove(hContact, hDBEvent).\n	";
static PyObject *__pyx_f_9protocols_AuthorizeAllow(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_protocol = 0;
  PyObject *__pyx_v_hDBEvent = 0;
  PyObject *__pyx_v_res;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"protocol","hDBEvent",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_protocol, &__pyx_v_hDBEvent)) return 0;
  Py_INCREF(__pyx_v_protocol);
  Py_INCREF(__pyx_v_hDBEvent);
  __pyx_v_res = Py_None; Py_INCREF(Py_None);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":102 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_CallService); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyNumber_Add(__pyx_v_protocol, __pyx_k19p); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_1);
  Py_INCREF(__pyx_v_hDBEvent);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_v_hDBEvent);
  PyTuple_SET_ITEM(__pyx_4, 2, __pyx_3);
  __pyx_1 = 0;
  __pyx_3 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_v_res);
  __pyx_v_res = __pyx_1;
  __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":104 */
  Py_INCREF(__pyx_v_res);
  __pyx_r = __pyx_v_res;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("protocols.AuthorizeAllow");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_res);
  Py_DECREF(__pyx_v_protocol);
  Py_DECREF(__pyx_v_hDBEvent);
  return __pyx_r;
}

static PyObject *__pyx_f_9protocols_AuthorizeDeny(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_9protocols_AuthorizeDeny[] = "Denies an authorisation request.\n		protocol - the protocol the contact is on.\n		hDBEvent - handle to the DB event that contains the authorisation request.\n		reason - reason for denial\n		This will not remove the event from the clist events. To remove the event you need to call clist.EventRemove(hContact, hDBEvent).\n	";
static PyObject *__pyx_f_9protocols_AuthorizeDeny(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_protocol = 0;
  PyObject *__pyx_v_hDBEvent = 0;
  PyObject *__pyx_v_reason = 0;
  PyObject *__pyx_v_res;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"protocol","hDBEvent","reason",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_protocol, &__pyx_v_hDBEvent, &__pyx_v_reason)) return 0;
  Py_INCREF(__pyx_v_protocol);
  Py_INCREF(__pyx_v_hDBEvent);
  Py_INCREF(__pyx_v_reason);
  __pyx_v_res = Py_None; Py_INCREF(Py_None);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":113 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_CallService); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyNumber_Add(__pyx_v_protocol, __pyx_k20p); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(3); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_1);
  Py_INCREF(__pyx_v_hDBEvent);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_v_hDBEvent);
  Py_INCREF(__pyx_v_reason);
  PyTuple_SET_ITEM(__pyx_3, 2, __pyx_v_reason);
  __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_v_res);
  __pyx_v_res = __pyx_1;
  __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":115 */
  Py_INCREF(__pyx_v_res);
  __pyx_r = __pyx_v_res;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("protocols.AuthorizeDeny");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_res);
  Py_DECREF(__pyx_v_protocol);
  Py_DECREF(__pyx_v_hDBEvent);
  Py_DECREF(__pyx_v_reason);
  return __pyx_r;
}

static PyObject *__pyx_f_9protocols___CallEventCallbacks(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9protocols___CallEventCallbacks(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_event = 0;
  PyObject *__pyx_v_wParam = 0;
  PyObject *__pyx_v_lParam = 0;
  PyObject *__pyx_v_res;
  PyObject *__pyx_v_list;
  PyObject *__pyx_v_callback;
  PyObject *__pyx_v_e;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  static char *__pyx_argnames[] = {"event","wParam","lParam",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_event, &__pyx_v_wParam, &__pyx_v_lParam)) return 0;
  Py_INCREF(__pyx_v_event);
  Py_INCREF(__pyx_v_wParam);
  Py_INCREF(__pyx_v_lParam);
  __pyx_v_res = Py_None; Py_INCREF(Py_None);
  __pyx_v_list = Py_None; Py_INCREF(Py_None);
  __pyx_v_callback = Py_None; Py_INCREF(Py_None);
  __pyx_v_e = Py_None; Py_INCREF(Py_None);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":122 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 122; goto __pyx_L1;}
  Py_DECREF(__pyx_v_res);
  __pyx_v_res = __pyx_1;
  __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":123 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n___protocolLock); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_acquire); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":124 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_HookedProtocolEventCallbacks); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
  __pyx_1 = PyObject_GetItem(__pyx_2, __pyx_v_event); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_v_list);
  __pyx_v_list = __pyx_1;
  __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":125 */
  __pyx_2 = PyObject_GetIter(__pyx_v_list); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
  for (;;) {
    __pyx_1 = PyIter_Next(__pyx_2);
    if (!__pyx_1) {
      if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
      break;
    }
    Py_DECREF(__pyx_v_callback);
    __pyx_v_callback = __pyx_1;
    __pyx_1 = 0;

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":126 */
    /*try:*/ {
      __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L4;}
      Py_INCREF(__pyx_v_wParam);
      PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_wParam);
      Py_INCREF(__pyx_v_lParam);
      PyTuple_SET_ITEM(__pyx_1, 1, __pyx_v_lParam);
      __pyx_3 = PyObject_CallObject(__pyx_v_callback, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L4;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      Py_DECREF(__pyx_v_res);
      __pyx_v_res = __pyx_3;
      __pyx_3 = 0;
    }
    goto __pyx_L5;
    __pyx_L4:;
    Py_XDECREF(__pyx_1); __pyx_1 = 0;
    Py_XDECREF(__pyx_3); __pyx_3 = 0;

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":128 */
    __pyx_4 = PyErr_ExceptionMatches(PyExc_Exception);
    if (__pyx_4) {
      __Pyx_AddTraceback("protocols.__CallEventCallbacks");
      if (__Pyx_GetException(&__pyx_1, &__pyx_3, &__pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 128; goto __pyx_L1;}
      Py_INCREF(__pyx_3);
      Py_DECREF(__pyx_v_e);
      __pyx_v_e = __pyx_3;

      /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":129 */
      __pyx_6 = PyObject_GetAttr(__pyx_v_callback, __pyx_n___name__); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
      __pyx_7 = PyTuple_New(2); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_7, 0, __pyx_6);
      Py_INCREF(__pyx_v_e);
      PyTuple_SET_ITEM(__pyx_7, 1, __pyx_v_e);
      __pyx_6 = 0;
      __pyx_6 = PyNumber_Remainder(__pyx_k24p, __pyx_7); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
      Py_DECREF(__pyx_7); __pyx_7 = 0;
      if (__Pyx_PrintItem(__pyx_6) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
      Py_DECREF(__pyx_6); __pyx_6 = 0;
      if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}

      /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":130 */
      __pyx_7 = PyInt_FromLong(0); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 130; goto __pyx_L1;}
      Py_DECREF(__pyx_v_res);
      __pyx_v_res = __pyx_7;
      __pyx_7 = 0;
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      goto __pyx_L5;
    }
    goto __pyx_L1;
    __pyx_L5:;

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":131 */
    if (PyObject_Cmp(__pyx_v_res, Py_None, &__pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
    __pyx_4 = __pyx_4 != 0;
    if (__pyx_4) {
      __pyx_6 = PyInt_FromLong(0); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
      if (PyObject_Cmp(__pyx_v_res, __pyx_6, &__pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
      __pyx_4 = __pyx_4 != 0;
      Py_DECREF(__pyx_6); __pyx_6 = 0;
    }
    if (__pyx_4) {
      goto __pyx_L3;
      goto __pyx_L6;
    }
    __pyx_L6:;
  }
  __pyx_L3:;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":134 */
  if (PyObject_Cmp(__pyx_v_res, Py_None, &__pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
  __pyx_4 = __pyx_4 == 0;
  if (__pyx_4) {
    __pyx_7 = PyInt_FromLong(0); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}
    Py_DECREF(__pyx_v_res);
    __pyx_v_res = __pyx_7;
    __pyx_7 = 0;
    goto __pyx_L7;
  }
  __pyx_L7:;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":136 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n___protocolLock); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 136; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_1, __pyx_n_release); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 136; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_5 = PyObject_CallObject(__pyx_3, 0); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 136; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":138 */
  Py_INCREF(__pyx_v_res);
  __pyx_r = __pyx_v_res;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  __Pyx_AddTraceback("protocols.__CallEventCallbacks");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_res);
  Py_DECREF(__pyx_v_list);
  Py_DECREF(__pyx_v_callback);
  Py_DECREF(__pyx_v_e);
  Py_DECREF(__pyx_v_event);
  Py_DECREF(__pyx_v_wParam);
  Py_DECREF(__pyx_v_lParam);
  return __pyx_r;
}

static PyObject *__pyx_f_9protocols_HookProtocolEvent(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_9protocols_HookProtocolEvent[] = "Hooks a protocol event.\n	HookProtocolEvent(event, callback):\n		event - the event string. To find out all available events type \"print protocol.HookedProtocolEvents.keys()\" (do not modify this dictionary !!!)\n		callback - python function that gets called when the event occurs. The declaration is OnEvent(wParam, lParam); the actual parameters depend on the event.\n	";
static PyObject *__pyx_f_9protocols_HookProtocolEvent(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_event = 0;
  PyObject *__pyx_v_callback = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  static char *__pyx_argnames[] = {"event","callback",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_event, &__pyx_v_callback)) return 0;
  Py_INCREF(__pyx_v_event);
  Py_INCREF(__pyx_v_callback);
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_HookedProtocolEvents); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 146; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_has_key); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 146; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 146; goto __pyx_L1;}
  Py_INCREF(__pyx_v_event);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_event);
  __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 146; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_4 = PyObject_IsTrue(__pyx_3); if (__pyx_4 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 146; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (__pyx_4) {
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_HookedProtocolEventCallbacks); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
    __pyx_1 = PyObject_GetItem(__pyx_2, __pyx_v_event); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_3 = PyObject_GetAttr(__pyx_1, __pyx_n_append); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
    Py_INCREF(__pyx_v_callback);
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_callback);
    __pyx_1 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    goto __pyx_L2;
  }
  /*else*/ {
    __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; goto __pyx_L1;}
    __pyx_2 = PyObject_GetAttr(__pyx_3, __pyx_n_NoSuchEventError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_1 = PyNumber_Remainder(__pyx_k31p, __pyx_v_event); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_1);
    __pyx_1 = 0;
    __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_1, 0, 0);
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; goto __pyx_L1;}
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("protocols.HookProtocolEvent");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_event);
  Py_DECREF(__pyx_v_callback);
  return __pyx_r;
}

static PyObject *__pyx_f_9protocols_UnhookProtocolEvent(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_9protocols_UnhookProtocolEvent[] = "Unhooks a previously hooked protocol event.\n	UnhookProtocolEvent(event, callback)\n		event - the event to unhook. Must have been previously hooked with a call to HookProtocolEvent.\n		callback - the event callback.\n	Both parameters are required because the same callback could be used to hook multiple events.\n	";
static PyObject *__pyx_f_9protocols_UnhookProtocolEvent(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_event = 0;
  PyObject *__pyx_v_callback = 0;
  PyObject *__pyx_v_ex;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  static char *__pyx_argnames[] = {"event","callback",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_event, &__pyx_v_callback)) return 0;
  Py_INCREF(__pyx_v_event);
  Py_INCREF(__pyx_v_callback);
  __pyx_v_ex = Py_None; Py_INCREF(Py_None);
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_HookedProtocolEvents); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 158; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_has_key); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 158; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 158; goto __pyx_L1;}
  Py_INCREF(__pyx_v_event);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_event);
  __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 158; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_4 = PyObject_IsTrue(__pyx_3); if (__pyx_4 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 158; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (__pyx_4) {
    /*try:*/ {
      __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_HookedProtocolEventCallbacks); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 160; goto __pyx_L3;}
      __pyx_1 = PyObject_GetItem(__pyx_2, __pyx_v_event); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 160; goto __pyx_L3;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      __pyx_3 = PyObject_GetAttr(__pyx_1, __pyx_n_remove); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 160; goto __pyx_L3;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 160; goto __pyx_L3;}
      Py_INCREF(__pyx_v_callback);
      PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_callback);
      __pyx_1 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 160; goto __pyx_L3;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_1); __pyx_1 = 0;
    }
    goto __pyx_L4;
    __pyx_L3:;
    Py_XDECREF(__pyx_3); __pyx_3 = 0;
    Py_XDECREF(__pyx_2); __pyx_2 = 0;
    Py_XDECREF(__pyx_1); __pyx_1 = 0;

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":161 */
    __pyx_4 = PyErr_ExceptionMatches(PyExc_Exception);
    if (__pyx_4) {
      __Pyx_AddTraceback("protocols.UnhookProtocolEvent");
      if (__Pyx_GetException(&__pyx_3, &__pyx_2, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
      Py_INCREF(__pyx_2);
      Py_DECREF(__pyx_v_ex);
      __pyx_v_ex = __pyx_2;
      __pyx_5 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; goto __pyx_L1;}
      __pyx_6 = PyObject_GetAttr(__pyx_5, __pyx_n_NoSuchCallbackForEventError); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      __pyx_5 = PyTuple_New(2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; goto __pyx_L1;}
      Py_INCREF(__pyx_v_event);
      PyTuple_SET_ITEM(__pyx_5, 0, __pyx_v_event);
      Py_INCREF(__pyx_v_callback);
      PyTuple_SET_ITEM(__pyx_5, 1, __pyx_v_callback);
      __pyx_7 = PyNumber_Remainder(__pyx_k34p, __pyx_5); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      __pyx_5 = PyTuple_New(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_5, 0, __pyx_7);
      __pyx_7 = 0;
      __pyx_7 = PyObject_CallObject(__pyx_6, __pyx_5); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; goto __pyx_L1;}
      Py_DECREF(__pyx_6); __pyx_6 = 0;
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      __Pyx_Raise(__pyx_7, 0, 0);
      Py_DECREF(__pyx_7); __pyx_7 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      goto __pyx_L4;
    }
    goto __pyx_L1;
    __pyx_L4:;
    goto __pyx_L2;
  }
  /*else*/ {
    __pyx_6 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
    __pyx_5 = PyObject_GetAttr(__pyx_6, __pyx_n_NoSuchEventError); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __pyx_7 = PyNumber_Remainder(__pyx_k35p, __pyx_v_event); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_7);
    __pyx_7 = 0;
    __pyx_2 = PyObject_CallObject(__pyx_5, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_2, 0, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  __Pyx_AddTraceback("protocols.UnhookProtocolEvent");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_ex);
  Py_DECREF(__pyx_v_event);
  Py_DECREF(__pyx_v_callback);
  return __pyx_r;
}

static int __pyx_f_9protocols_OnAuthorisationRequest(long __pyx_v_wParam,long __pyx_v_hDBEvent) {
  void *__pyx_v_buffer;
  int __pyx_v_offset;
  DBEVENTINFO __pyx_v_dbEvent;
  PyObject *__pyx_v_size;
  PyObject *__pyx_v_UIN;
  PyObject *__pyx_v_hContact;
  PyObject *__pyx_v_nick;
  PyObject *__pyx_v_firstName;
  PyObject *__pyx_v_lastName;
  PyObject *__pyx_v_email;
  PyObject *__pyx_v_reason;
  PyObject *__pyx_v_authEvent;
  int __pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  Py_ssize_t __pyx_6;
  PyObject *__pyx_7 = 0;
  PyObject *__pyx_8 = 0;
  PyObject *__pyx_9 = 0;
  __pyx_v_size = Py_None; Py_INCREF(Py_None);
  __pyx_v_UIN = Py_None; Py_INCREF(Py_None);
  __pyx_v_hContact = Py_None; Py_INCREF(Py_None);
  __pyx_v_nick = Py_None; Py_INCREF(Py_None);
  __pyx_v_firstName = Py_None; Py_INCREF(Py_None);
  __pyx_v_lastName = Py_None; Py_INCREF(Py_None);
  __pyx_v_email = Py_None; Py_INCREF(Py_None);
  __pyx_v_reason = Py_None; Py_INCREF(Py_None);
  __pyx_v_authEvent = Py_None; Py_INCREF(Py_None);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":167 */
  __pyx_1 = (__pyx_v_hDBEvent == 0);
  if (__pyx_1) {
    __pyx_r = 0;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":174 */
  __pyx_v_dbEvent.cbSize = (sizeof(DBEVENTINFO));

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":175 */
  __pyx_v_dbEvent.cbBlob = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":176 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 176; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_n_CallService); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 176; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyInt_FromLong(__pyx_v_hDBEvent); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 176; goto __pyx_L1;}
  __pyx_4 = PyInt_FromLong(((long)(&__pyx_v_dbEvent))); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 176; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 176; goto __pyx_L1;}
  Py_INCREF(__pyx_k36p);
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_k36p);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_2);
  PyTuple_SET_ITEM(__pyx_5, 2, __pyx_4);
  __pyx_2 = 0;
  __pyx_4 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_3, __pyx_5); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 176; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":177 */
  __pyx_1 = (!(__pyx_v_dbEvent.flags & __pyx_e_9protocols_DBEF_READ));
  if (__pyx_1) {
    __pyx_1 = (!(__pyx_v_dbEvent.flags & __pyx_e_9protocols_DBEF_SENT));
    if (__pyx_1) {
      __pyx_1 = (__pyx_v_dbEvent.eventType == __pyx_e_9protocols_EVENTTYPE_AUTHREQUEST);
    }
  }
  if (__pyx_1) {

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":178 */
    __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 178; goto __pyx_L1;}
    __pyx_3 = PyObject_GetAttr(__pyx_4, __pyx_n_CallService); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 178; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_5 = PyInt_FromLong(__pyx_v_hDBEvent); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 178; goto __pyx_L1;}
    __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 178; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 178; goto __pyx_L1;}
    Py_INCREF(__pyx_k37p);
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_k37p);
    PyTuple_SET_ITEM(__pyx_4, 1, __pyx_5);
    PyTuple_SET_ITEM(__pyx_4, 2, __pyx_2);
    __pyx_5 = 0;
    __pyx_2 = 0;
    __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 178; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_v_size);
    __pyx_v_size = __pyx_5;
    __pyx_5 = 0;

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":179 */
    __pyx_2 = PyInt_FromLong(4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 179; goto __pyx_L1;}
    __pyx_3 = PyNumber_Add(__pyx_v_size, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 179; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_v_size);
    __pyx_v_size = __pyx_3;
    __pyx_3 = 0;

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":181 */
    __pyx_1 = PyInt_AsLong(__pyx_v_size); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 181; goto __pyx_L1;}
    __pyx_v_buffer = malloc(__pyx_1);

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":182 */
    __pyx_v_dbEvent.pBlob = ((__pyx_t_9protocols_PBYTE)__pyx_v_buffer);

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":183 */
    __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 183; goto __pyx_L1;}
    __pyx_5 = PyObject_GetAttr(__pyx_4, __pyx_n_CallService); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 183; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_2 = PyInt_FromLong(__pyx_v_hDBEvent); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 183; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong(((long)(&__pyx_v_dbEvent))); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 183; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 183; goto __pyx_L1;}
    Py_INCREF(__pyx_k36p);
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_k36p);
    PyTuple_SET_ITEM(__pyx_4, 1, __pyx_2);
    PyTuple_SET_ITEM(__pyx_4, 2, __pyx_3);
    __pyx_2 = 0;
    __pyx_3 = 0;
    __pyx_2 = PyObject_CallObject(__pyx_5, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 183; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":185 */
    __pyx_3 = PyInt_FromLong((((long *)__pyx_v_dbEvent.pBlob)[0])); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 185; goto __pyx_L1;}
    Py_DECREF(__pyx_v_UIN);
    __pyx_v_UIN = __pyx_3;
    __pyx_3 = 0;

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":186 */
    __pyx_v_offset = (sizeof(long));

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":187 */
    __pyx_5 = PyInt_FromLong((((long *)__pyx_v_dbEvent.pBlob)[1])); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 187; goto __pyx_L1;}
    Py_DECREF(__pyx_v_hContact);
    __pyx_v_hContact = __pyx_5;
    __pyx_5 = 0;

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":188 */
    __pyx_v_offset = (__pyx_v_offset + (sizeof(long)));

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":189 */
    __pyx_4 = PyString_FromString(((char *)(__pyx_v_dbEvent.pBlob + __pyx_v_offset))); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 189; goto __pyx_L1;}
    Py_DECREF(__pyx_v_nick);
    __pyx_v_nick = __pyx_4;
    __pyx_4 = 0;

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":190 */
    __pyx_6 = PyObject_Length(__pyx_v_nick); if (__pyx_6 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 190; goto __pyx_L1;}
    __pyx_v_offset = ((__pyx_v_offset + __pyx_6) + 1);

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":191 */
    __pyx_2 = PyString_FromString(((char *)(__pyx_v_dbEvent.pBlob + __pyx_v_offset))); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 191; goto __pyx_L1;}
    Py_DECREF(__pyx_v_firstName);
    __pyx_v_firstName = __pyx_2;
    __pyx_2 = 0;

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":192 */
    __pyx_6 = PyObject_Length(__pyx_v_firstName); if (__pyx_6 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 192; goto __pyx_L1;}
    __pyx_v_offset = ((__pyx_v_offset + __pyx_6) + 1);

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":193 */
    __pyx_3 = PyString_FromString(((char *)(__pyx_v_dbEvent.pBlob + __pyx_v_offset))); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 193; goto __pyx_L1;}
    Py_DECREF(__pyx_v_lastName);
    __pyx_v_lastName = __pyx_3;
    __pyx_3 = 0;

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":194 */
    __pyx_6 = PyObject_Length(__pyx_v_lastName); if (__pyx_6 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 194; goto __pyx_L1;}
    __pyx_v_offset = ((__pyx_v_offset + __pyx_6) + 1);

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":195 */
    __pyx_5 = PyString_FromString(((char *)(__pyx_v_dbEvent.pBlob + __pyx_v_offset))); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 195; goto __pyx_L1;}
    Py_DECREF(__pyx_v_email);
    __pyx_v_email = __pyx_5;
    __pyx_5 = 0;

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":196 */
    __pyx_6 = PyObject_Length(__pyx_v_email); if (__pyx_6 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 196; goto __pyx_L1;}
    __pyx_v_offset = ((__pyx_v_offset + __pyx_6) + 1);

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":197 */
    __pyx_4 = PyString_FromString(((char *)(__pyx_v_dbEvent.pBlob + __pyx_v_offset))); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 197; goto __pyx_L1;}
    Py_DECREF(__pyx_v_reason);
    __pyx_v_reason = __pyx_4;
    __pyx_4 = 0;

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":198 */
    free(__pyx_v_buffer);

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":201 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_AuthRequestEvent); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 201; goto __pyx_L1;}
    __pyx_3 = PyString_FromString(__pyx_v_dbEvent.szModule); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 201; goto __pyx_L1;}
    __pyx_5 = PyLong_FromUnsignedLong(__pyx_v_dbEvent.timestamp); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 201; goto __pyx_L1;}
    __pyx_4 = PyLong_FromUnsignedLong(__pyx_v_dbEvent.flags); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 201; goto __pyx_L1;}
    __pyx_7 = PyInt_FromLong(__pyx_v_dbEvent.eventType); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 201; goto __pyx_L1;}
    __pyx_8 = PyInt_FromLong(__pyx_v_hDBEvent); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 201; goto __pyx_L1;}
    __pyx_9 = PyTuple_New(12); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 201; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_9, 0, __pyx_3);
    PyTuple_SET_ITEM(__pyx_9, 1, __pyx_5);
    PyTuple_SET_ITEM(__pyx_9, 2, __pyx_4);
    PyTuple_SET_ITEM(__pyx_9, 3, __pyx_7);
    PyTuple_SET_ITEM(__pyx_9, 4, __pyx_8);
    Py_INCREF(__pyx_v_hContact);
    PyTuple_SET_ITEM(__pyx_9, 5, __pyx_v_hContact);
    Py_INCREF(__pyx_v_UIN);
    PyTuple_SET_ITEM(__pyx_9, 6, __pyx_v_UIN);
    Py_INCREF(__pyx_v_nick);
    PyTuple_SET_ITEM(__pyx_9, 7, __pyx_v_nick);
    Py_INCREF(__pyx_v_firstName);
    PyTuple_SET_ITEM(__pyx_9, 8, __pyx_v_firstName);
    Py_INCREF(__pyx_v_lastName);
    PyTuple_SET_ITEM(__pyx_9, 9, __pyx_v_lastName);
    Py_INCREF(__pyx_v_email);
    PyTuple_SET_ITEM(__pyx_9, 10, __pyx_v_email);
    Py_INCREF(__pyx_v_reason);
    PyTuple_SET_ITEM(__pyx_9, 11, __pyx_v_reason);
    __pyx_3 = 0;
    __pyx_5 = 0;
    __pyx_4 = 0;
    __pyx_7 = 0;
    __pyx_8 = 0;
    __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_9); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 201; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_9); __pyx_9 = 0;
    Py_DECREF(__pyx_v_authEvent);
    __pyx_v_authEvent = __pyx_3;
    __pyx_3 = 0;

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":202 */
    __pyx_5 = __Pyx_GetName(__pyx_m, __pyx_n___CallEventCallbacks); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
    __pyx_4 = PyInt_FromLong(__pyx_v_hDBEvent); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
    __pyx_7 = PyTuple_New(3); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
    Py_INCREF(__pyx_k40p);
    PyTuple_SET_ITEM(__pyx_7, 0, __pyx_k40p);
    PyTuple_SET_ITEM(__pyx_7, 1, __pyx_4);
    Py_INCREF(__pyx_v_authEvent);
    PyTuple_SET_ITEM(__pyx_7, 2, __pyx_v_authEvent);
    __pyx_4 = 0;
    __pyx_8 = PyObject_CallObject(__pyx_5, __pyx_7); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    __pyx_1 = PyInt_AsLong(__pyx_8); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
    Py_DECREF(__pyx_8); __pyx_8 = 0;
    __pyx_r = __pyx_1;
    goto __pyx_L0;
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":204 */
  __pyx_r = 0;
  goto __pyx_L0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_7);
  Py_XDECREF(__pyx_8);
  Py_XDECREF(__pyx_9);
  __Pyx_WriteUnraisable("protocols.OnAuthorisationRequest");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_size);
  Py_DECREF(__pyx_v_UIN);
  Py_DECREF(__pyx_v_hContact);
  Py_DECREF(__pyx_v_nick);
  Py_DECREF(__pyx_v_firstName);
  Py_DECREF(__pyx_v_lastName);
  Py_DECREF(__pyx_v_email);
  Py_DECREF(__pyx_v_reason);
  Py_DECREF(__pyx_v_authEvent);
  return __pyx_r;
}

static void __pyx_f_9protocols___protocolAddEventHook(PyObject *__pyx_v_mirandaEvent,PyObject *__pyx_v_mirpyEvent,__pyx_t_9protocols_MIRANDAHOOK __pyx_v_function) {
  PyObject *__pyx_v_handle;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  Py_INCREF(__pyx_v_mirandaEvent);
  Py_INCREF(__pyx_v_mirpyEvent);
  __pyx_v_handle = Py_None; Py_INCREF(Py_None);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":209 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 209; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_HookEvent); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 209; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyInt_FromLong(((long)__pyx_v_function)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 209; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 209; goto __pyx_L1;}
  Py_INCREF(__pyx_v_mirandaEvent);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_mirandaEvent);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_1);
  __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 209; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_v_handle);
  __pyx_v_handle = __pyx_1;
  __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":210 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_HookedProtocolEvents); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 210; goto __pyx_L1;}
  if (PyObject_SetItem(__pyx_2, __pyx_v_mirpyEvent, __pyx_v_handle) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 210; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":211 */
  __pyx_3 = PyList_New(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L1;}
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_HookedProtocolEventCallbacks); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L1;}
  if (PyObject_SetItem(__pyx_1, __pyx_v_mirpyEvent, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_WriteUnraisable("protocols.__protocolAddEventHook");
  __pyx_L0:;
  Py_DECREF(__pyx_v_handle);
  Py_DECREF(__pyx_v_mirandaEvent);
  Py_DECREF(__pyx_v_mirpyEvent);
}

static PyObject *__pyx_f_9protocols___HookProtocolEvents(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9protocols___HookProtocolEvents(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  __pyx_f_9protocols___protocolAddEventHook(__pyx_k42p,__pyx_k40p,__pyx_f_9protocols_OnAuthorisationRequest);

  __pyx_r = Py_None; Py_INCREF(Py_None);
  return __pyx_r;
}

static PyObject *__pyx_f_9protocols___UnhookProtocolEvents(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9protocols___UnhookProtocolEvents(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_handle;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  __pyx_v_handle = Py_None; Py_INCREF(Py_None);
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_HookedProtocolEvents); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 217; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_values); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 217; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 217; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyObject_GetIter(__pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 217; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  for (;;) {
    __pyx_1 = PyIter_Next(__pyx_2);
    if (!__pyx_1) {
      if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 217; goto __pyx_L1;}
      break;
    }
    Py_DECREF(__pyx_v_handle);
    __pyx_v_handle = __pyx_1;
    __pyx_1 = 0;
    __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 218; goto __pyx_L1;}
    __pyx_3 = PyObject_GetAttr(__pyx_1, __pyx_n_UnhookEvent); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 218; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 218; goto __pyx_L1;}
    Py_INCREF(__pyx_v_handle);
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_handle);
    __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 218; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
  }
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("protocols.__UnhookProtocolEvents");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_handle);
  return __pyx_r;
}

static PyObject *__pyx_f_9protocols_OnMirPyClose(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9protocols_OnMirPyClose(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":225 */
  if (__Pyx_PrintItem(__pyx_k45p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 225; goto __pyx_L1;}
  if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 225; goto __pyx_L1;}

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":226 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n___UnhookProtocolEvents); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 226; goto __pyx_L1;}
  __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 226; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("protocols.OnMirPyClose");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static struct PyMethodDef __pyx_methods[] = {
  {"AuthorizeAllow", (PyCFunction)__pyx_f_9protocols_AuthorizeAllow, METH_VARARGS|METH_KEYWORDS, __pyx_doc_9protocols_AuthorizeAllow},
  {"AuthorizeDeny", (PyCFunction)__pyx_f_9protocols_AuthorizeDeny, METH_VARARGS|METH_KEYWORDS, __pyx_doc_9protocols_AuthorizeDeny},
  {"__CallEventCallbacks", (PyCFunction)__pyx_f_9protocols___CallEventCallbacks, METH_VARARGS|METH_KEYWORDS, 0},
  {"HookProtocolEvent", (PyCFunction)__pyx_f_9protocols_HookProtocolEvent, METH_VARARGS|METH_KEYWORDS, __pyx_doc_9protocols_HookProtocolEvent},
  {"UnhookProtocolEvent", (PyCFunction)__pyx_f_9protocols_UnhookProtocolEvent, METH_VARARGS|METH_KEYWORDS, __pyx_doc_9protocols_UnhookProtocolEvent},
  {"__HookProtocolEvents", (PyCFunction)__pyx_f_9protocols___HookProtocolEvents, METH_VARARGS|METH_KEYWORDS, 0},
  {"__UnhookProtocolEvents", (PyCFunction)__pyx_f_9protocols___UnhookProtocolEvents, METH_VARARGS|METH_KEYWORDS, 0},
  {"OnMirPyClose", (PyCFunction)__pyx_f_9protocols_OnMirPyClose, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initprotocols(void); /*proto*/
PyMODINIT_FUNC initprotocols(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("protocols", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":8 */
  __pyx_1 = __Pyx_Import(__pyx_n_threading, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_threading, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":10 */
  __pyx_1 = __Pyx_Import(__pyx_n_MirPy, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_MirPy, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":11 */
  __pyx_1 = __Pyx_Import(__pyx_n_clist, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_clist, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":13 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_threading); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_RLock); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n___protocolLock, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":56 */
  __pyx_2 = PyDict_New(); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
  __pyx_1 = PyTuple_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
  if (PyDict_SetItemString(__pyx_2, "__doc__", __pyx_k50p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
  __pyx_3 = __Pyx_CreateClass(__pyx_1, __pyx_2, __pyx_n_AuthRequestEvent, "protocols"); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":76 */
  __pyx_1 = PyCFunction_New(&__pyx_mdef_9protocols_16AuthRequestEvent___init__, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_1, 0, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n___init__, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":90 */
  __pyx_1 = PyCFunction_New(&__pyx_mdef_9protocols_16AuthRequestEvent___str__, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_1, 0, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n___str__, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n_AuthRequestEvent, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":118 */
  __pyx_1 = PyDict_New(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_HookedProtocolEvents, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":119 */
  __pyx_4 = PyDict_New(); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_HookedProtocolEventCallbacks, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":221 */
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n___HookProtocolEvents); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 221; goto __pyx_L1;}
  __pyx_2 = PyObject_CallObject(__pyx_3, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 221; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\protocols\pyrex\protocols.pyx":224 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("protocols");
}

static char *__pyx_filenames[] = {
  "protocols.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static int __Pyx_GetException(PyObject **type, PyObject **value, PyObject **tb) {
    PyThreadState *tstate = PyThreadState_Get();
    PyErr_Fetch(type, value, tb);
    PyErr_NormalizeException(type, value, tb);
    if (PyErr_Occurred())
        goto bad;
    Py_INCREF(*type);
    Py_INCREF(*value);
    Py_INCREF(*tb);
    Py_XDECREF(tstate->exc_type);
    Py_XDECREF(tstate->exc_value);
    Py_XDECREF(tstate->exc_traceback);
    tstate->exc_type = *type;
    tstate->exc_value = *value;
    tstate->exc_traceback = *tb;
    return 0;
bad:
    Py_XDECREF(*type);
    Py_XDECREF(*value);
    Py_XDECREF(*tb);
    return -1;
}

static PyObject *__Pyx_GetStdout(void) {
    PyObject *f = PySys_GetObject("stdout");
    if (!f) {
        PyErr_SetString(PyExc_RuntimeError, "lost sys.stdout");
    }
    return f;
}

static int __Pyx_PrintItem(PyObject *v) {
    PyObject *f;
    
    if (!(f = __Pyx_GetStdout()))
        return -1;
    if (PyFile_SoftSpace(f, 1)) {
        if (PyFile_WriteString(" ", f) < 0)
            return -1;
    }
    if (PyFile_WriteObject(v, f, Py_PRINT_RAW) < 0)
        return -1;
    if (PyString_Check(v)) {
        char *s = PyString_AsString(v);
        Py_ssize_t len = PyString_Size(v);
        if (len > 0 &&
            isspace(Py_CHARMASK(s[len-1])) &&
            s[len-1] != ' ')
                PyFile_SoftSpace(f, 0);
    }
    return 0;
}

static int __Pyx_PrintNewline(void) {
    PyObject *f;
    
    if (!(f = __Pyx_GetStdout()))
        return -1;
    if (PyFile_WriteString("\n", f) < 0)
        return -1;
    PyFile_SoftSpace(f, 0);
    return 0;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    #if PY_VERSION_HEX < 0x02050000
    if (!PyClass_Check(type))
    #else
    if (!PyType_Check(type))
    #endif
    {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        #if PY_VERSION_HEX < 0x02050000
            if (PyInstance_Check(type)) {
                type = (PyObject*) ((PyInstanceObject*)type)->in_class;
                Py_INCREF(type);
            }
            else {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception must be an old-style class or instance");
                goto raise_error;
            }
        #else
            type = (PyObject*) type->ob_type;
            Py_INCREF(type);
            if (!PyType_IsSubtype((PyTypeObject *)type, (PyTypeObject *)PyExc_BaseException)) {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception class must be a subclass of BaseException");
                goto raise_error;
            }
        #endif
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static void __Pyx_WriteUnraisable(char *name) {
    PyObject *old_exc, *old_val, *old_tb;
    PyObject *ctx;
    PyErr_Fetch(&old_exc, &old_val, &old_tb);
    ctx = PyString_FromString(name);
    PyErr_Restore(old_exc, old_val, old_tb);
    if (!ctx)
        ctx = Py_None;
    PyErr_WriteUnraisable(ctx);
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        if (t->i)
            PyString_InternInPlace(t->p);
        ++t;
    }
    return 0;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_CreateClass(
    PyObject *bases, PyObject *dict, PyObject *name, char *modname)
{
    PyObject *py_modname;
    PyObject *result = 0;
    
    py_modname = PyString_FromString(modname);
    if (!py_modname)
        goto bad;
    if (PyDict_SetItemString(dict, "__module__", py_modname) < 0)
        goto bad;
    result = PyClass_New(bases, dict, name);
bad:
    Py_XDECREF(py_modname);
    return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
