/* Generated by Pyrex 0.9.8.5 on Thu Oct 30 10:45:41 2008 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "string.h"
#include "malloc.h"
#include "m_message.h"
#include "m_protocols.h"


typedef struct {PyObject **p; int i; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static void __Pyx_WriteUnraisable(char *name); /*proto*/

static int __Pyx_GetException(PyObject **type, PyObject **value, PyObject **tb); /*proto*/

static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from messaging */


/* Declarations from implementation of messaging */

typedef unsigned char __pyx_t_9messaging_BYTE;

typedef unsigned long __pyx_t_9messaging_DWORD;

typedef unsigned short __pyx_t_9messaging_WORD;

typedef unsigned short __pyx_t_9messaging_WCHAR;

typedef __pyx_t_9messaging_BYTE *__pyx_t_9messaging_PBYTE;

typedef void *__pyx_t_9messaging_HANDLE;

typedef int (*__pyx_t_9messaging_MIRANDAHOOK)(long,long);

enum  {
  __pyx_e_9messaging_MSG_WINDOW_EVT_OPENING = 1,
  __pyx_e_9messaging_MSG_WINDOW_EVT_OPEN = 2,
  __pyx_e_9messaging_MSG_WINDOW_EVT_CLOSING = 3,
  __pyx_e_9messaging_MSG_WINDOW_EVT_CLOSE = 4,
  __pyx_e_9messaging_MSG_WINDOW_EVT_CUSTOM = 5
};

static int __pyx_f_9messaging_CallContactService(unsigned long,char *,long,long); /*proto*/
static int __pyx_f_9messaging_CallProtocolService(char *,char *,long,long); /*proto*/
static int __pyx_f_9messaging_OnWindowEvent(long,long); /*proto*/
static int __pyx_f_9messaging_OnProtocolAck(long,long); /*proto*/
static PyObject *__pyx_f_9messaging___messagingAddEventHook(PyObject *,__pyx_t_9messaging_MIRANDAHOOK); /*proto*/

static char __pyx_k1[] = "hContact";
static char __pyx_k2[] = "hwndWindow";
static char __pyx_k3[] = "module";
static char __pyx_k4[] = "msgType";
static char __pyx_k5[] = "flags";
static char __pyx_k6[] = "MirPy";
static char __pyx_k7[] = "CallService";
static char __pyx_k8[] = "Proto/CallContactService";
static char __pyx_k9[] = "SRMsg/LaunchMessageWindow";
static char __pyx_k10[] = "ServiceNotFoundError";
static char __pyx_k11[] = "SRMsg/SendCommand";
static char __pyx_k12[] = "MessageAPI/WindowAPI";
static char __pyx_k13[] = "MessageAPI/WindowClass";
static char __pyx_k14[] = "/SendMsg";
static char __pyx_k15[] = "acks";
static char __pyx_k16[] = "/SetAwayMsg";
static char __pyx_k17[] = "__messagingLock";
static char __pyx_k18[] = "acquire";
static char __pyx_k19[] = "HookedMessagingEventsCallbacks";
static char __pyx_k20[] = "Error calling '%s' (%s)";
static char __pyx_k21[] = "__name__";
static char __pyx_k22[] = "release";
static char __pyx_k23[] = "HookedMessagingEvents";
static char __pyx_k24[] = "has_key";
static char __pyx_k25[] = "append";
static char __pyx_k26[] = "NoSuchEventError";
static char __pyx_k27[] = "The event '%s' was not found.";
static char __pyx_k28[] = "remove";
static char __pyx_k29[] = "NoSuchCallbackForEventError";
static char __pyx_k30[] = "The event '%s' has no callback '%s'";
static char __pyx_k31[] = "custom";
static char __pyx_k32[] = "opening";
static char __pyx_k33[] = "open";
static char __pyx_k34[] = "closing";
static char __pyx_k35[] = "close";
static char __pyx_k36[] = "WindowEvent";
static char __pyx_k37[] = "__CallEventCallbacks";
static char __pyx_k38[] = "MessageAPI/WindowEvent";
static char __pyx_k39[] = "database";
static char __pyx_k40[] = "DBEvent";
static char __pyx_k41[] = "time";
static char __pyx_k42[] = "Proto/Ack";
static char __pyx_k43[] = "keys";
static char __pyx_k44[] = "blob";
static char __pyx_k45[] = "cbBlob";
static char __pyx_k46[] = "EventAdd";
static char __pyx_k47[] = "HookEvent";
static char __pyx_k48[] = "values";
static char __pyx_k49[] = "UnhookEvent";
static char __pyx_k50[] = "Unhooking Messaging events";
static char __pyx_k51[] = "__UnhookMessagingEvents";
static char __pyx_k52[] = "threading";
static char __pyx_k53[] = "RLock";
static char __pyx_k54[] = "Class that holds message window event data.\n	DATA:\n		hContact   - the contact that the window belongs to.\n		hwndWindow - the handle of the window\n		module     - used to get plugin type\n		msgType    - one of the following value: opening, open, closing, close, custom\n		flags      - used to indicate message direction for all event types except custom\n	";
static char __pyx_k55[] = "__init__";
static char __pyx_k56[] = "MessageNotSentException";
static char __pyx_k57[] = "__HookMessagingEvents";

static PyObject *__pyx_n_CallService;
static PyObject *__pyx_n_DBEvent;
static PyObject *__pyx_n_EventAdd;
static PyObject *__pyx_n_HookEvent;
static PyObject *__pyx_n_HookedMessagingEvents;
static PyObject *__pyx_n_HookedMessagingEventsCallbacks;
static PyObject *__pyx_n_MessageNotSentException;
static PyObject *__pyx_n_MirPy;
static PyObject *__pyx_n_NoSuchCallbackForEventError;
static PyObject *__pyx_n_NoSuchEventError;
static PyObject *__pyx_n_RLock;
static PyObject *__pyx_n_ServiceNotFoundError;
static PyObject *__pyx_n_UnhookEvent;
static PyObject *__pyx_n_WindowEvent;
static PyObject *__pyx_n___CallEventCallbacks;
static PyObject *__pyx_n___HookMessagingEvents;
static PyObject *__pyx_n___UnhookMessagingEvents;
static PyObject *__pyx_n___init__;
static PyObject *__pyx_n___messagingLock;
static PyObject *__pyx_n___name__;
static PyObject *__pyx_n_acks;
static PyObject *__pyx_n_acquire;
static PyObject *__pyx_n_append;
static PyObject *__pyx_n_blob;
static PyObject *__pyx_n_cbBlob;
static PyObject *__pyx_n_close;
static PyObject *__pyx_n_closing;
static PyObject *__pyx_n_custom;
static PyObject *__pyx_n_database;
static PyObject *__pyx_n_flags;
static PyObject *__pyx_n_hContact;
static PyObject *__pyx_n_has_key;
static PyObject *__pyx_n_hwndWindow;
static PyObject *__pyx_n_keys;
static PyObject *__pyx_n_module;
static PyObject *__pyx_n_msgType;
static PyObject *__pyx_n_open;
static PyObject *__pyx_n_opening;
static PyObject *__pyx_n_release;
static PyObject *__pyx_n_remove;
static PyObject *__pyx_n_threading;
static PyObject *__pyx_n_time;
static PyObject *__pyx_n_values;

static PyObject *__pyx_k8p;
static PyObject *__pyx_k9p;
static PyObject *__pyx_k11p;
static PyObject *__pyx_k12p;
static PyObject *__pyx_k13p;
static PyObject *__pyx_k20p;
static PyObject *__pyx_k27p;
static PyObject *__pyx_k30p;
static PyObject *__pyx_k38p;
static PyObject *__pyx_k42p;
static PyObject *__pyx_k50p;
static PyObject *__pyx_k54p;

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_n_CallService, 1, __pyx_k7, sizeof(__pyx_k7)},
  {&__pyx_n_DBEvent, 1, __pyx_k40, sizeof(__pyx_k40)},
  {&__pyx_n_EventAdd, 1, __pyx_k46, sizeof(__pyx_k46)},
  {&__pyx_n_HookEvent, 1, __pyx_k47, sizeof(__pyx_k47)},
  {&__pyx_n_HookedMessagingEvents, 1, __pyx_k23, sizeof(__pyx_k23)},
  {&__pyx_n_HookedMessagingEventsCallbacks, 1, __pyx_k19, sizeof(__pyx_k19)},
  {&__pyx_n_MessageNotSentException, 1, __pyx_k56, sizeof(__pyx_k56)},
  {&__pyx_n_MirPy, 1, __pyx_k6, sizeof(__pyx_k6)},
  {&__pyx_n_NoSuchCallbackForEventError, 1, __pyx_k29, sizeof(__pyx_k29)},
  {&__pyx_n_NoSuchEventError, 1, __pyx_k26, sizeof(__pyx_k26)},
  {&__pyx_n_RLock, 1, __pyx_k53, sizeof(__pyx_k53)},
  {&__pyx_n_ServiceNotFoundError, 1, __pyx_k10, sizeof(__pyx_k10)},
  {&__pyx_n_UnhookEvent, 1, __pyx_k49, sizeof(__pyx_k49)},
  {&__pyx_n_WindowEvent, 1, __pyx_k36, sizeof(__pyx_k36)},
  {&__pyx_n___CallEventCallbacks, 1, __pyx_k37, sizeof(__pyx_k37)},
  {&__pyx_n___HookMessagingEvents, 1, __pyx_k57, sizeof(__pyx_k57)},
  {&__pyx_n___UnhookMessagingEvents, 1, __pyx_k51, sizeof(__pyx_k51)},
  {&__pyx_n___init__, 1, __pyx_k55, sizeof(__pyx_k55)},
  {&__pyx_n___messagingLock, 1, __pyx_k17, sizeof(__pyx_k17)},
  {&__pyx_n___name__, 1, __pyx_k21, sizeof(__pyx_k21)},
  {&__pyx_n_acks, 1, __pyx_k15, sizeof(__pyx_k15)},
  {&__pyx_n_acquire, 1, __pyx_k18, sizeof(__pyx_k18)},
  {&__pyx_n_append, 1, __pyx_k25, sizeof(__pyx_k25)},
  {&__pyx_n_blob, 1, __pyx_k44, sizeof(__pyx_k44)},
  {&__pyx_n_cbBlob, 1, __pyx_k45, sizeof(__pyx_k45)},
  {&__pyx_n_close, 1, __pyx_k35, sizeof(__pyx_k35)},
  {&__pyx_n_closing, 1, __pyx_k34, sizeof(__pyx_k34)},
  {&__pyx_n_custom, 1, __pyx_k31, sizeof(__pyx_k31)},
  {&__pyx_n_database, 1, __pyx_k39, sizeof(__pyx_k39)},
  {&__pyx_n_flags, 1, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_n_hContact, 1, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_n_has_key, 1, __pyx_k24, sizeof(__pyx_k24)},
  {&__pyx_n_hwndWindow, 1, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_n_keys, 1, __pyx_k43, sizeof(__pyx_k43)},
  {&__pyx_n_module, 1, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_n_msgType, 1, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_n_open, 1, __pyx_k33, sizeof(__pyx_k33)},
  {&__pyx_n_opening, 1, __pyx_k32, sizeof(__pyx_k32)},
  {&__pyx_n_release, 1, __pyx_k22, sizeof(__pyx_k22)},
  {&__pyx_n_remove, 1, __pyx_k28, sizeof(__pyx_k28)},
  {&__pyx_n_threading, 1, __pyx_k52, sizeof(__pyx_k52)},
  {&__pyx_n_time, 1, __pyx_k41, sizeof(__pyx_k41)},
  {&__pyx_n_values, 1, __pyx_k48, sizeof(__pyx_k48)},
  {&__pyx_k8p, 0, __pyx_k8, sizeof(__pyx_k8)},
  {&__pyx_k9p, 0, __pyx_k9, sizeof(__pyx_k9)},
  {&__pyx_k11p, 0, __pyx_k11, sizeof(__pyx_k11)},
  {&__pyx_k12p, 0, __pyx_k12, sizeof(__pyx_k12)},
  {&__pyx_k13p, 0, __pyx_k13, sizeof(__pyx_k13)},
  {&__pyx_k20p, 0, __pyx_k20, sizeof(__pyx_k20)},
  {&__pyx_k27p, 0, __pyx_k27, sizeof(__pyx_k27)},
  {&__pyx_k30p, 0, __pyx_k30, sizeof(__pyx_k30)},
  {&__pyx_k38p, 0, __pyx_k38, sizeof(__pyx_k38)},
  {&__pyx_k42p, 0, __pyx_k42, sizeof(__pyx_k42)},
  {&__pyx_k50p, 0, __pyx_k50, sizeof(__pyx_k50)},
  {&__pyx_k54p, 0, __pyx_k54, sizeof(__pyx_k54)},
  {0, 0, 0, 0}
};

static char *__pyx_d1;


/* Implementation of messaging */

static PyObject *__pyx_f_9messaging_11WindowEvent___init__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyMethodDef __pyx_mdef_9messaging_11WindowEvent___init__ = {"__init__", (PyCFunction)__pyx_f_9messaging_11WindowEvent___init__, METH_VARARGS|METH_KEYWORDS, 0};
static PyObject *__pyx_f_9messaging_11WindowEvent___init__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_hContact = 0;
  PyObject *__pyx_v_hwndWindow = 0;
  PyObject *__pyx_v_module = 0;
  PyObject *__pyx_v_msgType = 0;
  PyObject *__pyx_v_flags = 0;
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {"self","hContact","hwndWindow","module","msgType","flags",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOOOOO", __pyx_argnames, &__pyx_v_self, &__pyx_v_hContact, &__pyx_v_hwndWindow, &__pyx_v_module, &__pyx_v_msgType, &__pyx_v_flags)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_hContact);
  Py_INCREF(__pyx_v_hwndWindow);
  Py_INCREF(__pyx_v_module);
  Py_INCREF(__pyx_v_msgType);
  Py_INCREF(__pyx_v_flags);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":33 */
  if (PyObject_SetAttr(__pyx_v_self, __pyx_n_hContact, __pyx_v_hContact) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":34 */
  if (PyObject_SetAttr(__pyx_v_self, __pyx_n_hwndWindow, __pyx_v_hwndWindow) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; goto __pyx_L1;}

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":35 */
  if (PyObject_SetAttr(__pyx_v_self, __pyx_n_module, __pyx_v_module) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; goto __pyx_L1;}

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":36 */
  if (PyObject_SetAttr(__pyx_v_self, __pyx_n_msgType, __pyx_v_msgType) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; goto __pyx_L1;}

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":37 */
  if (PyObject_SetAttr(__pyx_v_self, __pyx_n_flags, __pyx_v_flags) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("messaging.WindowEvent.__init__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_hContact);
  Py_DECREF(__pyx_v_hwndWindow);
  Py_DECREF(__pyx_v_module);
  Py_DECREF(__pyx_v_msgType);
  Py_DECREF(__pyx_v_flags);
  return __pyx_r;
}

static int __pyx_f_9messaging_CallContactService(unsigned long __pyx_v_hContact,char *__pyx_v_szProtoService,long __pyx_v_wParam,long __pyx_v_lParam) {
  CCSDATA __pyx_v_ccs;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  int __pyx_5;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":82 */
  __pyx_v_ccs.hContact = __pyx_v_hContact;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":83 */
  __pyx_v_ccs.szProtoService = __pyx_v_szProtoService;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":84 */
  __pyx_v_ccs.wParam = __pyx_v_wParam;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":85 */
  __pyx_v_ccs.lParam = __pyx_v_lParam;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":86 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_CallService); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(((long)(&__pyx_v_ccs))); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  Py_INCREF(__pyx_k8p);
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_k8p);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_1);
  PyTuple_SET_ITEM(__pyx_4, 2, __pyx_3);
  __pyx_1 = 0;
  __pyx_3 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_5 = PyInt_AsLong(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_r = __pyx_5;
  goto __pyx_L0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_WriteUnraisable("messaging.CallContactService");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static int __pyx_f_9messaging_CallProtocolService(char *__pyx_v_protocol,char *__pyx_v_service,long __pyx_v_wParam,long __pyx_v_lParam) {
  char __pyx_v_buffer[512];
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  int __pyx_6;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":90 */
  strcpy(__pyx_v_buffer,__pyx_v_protocol);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":91 */
  strcat(__pyx_v_buffer,__pyx_v_service);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":92 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_CallService); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyString_FromString(__pyx_v_buffer); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_v_wParam); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  __pyx_4 = PyInt_FromLong(__pyx_v_lParam); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_1);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_3);
  PyTuple_SET_ITEM(__pyx_5, 2, __pyx_4);
  __pyx_1 = 0;
  __pyx_3 = 0;
  __pyx_4 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_5); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_6 = PyInt_AsLong(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_r = __pyx_6;
  goto __pyx_L0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_WriteUnraisable("messaging.CallProtocolService");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static PyObject *__pyx_f_9messaging_ShowMessageWindow(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_9messaging_ShowMessageWindow[] = "Shows the message window for a particular contact.\n	ShowMessageWindow(hContact, text = None).\n	";
static PyObject *__pyx_f_9messaging_ShowMessageWindow(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  long __pyx_v_hContact;
  char *__pyx_v_text;
  int __pyx_v_res;
  PyObject *__pyx_v_e;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  int __pyx_5;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  PyObject *__pyx_8 = 0;
  static char *__pyx_argnames[] = {"hContact","text",0};
  __pyx_v_text = __pyx_d1;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "l|s", __pyx_argnames, &__pyx_v_hContact, &__pyx_v_text)) return 0;
  __pyx_v_e = Py_None; Py_INCREF(Py_None);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":99 */
  /*try:*/ {
    __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L2;}
    __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_CallService); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L2;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_1 = PyInt_FromLong(__pyx_v_hContact); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L2;}
    __pyx_3 = PyInt_FromLong(((long)__pyx_v_text)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L2;}
    __pyx_4 = PyTuple_New(3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L2;}
    Py_INCREF(__pyx_k9p);
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_k9p);
    PyTuple_SET_ITEM(__pyx_4, 1, __pyx_1);
    PyTuple_SET_ITEM(__pyx_4, 2, __pyx_3);
    __pyx_1 = 0;
    __pyx_3 = 0;
    __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L2;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_5 = PyInt_AsLong(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L2;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_v_res = __pyx_5;
  }
  goto __pyx_L3;
  __pyx_L2:;
  Py_XDECREF(__pyx_3); __pyx_3 = 0;
  Py_XDECREF(__pyx_2); __pyx_2 = 0;
  Py_XDECREF(__pyx_4); __pyx_4 = 0;
  Py_XDECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":101 */
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_3, __pyx_n_ServiceNotFoundError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_5 = PyErr_ExceptionMatches(__pyx_2);
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (__pyx_5) {
    __Pyx_AddTraceback("messaging.ShowMessageWindow");
    if (__Pyx_GetException(&__pyx_4, &__pyx_1, &__pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
    Py_INCREF(__pyx_1);
    Py_DECREF(__pyx_v_e);
    __pyx_v_e = __pyx_1;
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
    __pyx_6 = PyObject_GetAttr(__pyx_2, __pyx_n_CallService); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_2 = PyInt_FromLong(__pyx_v_hContact); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
    __pyx_7 = PyInt_FromLong(((long)__pyx_v_text)); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
    __pyx_8 = PyTuple_New(3); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
    Py_INCREF(__pyx_k11p);
    PyTuple_SET_ITEM(__pyx_8, 0, __pyx_k11p);
    PyTuple_SET_ITEM(__pyx_8, 1, __pyx_2);
    PyTuple_SET_ITEM(__pyx_8, 2, __pyx_7);
    __pyx_2 = 0;
    __pyx_7 = 0;
    __pyx_2 = PyObject_CallObject(__pyx_6, __pyx_8); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    Py_DECREF(__pyx_8); __pyx_8 = 0;
    __pyx_5 = PyInt_AsLong(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_v_res = __pyx_5;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    goto __pyx_L3;
  }
  goto __pyx_L1;
  __pyx_L3:;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":103 */
  __pyx_7 = PyInt_FromLong(__pyx_v_res); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; goto __pyx_L1;}
  __pyx_r = __pyx_7;
  __pyx_7 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  Py_XDECREF(__pyx_8);
  __Pyx_AddTraceback("messaging.ShowMessageWindow");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_e);
  return __pyx_r;
}

static PyObject *__pyx_f_9messaging_GetMessageWindowApi(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_9messaging_GetMessageWindowApi[] = "Returns the current message window api.\n	Current version is 0.0.0.3.\n	";
static PyObject *__pyx_f_9messaging_GetMessageWindowApi(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_CallService); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  Py_INCREF(__pyx_k12p);
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_k12p);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_1);
  PyTuple_SET_ITEM(__pyx_4, 2, __pyx_3);
  __pyx_1 = 0;
  __pyx_3 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("messaging.GetMessageWindowApi");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static PyObject *__pyx_f_9messaging_GetMessageWindowClass(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_9messaging_GetMessageWindowClass[] = "Returns the message window class.\n	";
static PyObject *__pyx_f_9messaging_GetMessageWindowClass(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char __pyx_v_buffer[2048];
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":115 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_CallService); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyInt_FromLong(((long)__pyx_v_buffer)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(2048); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
  Py_INCREF(__pyx_k13p);
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_k13p);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_1);
  PyTuple_SET_ITEM(__pyx_4, 2, __pyx_3);
  __pyx_1 = 0;
  __pyx_3 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":116 */
  __pyx_3 = PyString_FromString(__pyx_v_buffer); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("messaging.GetMessageWindowClass");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static PyObject *__pyx_f_9messaging_SendMessage(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_9messaging_SendMessage[] = "Sends a message to a contact.\n	SendMessage(hContact, message)\n	";
static PyObject *__pyx_f_9messaging_SendMessage(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_hContact = 0;
  char *__pyx_v_message;
  PyObject *__pyx_v_hProcess;
  PyObject *__pyx_r;
  unsigned long __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"hContact","message",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "Os", __pyx_argnames, &__pyx_v_hContact, &__pyx_v_message)) return 0;
  Py_INCREF(__pyx_v_hContact);
  __pyx_v_hProcess = Py_None; Py_INCREF(Py_None);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":122 */
  __pyx_1 = PyInt_AsUnsignedLongMask(__pyx_v_hContact); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 122; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(__pyx_f_9messaging_CallContactService(__pyx_1,__pyx_k14,0,((long)__pyx_v_message))); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 122; goto __pyx_L1;}
  Py_DECREF(__pyx_v_hProcess);
  __pyx_v_hProcess = __pyx_2;
  __pyx_2 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":123 */
  __pyx_2 = PyString_FromString(__pyx_v_message); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; goto __pyx_L1;}
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_acks); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; goto __pyx_L1;}
  if (PyObject_SetItem(__pyx_3, __pyx_v_hProcess, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("messaging.SendMessage");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_hProcess);
  Py_DECREF(__pyx_v_hContact);
  return __pyx_r;
}

static PyObject *__pyx_f_9messaging_SetStatusMessage(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_9messaging_SetStatusMessage[] = "Changes the status message for a protocol.\n	SetStatusMessage(protocol, statusMessage)\n	";
static PyObject *__pyx_f_9messaging_SetStatusMessage(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char *__pyx_v_protocol;
  char *__pyx_v_statusMessage;
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {"protocol","statusMessage",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "ss", __pyx_argnames, &__pyx_v_protocol, &__pyx_v_statusMessage)) return 0;
  __pyx_f_9messaging_CallProtocolService(__pyx_v_protocol,__pyx_k16,0,((long)__pyx_v_statusMessage));

  __pyx_r = Py_None; Py_INCREF(Py_None);
  return __pyx_r;
}

static PyObject *__pyx_f_9messaging___CallEventCallbacks(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9messaging___CallEventCallbacks(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_event = 0;
  PyObject *__pyx_v_wParam = 0;
  PyObject *__pyx_v_lParam = 0;
  PyObject *__pyx_v_res;
  PyObject *__pyx_v_list;
  PyObject *__pyx_v_callback;
  PyObject *__pyx_v_e;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  static char *__pyx_argnames[] = {"event","wParam","lParam",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_event, &__pyx_v_wParam, &__pyx_v_lParam)) return 0;
  Py_INCREF(__pyx_v_event);
  Py_INCREF(__pyx_v_wParam);
  Py_INCREF(__pyx_v_lParam);
  __pyx_v_res = Py_None; Py_INCREF(Py_None);
  __pyx_v_list = Py_None; Py_INCREF(Py_None);
  __pyx_v_callback = Py_None; Py_INCREF(Py_None);
  __pyx_v_e = Py_None; Py_INCREF(Py_None);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":138 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 138; goto __pyx_L1;}
  Py_DECREF(__pyx_v_res);
  __pyx_v_res = __pyx_1;
  __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":139 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n___messagingLock); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 139; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_acquire); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 139; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 139; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":140 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_HookedMessagingEventsCallbacks); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
  __pyx_1 = PyObject_GetItem(__pyx_2, __pyx_v_event); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_v_list);
  __pyx_v_list = __pyx_1;
  __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":141 */
  __pyx_2 = PyObject_GetIter(__pyx_v_list); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 141; goto __pyx_L1;}
  for (;;) {
    __pyx_1 = PyIter_Next(__pyx_2);
    if (!__pyx_1) {
      if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 141; goto __pyx_L1;}
      break;
    }
    Py_DECREF(__pyx_v_callback);
    __pyx_v_callback = __pyx_1;
    __pyx_1 = 0;

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":142 */
    /*try:*/ {
      __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 143; goto __pyx_L4;}
      Py_INCREF(__pyx_v_wParam);
      PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_wParam);
      Py_INCREF(__pyx_v_lParam);
      PyTuple_SET_ITEM(__pyx_1, 1, __pyx_v_lParam);
      __pyx_3 = PyObject_CallObject(__pyx_v_callback, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 143; goto __pyx_L4;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      Py_DECREF(__pyx_v_res);
      __pyx_v_res = __pyx_3;
      __pyx_3 = 0;
    }
    goto __pyx_L5;
    __pyx_L4:;
    Py_XDECREF(__pyx_1); __pyx_1 = 0;
    Py_XDECREF(__pyx_3); __pyx_3 = 0;

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":144 */
    __pyx_4 = PyErr_ExceptionMatches(PyExc_Exception);
    if (__pyx_4) {
      __Pyx_AddTraceback("messaging.__CallEventCallbacks");
      if (__Pyx_GetException(&__pyx_1, &__pyx_3, &__pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 144; goto __pyx_L1;}
      Py_INCREF(__pyx_3);
      Py_DECREF(__pyx_v_e);
      __pyx_v_e = __pyx_3;
      __pyx_6 = PyObject_GetAttr(__pyx_v_callback, __pyx_n___name__); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
      __pyx_7 = PyTuple_New(2); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_7, 0, __pyx_6);
      Py_INCREF(__pyx_v_e);
      PyTuple_SET_ITEM(__pyx_7, 1, __pyx_v_e);
      __pyx_6 = 0;
      __pyx_6 = PyNumber_Remainder(__pyx_k20p, __pyx_7); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
      Py_DECREF(__pyx_7); __pyx_7 = 0;
      if (__Pyx_PrintItem(__pyx_6) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
      Py_DECREF(__pyx_6); __pyx_6 = 0;
      if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      goto __pyx_L5;
    }
    goto __pyx_L1;
    __pyx_L5:;

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":146 */
    if (PyObject_Cmp(__pyx_v_res, Py_None, &__pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 146; goto __pyx_L1;}
    __pyx_4 = __pyx_4 != 0;
    if (__pyx_4) {
      __pyx_7 = PyInt_FromLong(0); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 146; goto __pyx_L1;}
      if (PyObject_Cmp(__pyx_v_res, __pyx_7, &__pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 146; goto __pyx_L1;}
      __pyx_4 = __pyx_4 != 0;
      Py_DECREF(__pyx_7); __pyx_7 = 0;
    }
    if (__pyx_4) {
      goto __pyx_L3;
      goto __pyx_L6;
    }
    __pyx_L6:;
  }
  __pyx_L3:;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":148 */
  if (PyObject_Cmp(__pyx_v_res, Py_None, &__pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L1;}
  __pyx_4 = __pyx_4 == 0;
  if (__pyx_4) {
    __pyx_6 = PyInt_FromLong(0); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; goto __pyx_L1;}
    Py_DECREF(__pyx_v_res);
    __pyx_v_res = __pyx_6;
    __pyx_6 = 0;
    goto __pyx_L7;
  }
  __pyx_L7:;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":150 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n___messagingLock); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_1, __pyx_n_release); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_5 = PyObject_CallObject(__pyx_3, 0); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":152 */
  Py_INCREF(__pyx_v_res);
  __pyx_r = __pyx_v_res;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  __Pyx_AddTraceback("messaging.__CallEventCallbacks");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_res);
  Py_DECREF(__pyx_v_list);
  Py_DECREF(__pyx_v_callback);
  Py_DECREF(__pyx_v_e);
  Py_DECREF(__pyx_v_event);
  Py_DECREF(__pyx_v_wParam);
  Py_DECREF(__pyx_v_lParam);
  return __pyx_r;
}

static PyObject *__pyx_f_9messaging_HookMessagingEvent(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_9messaging_HookMessagingEvent[] = "Hooks a messaging event.\n	HookMessagingEvent(event, callback)\n		event - the event string. To find out all available events type \"print messaging.HookedMessagingEvents.keys()\" (do not modify this dictionary !!!)\n		callback - python function that gets called when the event occurs. The declaration is OnEvent(wParam, lParam); the actual parameters depend on the event.	\n	";
static PyObject *__pyx_f_9messaging_HookMessagingEvent(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_event = 0;
  PyObject *__pyx_v_callback = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  static char *__pyx_argnames[] = {"event","callback",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_event, &__pyx_v_callback)) return 0;
  Py_INCREF(__pyx_v_event);
  Py_INCREF(__pyx_v_callback);
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_HookedMessagingEvents); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 160; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_has_key); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 160; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 160; goto __pyx_L1;}
  Py_INCREF(__pyx_v_event);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_event);
  __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 160; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_4 = PyObject_IsTrue(__pyx_3); if (__pyx_4 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 160; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (__pyx_4) {
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_HookedMessagingEventsCallbacks); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
    __pyx_1 = PyObject_GetItem(__pyx_2, __pyx_v_event); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_3 = PyObject_GetAttr(__pyx_1, __pyx_n_append); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
    Py_INCREF(__pyx_v_callback);
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_callback);
    __pyx_1 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    goto __pyx_L2;
  }
  /*else*/ {
    __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
    __pyx_2 = PyObject_GetAttr(__pyx_3, __pyx_n_NoSuchEventError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_1 = PyNumber_Remainder(__pyx_k27p, __pyx_v_event); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_1);
    __pyx_1 = 0;
    __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_1, 0, 0);
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("messaging.HookMessagingEvent");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_event);
  Py_DECREF(__pyx_v_callback);
  return __pyx_r;
}

static PyObject *__pyx_f_9messaging_UnhookMessagingEvent(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_9messaging_UnhookMessagingEvent[] = "Unhooks a previously hooked messaging event.\n	UnhookMessagingEvent(event, callback)\n		event - the event to unhook. Must have been previously hooked with a call to HookMessagingEvent.\n		callback - the event callback.\n	Both parameters are required because the same callback could be used to hook multiple events.\n	";
static PyObject *__pyx_f_9messaging_UnhookMessagingEvent(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_event = 0;
  PyObject *__pyx_v_callback = 0;
  PyObject *__pyx_v_e;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  static char *__pyx_argnames[] = {"event","callback",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_event, &__pyx_v_callback)) return 0;
  Py_INCREF(__pyx_v_event);
  Py_INCREF(__pyx_v_callback);
  __pyx_v_e = Py_None; Py_INCREF(Py_None);
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_HookedMessagingEvents); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 173; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_has_key); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 173; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 173; goto __pyx_L1;}
  Py_INCREF(__pyx_v_event);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_event);
  __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 173; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_4 = PyObject_IsTrue(__pyx_3); if (__pyx_4 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 173; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (__pyx_4) {
    /*try:*/ {
      __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_HookedMessagingEventsCallbacks); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 175; goto __pyx_L3;}
      __pyx_1 = PyObject_GetItem(__pyx_2, __pyx_v_event); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 175; goto __pyx_L3;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      __pyx_3 = PyObject_GetAttr(__pyx_1, __pyx_n_remove); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 175; goto __pyx_L3;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 175; goto __pyx_L3;}
      Py_INCREF(__pyx_v_callback);
      PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_callback);
      __pyx_1 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 175; goto __pyx_L3;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_1); __pyx_1 = 0;
    }
    goto __pyx_L4;
    __pyx_L3:;
    Py_XDECREF(__pyx_3); __pyx_3 = 0;
    Py_XDECREF(__pyx_2); __pyx_2 = 0;
    Py_XDECREF(__pyx_1); __pyx_1 = 0;

    /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":176 */
    __pyx_4 = PyErr_ExceptionMatches(PyExc_Exception);
    if (__pyx_4) {
      __Pyx_AddTraceback("messaging.UnhookMessagingEvent");
      if (__Pyx_GetException(&__pyx_3, &__pyx_2, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 176; goto __pyx_L1;}
      Py_INCREF(__pyx_2);
      Py_DECREF(__pyx_v_e);
      __pyx_v_e = __pyx_2;
      __pyx_5 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; goto __pyx_L1;}
      __pyx_6 = PyObject_GetAttr(__pyx_5, __pyx_n_NoSuchCallbackForEventError); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      __pyx_5 = PyTuple_New(2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; goto __pyx_L1;}
      Py_INCREF(__pyx_v_event);
      PyTuple_SET_ITEM(__pyx_5, 0, __pyx_v_event);
      Py_INCREF(__pyx_v_callback);
      PyTuple_SET_ITEM(__pyx_5, 1, __pyx_v_callback);
      __pyx_7 = PyNumber_Remainder(__pyx_k30p, __pyx_5); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      __pyx_5 = PyTuple_New(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_5, 0, __pyx_7);
      __pyx_7 = 0;
      __pyx_7 = PyObject_CallObject(__pyx_6, __pyx_5); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; goto __pyx_L1;}
      Py_DECREF(__pyx_6); __pyx_6 = 0;
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      __Pyx_Raise(__pyx_7, 0, 0);
      Py_DECREF(__pyx_7); __pyx_7 = 0;
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 177; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      goto __pyx_L4;
    }
    goto __pyx_L1;
    __pyx_L4:;
    goto __pyx_L2;
  }
  /*else*/ {
    __pyx_6 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 179; goto __pyx_L1;}
    __pyx_5 = PyObject_GetAttr(__pyx_6, __pyx_n_NoSuchEventError); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 179; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __pyx_7 = PyNumber_Remainder(__pyx_k27p, __pyx_v_event); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 179; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 179; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_7);
    __pyx_7 = 0;
    __pyx_2 = PyObject_CallObject(__pyx_5, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 179; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_2, 0, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 179; goto __pyx_L1;}
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  __Pyx_AddTraceback("messaging.UnhookMessagingEvent");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_e);
  Py_DECREF(__pyx_v_event);
  Py_DECREF(__pyx_v_callback);
  return __pyx_r;
}

static int __pyx_f_9messaging_OnWindowEvent(long __pyx_v_wParam,long __pyx_v_lParam) {
  MessageWindowEventData *__pyx_v_eventData;
  long __pyx_v_hContact;
  PyObject *__pyx_v_msgType;
  PyObject *__pyx_v_event;
  int __pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  __pyx_v_msgType = Py_None; Py_INCREF(Py_None);
  __pyx_v_event = Py_None; Py_INCREF(Py_None);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":183 */
  __pyx_v_eventData = ((MessageWindowEventData *)__pyx_v_lParam);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":185 */
  __pyx_v_hContact = ((long)__pyx_v_eventData->hContact);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":186 */
  Py_INCREF(__pyx_n_custom);
  Py_DECREF(__pyx_v_msgType);
  __pyx_v_msgType = __pyx_n_custom;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":187 */
  __pyx_1 = (__pyx_v_eventData->uType == __pyx_e_9messaging_MSG_WINDOW_EVT_OPENING);
  if (__pyx_1) {
    Py_INCREF(__pyx_n_opening);
    Py_DECREF(__pyx_v_msgType);
    __pyx_v_msgType = __pyx_n_opening;
    goto __pyx_L2;
  }
  __pyx_1 = (__pyx_v_eventData->uType == __pyx_e_9messaging_MSG_WINDOW_EVT_OPEN);
  if (__pyx_1) {
    Py_INCREF(__pyx_n_open);
    Py_DECREF(__pyx_v_msgType);
    __pyx_v_msgType = __pyx_n_open;
    goto __pyx_L2;
  }
  __pyx_1 = (__pyx_v_eventData->uType == __pyx_e_9messaging_MSG_WINDOW_EVT_CLOSING);
  if (__pyx_1) {
    Py_INCREF(__pyx_n_closing);
    Py_DECREF(__pyx_v_msgType);
    __pyx_v_msgType = __pyx_n_closing;
    goto __pyx_L2;
  }
  __pyx_1 = (__pyx_v_eventData->uType == __pyx_e_9messaging_MSG_WINDOW_EVT_CLOSE);
  if (__pyx_1) {
    Py_INCREF(__pyx_n_close);
    Py_DECREF(__pyx_v_msgType);
    __pyx_v_msgType = __pyx_n_close;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":196 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_WindowEvent); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 196; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_v_hContact); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 196; goto __pyx_L1;}
  __pyx_4 = PyLong_FromUnsignedLong(__pyx_v_eventData->hwndWindow); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 196; goto __pyx_L1;}
  __pyx_5 = PyString_FromString(__pyx_v_eventData->szModule); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 196; goto __pyx_L1;}
  __pyx_6 = PyLong_FromUnsignedLong(__pyx_v_eventData->uFlags); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 196; goto __pyx_L1;}
  __pyx_7 = PyTuple_New(5); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 196; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_7, 0, __pyx_3);
  PyTuple_SET_ITEM(__pyx_7, 1, __pyx_4);
  PyTuple_SET_ITEM(__pyx_7, 2, __pyx_5);
  Py_INCREF(__pyx_v_msgType);
  PyTuple_SET_ITEM(__pyx_7, 3, __pyx_v_msgType);
  PyTuple_SET_ITEM(__pyx_7, 4, __pyx_6);
  __pyx_3 = 0;
  __pyx_4 = 0;
  __pyx_5 = 0;
  __pyx_6 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_7); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 196; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_7); __pyx_7 = 0;
  Py_DECREF(__pyx_v_event);
  __pyx_v_event = __pyx_3;
  __pyx_3 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":197 */
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n___CallEventCallbacks); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 197; goto __pyx_L1;}
  __pyx_5 = PyInt_FromLong(__pyx_v_wParam); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 197; goto __pyx_L1;}
  __pyx_6 = PyTuple_New(3); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 197; goto __pyx_L1;}
  Py_INCREF(__pyx_k38p);
  PyTuple_SET_ITEM(__pyx_6, 0, __pyx_k38p);
  PyTuple_SET_ITEM(__pyx_6, 1, __pyx_5);
  Py_INCREF(__pyx_v_event);
  PyTuple_SET_ITEM(__pyx_6, 2, __pyx_v_event);
  __pyx_5 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_4, __pyx_6); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 197; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  __pyx_1 = PyInt_AsLong(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 197; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_r = __pyx_1;
  goto __pyx_L0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  __Pyx_WriteUnraisable("messaging.OnWindowEvent");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_msgType);
  Py_DECREF(__pyx_v_event);
  return __pyx_r;
}

static int __pyx_f_9messaging_OnProtocolAck(long __pyx_v_wParam,long __pyx_v_lParam) {
  ACKDATA *__pyx_v_ack;
  PyObject *__pyx_v_result;
  PyObject *__pyx_v_hContact;
  PyObject *__pyx_v_event;
  PyObject *__pyx_v_hProcess;
  PyObject *__pyx_v_message;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  int __pyx_8;
  Py_ssize_t __pyx_9;
  __pyx_v_result = Py_None; Py_INCREF(Py_None);
  __pyx_v_hContact = Py_None; Py_INCREF(Py_None);
  __pyx_v_event = Py_None; Py_INCREF(Py_None);
  __pyx_v_hProcess = Py_None; Py_INCREF(Py_None);
  __pyx_v_message = Py_None; Py_INCREF(Py_None);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":203 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 203; goto __pyx_L1;}
  Py_DECREF(__pyx_v_result);
  __pyx_v_result = __pyx_1;
  __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":204 */
  __pyx_v_ack = ((ACKDATA *)__pyx_v_lParam);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":206 */
  __pyx_1 = PyLong_FromUnsignedLong(((unsigned long)__pyx_v_ack->hContact)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 206; goto __pyx_L1;}
  Py_DECREF(__pyx_v_hContact);
  __pyx_v_hContact = __pyx_1;
  __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":207 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_database); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_DBEvent); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyString_FromString(__pyx_v_ack->szModule); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; goto __pyx_L1;}
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_time); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; goto __pyx_L1;}
  __pyx_4 = PyObject_GetAttr(__pyx_3, __pyx_n_time); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_4, 0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_4 = PyInt_FromLong(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; goto __pyx_L1;}
  __pyx_5 = PyInt_FromLong(0); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; goto __pyx_L1;}
  __pyx_6 = PyLong_FromUnsignedLong(__pyx_v_ack->lParam); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; goto __pyx_L1;}
  __pyx_7 = PyTuple_New(5); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_7, 0, __pyx_1);
  PyTuple_SET_ITEM(__pyx_7, 1, __pyx_3);
  PyTuple_SET_ITEM(__pyx_7, 2, __pyx_4);
  PyTuple_SET_ITEM(__pyx_7, 3, __pyx_5);
  PyTuple_SET_ITEM(__pyx_7, 4, __pyx_6);
  __pyx_1 = 0;
  __pyx_3 = 0;
  __pyx_4 = 0;
  __pyx_5 = 0;
  __pyx_6 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_7); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 207; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_7); __pyx_7 = 0;
  Py_DECREF(__pyx_v_event);
  __pyx_v_event = __pyx_1;
  __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":208 */
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n___CallEventCallbacks); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; goto __pyx_L1;}
  __pyx_4 = PyInt_FromLong(__pyx_v_wParam); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; goto __pyx_L1;}
  Py_INCREF(__pyx_k42p);
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_k42p);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_4);
  Py_INCREF(__pyx_v_event);
  PyTuple_SET_ITEM(__pyx_5, 2, __pyx_v_event);
  __pyx_4 = 0;
  __pyx_6 = PyObject_CallObject(__pyx_3, __pyx_5); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  Py_DECREF(__pyx_v_result);
  __pyx_v_result = __pyx_6;
  __pyx_6 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":210 */
  __pyx_8 = (__pyx_v_ack->type == 0);
  if (__pyx_8) {
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_acks); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L1;}
    __pyx_7 = PyObject_GetAttr(__pyx_2, __pyx_n_keys); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_1 = PyObject_CallObject(__pyx_7, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L1;}
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    __pyx_4 = PyObject_GetIter(__pyx_1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    for (;;) {
      __pyx_3 = PyIter_Next(__pyx_4);
      if (!__pyx_3) {
        if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L1;}
        break;
      }
      Py_DECREF(__pyx_v_hProcess);
      __pyx_v_hProcess = __pyx_3;
      __pyx_3 = 0;
      __pyx_5 = PyLong_FromUnsignedLong(((unsigned long)__pyx_v_ack->hProcess)); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 212; goto __pyx_L1;}
      if (PyObject_Cmp(__pyx_5, __pyx_v_hProcess, &__pyx_8) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 212; goto __pyx_L1;}
      __pyx_8 = __pyx_8 == 0;
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      if (__pyx_8) {
        __pyx_8 = (__pyx_v_ack->result == 0);
        if (__pyx_8) {

          /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":214 */
          __pyx_6 = __Pyx_GetName(__pyx_m, __pyx_n_acks); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 214; goto __pyx_L1;}
          __pyx_2 = PyObject_GetItem(__pyx_6, __pyx_v_hProcess); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 214; goto __pyx_L1;}
          Py_DECREF(__pyx_6); __pyx_6 = 0;
          Py_DECREF(__pyx_v_message);
          __pyx_v_message = __pyx_2;
          __pyx_2 = 0;

          /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":215 */
          if (PyObject_SetAttr(__pyx_v_event, __pyx_n_blob, __pyx_v_message) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 215; goto __pyx_L1;}

          /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":216 */
          __pyx_9 = PyObject_Length(__pyx_v_message); if (__pyx_9 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 216; goto __pyx_L1;}
          __pyx_7 = PyInt_FromSsize_t(__pyx_9); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 216; goto __pyx_L1;}
          if (PyObject_SetAttr(__pyx_v_event, __pyx_n_cbBlob, __pyx_7) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 216; goto __pyx_L1;}
          Py_DECREF(__pyx_7); __pyx_7 = 0;

          /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":218 */
          __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_database); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 218; goto __pyx_L1;}
          __pyx_3 = PyObject_GetAttr(__pyx_1, __pyx_n_EventAdd); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 218; goto __pyx_L1;}
          Py_DECREF(__pyx_1); __pyx_1 = 0;
          __pyx_5 = PyTuple_New(2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 218; goto __pyx_L1;}
          Py_INCREF(__pyx_v_hContact);
          PyTuple_SET_ITEM(__pyx_5, 0, __pyx_v_hContact);
          Py_INCREF(__pyx_v_event);
          PyTuple_SET_ITEM(__pyx_5, 1, __pyx_v_event);
          __pyx_6 = PyObject_CallObject(__pyx_3, __pyx_5); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 218; goto __pyx_L1;}
          Py_DECREF(__pyx_3); __pyx_3 = 0;
          Py_DECREF(__pyx_5); __pyx_5 = 0;
          Py_DECREF(__pyx_6); __pyx_6 = 0;

          /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":220 */
          __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_acks); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 220; goto __pyx_L1;}
          if (PyObject_DelItem(__pyx_2, __pyx_v_hProcess) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 220; goto __pyx_L1;}
          Py_DECREF(__pyx_2); __pyx_2 = 0;
          goto __pyx_L6;
        }
        __pyx_L6:;
        goto __pyx_L5;
      }
      __pyx_L5:;
    }
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":222 */
  __pyx_8 = PyInt_AsLong(__pyx_v_result); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 222; goto __pyx_L1;}
  __pyx_r = __pyx_8;
  goto __pyx_L0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  __Pyx_WriteUnraisable("messaging.OnProtocolAck");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_result);
  Py_DECREF(__pyx_v_hContact);
  Py_DECREF(__pyx_v_event);
  Py_DECREF(__pyx_v_hProcess);
  Py_DECREF(__pyx_v_message);
  return __pyx_r;
}

static PyObject *__pyx_f_9messaging___messagingAddEventHook(PyObject *__pyx_v_event,__pyx_t_9messaging_MIRANDAHOOK __pyx_v_function) {
  PyObject *__pyx_v_handle;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  Py_INCREF(__pyx_v_event);
  __pyx_v_handle = Py_None; Py_INCREF(Py_None);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":225 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 225; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_HookEvent); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 225; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyInt_FromLong(((long)__pyx_v_function)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 225; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 225; goto __pyx_L1;}
  Py_INCREF(__pyx_v_event);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_event);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_1);
  __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 225; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_v_handle);
  __pyx_v_handle = __pyx_1;
  __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":226 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_HookedMessagingEvents); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 226; goto __pyx_L1;}
  if (PyObject_SetItem(__pyx_2, __pyx_v_event, __pyx_v_handle) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 226; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":227 */
  __pyx_3 = PyList_New(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 227; goto __pyx_L1;}
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_HookedMessagingEventsCallbacks); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 227; goto __pyx_L1;}
  if (PyObject_SetItem(__pyx_1, __pyx_v_event, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 227; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("messaging.__messagingAddEventHook");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_handle);
  Py_DECREF(__pyx_v_event);
  return __pyx_r;
}

static PyObject *__pyx_f_9messaging___HookMessagingEvents(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9messaging___HookMessagingEvents(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":230 */
  __pyx_1 = __pyx_f_9messaging___messagingAddEventHook(__pyx_k38p,__pyx_f_9messaging_OnWindowEvent); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 230; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":231 */
  __pyx_1 = __pyx_f_9messaging___messagingAddEventHook(__pyx_k42p,__pyx_f_9messaging_OnProtocolAck); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 231; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("messaging.__HookMessagingEvents");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static PyObject *__pyx_f_9messaging___UnhookMessagingEvents(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9messaging___UnhookMessagingEvents(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_handle;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  __pyx_v_handle = Py_None; Py_INCREF(Py_None);
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_HookedMessagingEvents); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 234; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_values); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 234; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 234; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyObject_GetIter(__pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 234; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  for (;;) {
    __pyx_1 = PyIter_Next(__pyx_2);
    if (!__pyx_1) {
      if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 234; goto __pyx_L1;}
      break;
    }
    Py_DECREF(__pyx_v_handle);
    __pyx_v_handle = __pyx_1;
    __pyx_1 = 0;
    __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 235; goto __pyx_L1;}
    __pyx_3 = PyObject_GetAttr(__pyx_1, __pyx_n_UnhookEvent); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 235; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 235; goto __pyx_L1;}
    Py_INCREF(__pyx_v_handle);
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_handle);
    __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 235; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
  }
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("messaging.__UnhookMessagingEvents");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_handle);
  return __pyx_r;
}

static PyObject *__pyx_f_9messaging_OnMirPyClose(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9messaging_OnMirPyClose(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":238 */
  if (__Pyx_PrintItem(__pyx_k50p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 238; goto __pyx_L1;}
  if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 238; goto __pyx_L1;}

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":239 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n___UnhookMessagingEvents); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 239; goto __pyx_L1;}
  __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 239; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("messaging.OnMirPyClose");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static struct PyMethodDef __pyx_methods[] = {
  {"ShowMessageWindow", (PyCFunction)__pyx_f_9messaging_ShowMessageWindow, METH_VARARGS|METH_KEYWORDS, __pyx_doc_9messaging_ShowMessageWindow},
  {"GetMessageWindowApi", (PyCFunction)__pyx_f_9messaging_GetMessageWindowApi, METH_VARARGS|METH_KEYWORDS, __pyx_doc_9messaging_GetMessageWindowApi},
  {"GetMessageWindowClass", (PyCFunction)__pyx_f_9messaging_GetMessageWindowClass, METH_VARARGS|METH_KEYWORDS, __pyx_doc_9messaging_GetMessageWindowClass},
  {"SendMessage", (PyCFunction)__pyx_f_9messaging_SendMessage, METH_VARARGS|METH_KEYWORDS, __pyx_doc_9messaging_SendMessage},
  {"SetStatusMessage", (PyCFunction)__pyx_f_9messaging_SetStatusMessage, METH_VARARGS|METH_KEYWORDS, __pyx_doc_9messaging_SetStatusMessage},
  {"__CallEventCallbacks", (PyCFunction)__pyx_f_9messaging___CallEventCallbacks, METH_VARARGS|METH_KEYWORDS, 0},
  {"HookMessagingEvent", (PyCFunction)__pyx_f_9messaging_HookMessagingEvent, METH_VARARGS|METH_KEYWORDS, __pyx_doc_9messaging_HookMessagingEvent},
  {"UnhookMessagingEvent", (PyCFunction)__pyx_f_9messaging_UnhookMessagingEvent, METH_VARARGS|METH_KEYWORDS, __pyx_doc_9messaging_UnhookMessagingEvent},
  {"__HookMessagingEvents", (PyCFunction)__pyx_f_9messaging___HookMessagingEvents, METH_VARARGS|METH_KEYWORDS, 0},
  {"__UnhookMessagingEvents", (PyCFunction)__pyx_f_9messaging___UnhookMessagingEvents, METH_VARARGS|METH_KEYWORDS, 0},
  {"OnMirPyClose", (PyCFunction)__pyx_f_9messaging_OnMirPyClose, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initmessaging(void); /*proto*/
PyMODINIT_FUNC initmessaging(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("messaging", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":9 */
  __pyx_1 = __Pyx_Import(__pyx_n_time, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_time, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":10 */
  __pyx_1 = __Pyx_Import(__pyx_n_threading, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_threading, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":12 */
  __pyx_1 = __Pyx_Import(__pyx_n_MirPy, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_MirPy, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":13 */
  __pyx_1 = __Pyx_Import(__pyx_n_database, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_database, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":21 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_threading); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 21; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_RLock); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 21; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 21; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n___messagingLock, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 21; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":23 */
  __pyx_2 = PyDict_New(); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; goto __pyx_L1;}
  __pyx_1 = PyTuple_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; goto __pyx_L1;}
  if (PyDict_SetItemString(__pyx_2, "__doc__", __pyx_k54p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; goto __pyx_L1;}
  __pyx_3 = __Pyx_CreateClass(__pyx_1, __pyx_2, __pyx_n_WindowEvent, "messaging"); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyCFunction_New(&__pyx_mdef_9messaging_11WindowEvent___init__, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_1, 0, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n___init__, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n_WindowEvent, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":76 */
  __pyx_1 = PyDict_New(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  Py_INCREF(PyExc_Exception);
  PyTuple_SET_ITEM(__pyx_4, 0, PyExc_Exception);
  __pyx_3 = __Pyx_CreateClass(__pyx_4, __pyx_1, __pyx_n_MessageNotSentException, "messaging"); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n_MessageNotSentException, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":78 */
  __pyx_2 = PyDict_New(); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_acks, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":94 */
  __pyx_d1 = NULL;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":134 */
  __pyx_4 = PyDict_New(); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_HookedMessagingEvents, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":135 */
  __pyx_3 = PyDict_New(); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_HookedMessagingEventsCallbacks, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\messaging\pyrex\messaging.pyx":241 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n___HookMessagingEvents); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 241; goto __pyx_L1;}
  __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 241; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("messaging");
}

static char *__pyx_filenames[] = {
  "messaging.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_WriteUnraisable(char *name) {
    PyObject *old_exc, *old_val, *old_tb;
    PyObject *ctx;
    PyErr_Fetch(&old_exc, &old_val, &old_tb);
    ctx = PyString_FromString(name);
    PyErr_Restore(old_exc, old_val, old_tb);
    if (!ctx)
        ctx = Py_None;
    PyErr_WriteUnraisable(ctx);
}

static int __Pyx_GetException(PyObject **type, PyObject **value, PyObject **tb) {
    PyThreadState *tstate = PyThreadState_Get();
    PyErr_Fetch(type, value, tb);
    PyErr_NormalizeException(type, value, tb);
    if (PyErr_Occurred())
        goto bad;
    Py_INCREF(*type);
    Py_INCREF(*value);
    Py_INCREF(*tb);
    Py_XDECREF(tstate->exc_type);
    Py_XDECREF(tstate->exc_value);
    Py_XDECREF(tstate->exc_traceback);
    tstate->exc_type = *type;
    tstate->exc_value = *value;
    tstate->exc_traceback = *tb;
    return 0;
bad:
    Py_XDECREF(*type);
    Py_XDECREF(*value);
    Py_XDECREF(*tb);
    return -1;
}

static PyObject *__Pyx_GetStdout(void) {
    PyObject *f = PySys_GetObject("stdout");
    if (!f) {
        PyErr_SetString(PyExc_RuntimeError, "lost sys.stdout");
    }
    return f;
}

static int __Pyx_PrintItem(PyObject *v) {
    PyObject *f;
    
    if (!(f = __Pyx_GetStdout()))
        return -1;
    if (PyFile_SoftSpace(f, 1)) {
        if (PyFile_WriteString(" ", f) < 0)
            return -1;
    }
    if (PyFile_WriteObject(v, f, Py_PRINT_RAW) < 0)
        return -1;
    if (PyString_Check(v)) {
        char *s = PyString_AsString(v);
        Py_ssize_t len = PyString_Size(v);
        if (len > 0 &&
            isspace(Py_CHARMASK(s[len-1])) &&
            s[len-1] != ' ')
                PyFile_SoftSpace(f, 0);
    }
    return 0;
}

static int __Pyx_PrintNewline(void) {
    PyObject *f;
    
    if (!(f = __Pyx_GetStdout()))
        return -1;
    if (PyFile_WriteString("\n", f) < 0)
        return -1;
    PyFile_SoftSpace(f, 0);
    return 0;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    #if PY_VERSION_HEX < 0x02050000
    if (!PyClass_Check(type))
    #else
    if (!PyType_Check(type))
    #endif
    {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        #if PY_VERSION_HEX < 0x02050000
            if (PyInstance_Check(type)) {
                type = (PyObject*) ((PyInstanceObject*)type)->in_class;
                Py_INCREF(type);
            }
            else {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception must be an old-style class or instance");
                goto raise_error;
            }
        #else
            type = (PyObject*) type->ob_type;
            Py_INCREF(type);
            if (!PyType_IsSubtype((PyTypeObject *)type, (PyTypeObject *)PyExc_BaseException)) {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception class must be a subclass of BaseException");
                goto raise_error;
            }
        #endif
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        if (t->i)
            PyString_InternInPlace(t->p);
        ++t;
    }
    return 0;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_CreateClass(
    PyObject *bases, PyObject *dict, PyObject *name, char *modname)
{
    PyObject *py_modname;
    PyObject *result = 0;
    
    py_modname = PyString_FromString(modname);
    if (!py_modname)
        goto bad;
    if (PyDict_SetItemString(dict, "__module__", py_modname) < 0)
        goto bad;
    result = PyClass_New(bases, dict, name);
bad:
    Py_XDECREF(py_modname);
    return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
