/* Generated by Pyrex 0.9.8.5 on Thu Oct 30 10:45:46 2008 */

#define PY_SSIZE_T_CLEAN
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "string.h"
#include "m_icq.h"


typedef struct {PyObject **p; int i; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static int __Pyx_GetException(PyObject **type, PyObject **value, PyObject **tb); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from status */


/* Declarations from implementation of status */

typedef unsigned char __pyx_t_6status_BYTE;

typedef unsigned long __pyx_t_6status_DWORD;

typedef unsigned short __pyx_t_6status_WORD;

typedef unsigned short __pyx_t_6status_WCHAR;

typedef __pyx_t_6status_BYTE *__pyx_t_6status_PBYTE;

typedef void *__pyx_t_6status_HANDLE;

typedef int (*__pyx_t_6status_MIRANDAHOOK)(long,long);


static char __pyx_k1[] = "";
static char __pyx_k2[] = "upper";
static char __pyx_k3[] = "MirPy";
static char __pyx_k4[] = "CallService";
static char __pyx_k5[] = "ServiceNotFoundError";
static char __pyx_k6[] = "ProtocolNotFoundError";
static char __pyx_k7[] = "Protocol '";
static char __pyx_k8[] = "' was not found.";
static char __pyx_k9[] = "CallProtocolService";
static char __pyx_k10[] = "/GetStatus";
static char __pyx_k11[] = "/SetStatus";
static char __pyx_k12[] = "/SetAwayMsg";
static char __pyx_k13[] = "/GetXStatus";
static char __pyx_k14[] = "/SetXStatus";
static char __pyx_k15[] = "/GetXStatusEx";
static char __pyx_k16[] = "ExtendedStatus";
static char __pyx_k17[] = "flags";
static char __pyx_k18[] = "wParam";
static char __pyx_k19[] = "lParam";
static char __pyx_k20[] = "status";
static char __pyx_k21[] = "name";
static char __pyx_k22[] = "message";
static char __pyx_k23[] = "/SetXStatusEx";
static char __pyx_k24[] = "STATUS_CONNECTING";
static char __pyx_k25[] = "STATUS_OFFLINE";
static char __pyx_k26[] = "STATUS_ONLINE";
static char __pyx_k27[] = "STATUS_AWAY";
static char __pyx_k28[] = "STATUS_DND";
static char __pyx_k29[] = "STATUS_NA";
static char __pyx_k30[] = "STATUS_OCCUPIED";
static char __pyx_k31[] = "STATUS_FREECHAT";
static char __pyx_k32[] = "STATUS_INVISILE";
static char __pyx_k33[] = "STATUS_ONTHEPHONE";
static char __pyx_k34[] = "STATUS_OUTTOLUNCH";
static char __pyx_k35[] = "STATUS_IDLE";
static char __pyx_k36[] = "Contains information about an extended status.\n	flags     - status flags\n	status    - actual extended status\n	name      - status name\n	message   - status message\n	wParam    - extra data - currently not used\n	lParam    - extra data - currently not used  \n	";
static char __pyx_k37[] = "__init__";

static PyObject *__pyx_n_CallProtocolService;
static PyObject *__pyx_n_CallService;
static PyObject *__pyx_n_ExtendedStatus;
static PyObject *__pyx_n_MirPy;
static PyObject *__pyx_n_ProtocolNotFoundError;
static PyObject *__pyx_n_STATUS_AWAY;
static PyObject *__pyx_n_STATUS_CONNECTING;
static PyObject *__pyx_n_STATUS_DND;
static PyObject *__pyx_n_STATUS_FREECHAT;
static PyObject *__pyx_n_STATUS_IDLE;
static PyObject *__pyx_n_STATUS_INVISILE;
static PyObject *__pyx_n_STATUS_NA;
static PyObject *__pyx_n_STATUS_OCCUPIED;
static PyObject *__pyx_n_STATUS_OFFLINE;
static PyObject *__pyx_n_STATUS_ONLINE;
static PyObject *__pyx_n_STATUS_ONTHEPHONE;
static PyObject *__pyx_n_STATUS_OUTTOLUNCH;
static PyObject *__pyx_n_ServiceNotFoundError;
static PyObject *__pyx_n___init__;
static PyObject *__pyx_n_flags;
static PyObject *__pyx_n_lParam;
static PyObject *__pyx_n_message;
static PyObject *__pyx_n_name;
static PyObject *__pyx_n_status;
static PyObject *__pyx_n_upper;
static PyObject *__pyx_n_wParam;

static PyObject *__pyx_k1p;
static PyObject *__pyx_k7p;
static PyObject *__pyx_k8p;
static PyObject *__pyx_k10p;
static PyObject *__pyx_k11p;
static PyObject *__pyx_k12p;
static PyObject *__pyx_k13p;
static PyObject *__pyx_k14p;
static PyObject *__pyx_k15p;
static PyObject *__pyx_k23p;
static PyObject *__pyx_k36p;

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_n_CallProtocolService, 1, __pyx_k9, sizeof(__pyx_k9)},
  {&__pyx_n_CallService, 1, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_n_ExtendedStatus, 1, __pyx_k16, sizeof(__pyx_k16)},
  {&__pyx_n_MirPy, 1, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_n_ProtocolNotFoundError, 1, __pyx_k6, sizeof(__pyx_k6)},
  {&__pyx_n_STATUS_AWAY, 1, __pyx_k27, sizeof(__pyx_k27)},
  {&__pyx_n_STATUS_CONNECTING, 1, __pyx_k24, sizeof(__pyx_k24)},
  {&__pyx_n_STATUS_DND, 1, __pyx_k28, sizeof(__pyx_k28)},
  {&__pyx_n_STATUS_FREECHAT, 1, __pyx_k31, sizeof(__pyx_k31)},
  {&__pyx_n_STATUS_IDLE, 1, __pyx_k35, sizeof(__pyx_k35)},
  {&__pyx_n_STATUS_INVISILE, 1, __pyx_k32, sizeof(__pyx_k32)},
  {&__pyx_n_STATUS_NA, 1, __pyx_k29, sizeof(__pyx_k29)},
  {&__pyx_n_STATUS_OCCUPIED, 1, __pyx_k30, sizeof(__pyx_k30)},
  {&__pyx_n_STATUS_OFFLINE, 1, __pyx_k25, sizeof(__pyx_k25)},
  {&__pyx_n_STATUS_ONLINE, 1, __pyx_k26, sizeof(__pyx_k26)},
  {&__pyx_n_STATUS_ONTHEPHONE, 1, __pyx_k33, sizeof(__pyx_k33)},
  {&__pyx_n_STATUS_OUTTOLUNCH, 1, __pyx_k34, sizeof(__pyx_k34)},
  {&__pyx_n_ServiceNotFoundError, 1, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_n___init__, 1, __pyx_k37, sizeof(__pyx_k37)},
  {&__pyx_n_flags, 1, __pyx_k17, sizeof(__pyx_k17)},
  {&__pyx_n_lParam, 1, __pyx_k19, sizeof(__pyx_k19)},
  {&__pyx_n_message, 1, __pyx_k22, sizeof(__pyx_k22)},
  {&__pyx_n_name, 1, __pyx_k21, sizeof(__pyx_k21)},
  {&__pyx_n_status, 1, __pyx_k20, sizeof(__pyx_k20)},
  {&__pyx_n_upper, 1, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_n_wParam, 1, __pyx_k18, sizeof(__pyx_k18)},
  {&__pyx_k1p, 0, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_k7p, 0, __pyx_k7, sizeof(__pyx_k7)},
  {&__pyx_k8p, 0, __pyx_k8, sizeof(__pyx_k8)},
  {&__pyx_k10p, 0, __pyx_k10, sizeof(__pyx_k10)},
  {&__pyx_k11p, 0, __pyx_k11, sizeof(__pyx_k11)},
  {&__pyx_k12p, 0, __pyx_k12, sizeof(__pyx_k12)},
  {&__pyx_k13p, 0, __pyx_k13, sizeof(__pyx_k13)},
  {&__pyx_k14p, 0, __pyx_k14, sizeof(__pyx_k14)},
  {&__pyx_k15p, 0, __pyx_k15, sizeof(__pyx_k15)},
  {&__pyx_k23p, 0, __pyx_k23, sizeof(__pyx_k23)},
  {&__pyx_k36p, 0, __pyx_k36, sizeof(__pyx_k36)},
  {0, 0, 0, 0}
};



/* Implementation of status */

static PyObject *__pyx_f_6status_14ExtendedStatus___init__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyMethodDef __pyx_mdef_6status_14ExtendedStatus___init__ = {"__init__", (PyCFunction)__pyx_f_6status_14ExtendedStatus___init__, METH_VARARGS|METH_KEYWORDS, 0};
static PyObject *__pyx_f_6status_14ExtendedStatus___init__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_flags;
  PyObject *__pyx_v_status;
  PyObject *__pyx_v_name;
  PyObject *__pyx_v_message;
  PyObject *__pyx_v_wParam;
  PyObject *__pyx_v_lParam;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"self",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_self)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_flags = Py_None; Py_INCREF(Py_None);
  __pyx_v_status = Py_None; Py_INCREF(Py_None);
  __pyx_v_name = Py_None; Py_INCREF(Py_None);
  __pyx_v_message = Py_None; Py_INCREF(Py_None);
  __pyx_v_wParam = Py_None; Py_INCREF(Py_None);
  __pyx_v_lParam = Py_None; Py_INCREF(Py_None);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":50 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  Py_DECREF(__pyx_v_flags);
  __pyx_v_flags = __pyx_1;
  __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":51 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; goto __pyx_L1;}
  Py_DECREF(__pyx_v_status);
  __pyx_v_status = __pyx_1;
  __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":52 */
  Py_INCREF(__pyx_k1p);
  Py_DECREF(__pyx_v_name);
  __pyx_v_name = __pyx_k1p;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":53 */
  Py_INCREF(__pyx_k1p);
  Py_DECREF(__pyx_v_message);
  __pyx_v_message = __pyx_k1p;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":54 */
  Py_INCREF(Py_None);
  Py_DECREF(__pyx_v_wParam);
  __pyx_v_wParam = Py_None;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":55 */
  Py_INCREF(Py_None);
  Py_DECREF(__pyx_v_lParam);
  __pyx_v_lParam = Py_None;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("status.ExtendedStatus.__init__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_flags);
  Py_DECREF(__pyx_v_status);
  Py_DECREF(__pyx_v_name);
  Py_DECREF(__pyx_v_message);
  Py_DECREF(__pyx_v_wParam);
  Py_DECREF(__pyx_v_lParam);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_6status_CallProtocolService(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6status_CallProtocolService(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char *__pyx_v_protocol;
  char *__pyx_v_service;
  long __pyx_v_wParam;
  long __pyx_v_lParam;
  char __pyx_v_buffer[512];
  PyObject *__pyx_v_upper;
  PyObject *__pyx_v_res;
  PyObject *__pyx_v_e;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  char *__pyx_3;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  int __pyx_7;
  PyObject *__pyx_8 = 0;
  static char *__pyx_argnames[] = {"protocol","service","wParam","lParam",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "ssll", __pyx_argnames, &__pyx_v_protocol, &__pyx_v_service, &__pyx_v_wParam, &__pyx_v_lParam)) return 0;
  __pyx_v_upper = Py_None; Py_INCREF(Py_None);
  __pyx_v_res = Py_None; Py_INCREF(Py_None);
  __pyx_v_e = Py_None; Py_INCREF(Py_None);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":61 */
  __pyx_1 = PyString_FromString(__pyx_v_protocol); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_upper); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_v_upper);
  __pyx_v_upper = __pyx_1;
  __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":62 */
  __pyx_3 = PyString_AsString(__pyx_v_upper); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L1;}
  strcpy(__pyx_v_buffer,__pyx_3);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":63 */
  strcat(__pyx_v_buffer,__pyx_v_service);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":64 */
  __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
  Py_DECREF(__pyx_v_res);
  __pyx_v_res = __pyx_2;
  __pyx_2 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":65 */
  /*try:*/ {
    __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L2;}
    __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_CallService); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L2;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_1 = PyString_FromString(__pyx_v_buffer); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L2;}
    __pyx_4 = PyInt_FromLong(__pyx_v_wParam); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L2;}
    __pyx_5 = PyInt_FromLong(__pyx_v_lParam); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L2;}
    __pyx_6 = PyTuple_New(3); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L2;}
    PyTuple_SET_ITEM(__pyx_6, 0, __pyx_1);
    PyTuple_SET_ITEM(__pyx_6, 1, __pyx_4);
    PyTuple_SET_ITEM(__pyx_6, 2, __pyx_5);
    __pyx_1 = 0;
    __pyx_4 = 0;
    __pyx_5 = 0;
    __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_6); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L2;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    Py_DECREF(__pyx_v_res);
    __pyx_v_res = __pyx_1;
    __pyx_1 = 0;
  }
  goto __pyx_L3;
  __pyx_L2:;
  Py_XDECREF(__pyx_4); __pyx_4 = 0;
  Py_XDECREF(__pyx_5); __pyx_5 = 0;
  Py_XDECREF(__pyx_2); __pyx_2 = 0;
  Py_XDECREF(__pyx_6); __pyx_6 = 0;
  Py_XDECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":67 */
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; goto __pyx_L1;}
  __pyx_5 = PyObject_GetAttr(__pyx_4, __pyx_n_ServiceNotFoundError); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_7 = PyErr_ExceptionMatches(__pyx_5);
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  if (__pyx_7) {
    __Pyx_AddTraceback("status.CallProtocolService");
    if (__Pyx_GetException(&__pyx_2, &__pyx_6, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; goto __pyx_L1;}
    Py_INCREF(__pyx_6);
    Py_DECREF(__pyx_v_e);
    __pyx_v_e = __pyx_6;
    __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_ProtocolNotFoundError); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
    __pyx_5 = PyNumber_Add(__pyx_k7p, __pyx_v_upper); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
    __pyx_8 = PyNumber_Add(__pyx_5, __pyx_k8p); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_5 = PyTuple_New(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_5, 0, __pyx_8);
    __pyx_8 = 0;
    __pyx_8 = PyObject_CallObject(__pyx_4, __pyx_5); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __Pyx_Raise(__pyx_8, 0, 0);
    Py_DECREF(__pyx_8); __pyx_8 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    goto __pyx_L3;
  }
  goto __pyx_L1;
  __pyx_L3:;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":69 */
  Py_INCREF(__pyx_v_res);
  __pyx_r = __pyx_v_res;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_8);
  __Pyx_AddTraceback("status.CallProtocolService");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_upper);
  Py_DECREF(__pyx_v_res);
  Py_DECREF(__pyx_v_e);
  return __pyx_r;
}

static PyObject *__pyx_f_6status_GetStatus(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6status_GetStatus[] = "GetStatus(protocol)\n	Returns the status of the given protocol. Returns one of the status.STATUS_* constants.\n	";
static PyObject *__pyx_f_6status_GetStatus(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char *__pyx_v_protocol;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"protocol",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "s", __pyx_argnames, &__pyx_v_protocol)) return 0;
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_CallProtocolService); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
  __pyx_2 = PyString_FromString(__pyx_v_protocol); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
  __pyx_4 = PyInt_FromLong(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_2);
  Py_INCREF(__pyx_k10p);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_k10p);
  PyTuple_SET_ITEM(__pyx_5, 2, __pyx_3);
  PyTuple_SET_ITEM(__pyx_5, 3, __pyx_4);
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_4 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_5); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("status.GetStatus");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static PyObject *__pyx_f_6status_SetStatus(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6status_SetStatus[] = "SetStatus(protocol mode)\n	Sets the protocol status to mode.\n	Returns 0 on success, nonzero on failure\n	";
static PyObject *__pyx_f_6status_SetStatus(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char *__pyx_v_protocol;
  long __pyx_v_mode;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"protocol","mode",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "sl", __pyx_argnames, &__pyx_v_protocol, &__pyx_v_mode)) return 0;
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_CallProtocolService); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  __pyx_2 = PyString_FromString(__pyx_v_protocol); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_v_mode); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  __pyx_4 = PyInt_FromLong(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_2);
  Py_INCREF(__pyx_k11p);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_k11p);
  PyTuple_SET_ITEM(__pyx_5, 2, __pyx_3);
  PyTuple_SET_ITEM(__pyx_5, 3, __pyx_4);
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_4 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_5); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("status.SetStatus");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static PyObject *__pyx_f_6status_SetStatusMessage(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6status_SetStatusMessage[] = "SetStatusMessage(protocol, mode, statusMessage)\n	Changes the status and status message for a protocol.\n	Returns 0 on success, nonzero on failure. \n	";
static PyObject *__pyx_f_6status_SetStatusMessage(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char *__pyx_v_protocol;
  long __pyx_v_mode;
  char *__pyx_v_statusMessage;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"protocol","mode","statusMessage",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "sls", __pyx_argnames, &__pyx_v_protocol, &__pyx_v_mode, &__pyx_v_statusMessage)) return 0;
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_CallProtocolService); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
  __pyx_2 = PyString_FromString(__pyx_v_protocol); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_v_mode); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
  __pyx_4 = PyInt_FromLong(((long)__pyx_v_statusMessage)); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_2);
  Py_INCREF(__pyx_k12p);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_k12p);
  PyTuple_SET_ITEM(__pyx_5, 2, __pyx_3);
  PyTuple_SET_ITEM(__pyx_5, 3, __pyx_4);
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_4 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_5); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("status.SetStatusMessage");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static PyObject *__pyx_f_6status_GetXStatus(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6status_GetXStatus[] = "GetXStatus(protocol)\n	Returns the extended status mode (valid values are 1 to 32).\n	";
static PyObject *__pyx_f_6status_GetXStatus(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char *__pyx_v_protocol;
  char *__pyx_v_title;
  char *__pyx_v_msg;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"protocol",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "s", __pyx_argnames, &__pyx_v_protocol)) return 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":97 */
  __pyx_v_title = NULL;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":98 */
  __pyx_v_msg = NULL;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":99 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_CallProtocolService); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
  __pyx_2 = PyString_FromString(__pyx_v_protocol); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(((long)(&__pyx_v_title))); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
  __pyx_4 = PyInt_FromLong(((long)(&__pyx_v_msg))); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_2);
  Py_INCREF(__pyx_k13p);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_k13p);
  PyTuple_SET_ITEM(__pyx_5, 2, __pyx_3);
  PyTuple_SET_ITEM(__pyx_5, 3, __pyx_4);
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_4 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_5); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("status.GetXStatus");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static PyObject *__pyx_f_6status_SetXStatus(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6status_SetXStatus[] = "SetXStatus(protocol, xMode)\n	Sets the protocol extended status to xMode. xMode valid values are from 1 to 32\n	Returns the extended status mode set or 0 on error.\n	";
static PyObject *__pyx_f_6status_SetXStatus(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char *__pyx_v_protocol;
  int __pyx_v_xMode;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"protocol","xMode",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "si", __pyx_argnames, &__pyx_v_protocol, &__pyx_v_xMode)) return 0;
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_CallProtocolService); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
  __pyx_2 = PyString_FromString(__pyx_v_protocol); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_v_xMode); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
  __pyx_4 = PyInt_FromLong(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_2);
  Py_INCREF(__pyx_k14p);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_k14p);
  PyTuple_SET_ITEM(__pyx_5, 2, __pyx_3);
  PyTuple_SET_ITEM(__pyx_5, 3, __pyx_4);
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_4 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_5); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("status.SetXStatus");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static PyObject *__pyx_f_6status_GetXStatusEx(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6status_GetXStatusEx[] = "GetXStatusEx(protocol, hContact)\n	Returns the current extended status. Return value is of type ExtendedStatus.\n	";
static PyObject *__pyx_f_6status_GetXStatusEx(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char *__pyx_v_protocol;
  long __pyx_v_hContact;
  ICQ_CUSTOM_STATUS __pyx_v_ext;
  int __pyx_v_tmpStatus;
  char __pyx_v_name[2048];
  char __pyx_v_message[2048];
  PyObject *__pyx_v_wParam;
  PyObject *__pyx_v_lParam;
  PyObject *__pyx_v_xStatus;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"protocol","hContact",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "sl", __pyx_argnames, &__pyx_v_protocol, &__pyx_v_hContact)) return 0;
  __pyx_v_wParam = Py_None; Py_INCREF(Py_None);
  __pyx_v_lParam = Py_None; Py_INCREF(Py_None);
  __pyx_v_xStatus = Py_None; Py_INCREF(Py_None);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":117 */
  (__pyx_v_name[0]) = 0;
  (__pyx_v_message[0]) = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":119 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
  Py_DECREF(__pyx_v_wParam);
  __pyx_v_wParam = __pyx_1;
  __pyx_1 = 0;
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
  Py_DECREF(__pyx_v_lParam);
  __pyx_v_lParam = __pyx_1;
  __pyx_1 = 0;
  __pyx_v_tmpStatus = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":120 */
  __pyx_v_ext.cbSize = (sizeof(ICQ_CUSTOM_STATUS));

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":121 */
  __pyx_v_ext.flags = 7;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":122 */
  __pyx_v_ext.wParam = NULL;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":123 */
  __pyx_v_ext.lParam = NULL;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":124 */
  __pyx_v_ext.status = (&__pyx_v_tmpStatus);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":125 */
  __pyx_v_ext.pszName = __pyx_v_name;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":126 */
  __pyx_v_ext.pszMessage = __pyx_v_message;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":128 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_CallProtocolService); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 128; goto __pyx_L1;}
  __pyx_2 = PyString_FromString(__pyx_v_protocol); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 128; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_v_hContact); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 128; goto __pyx_L1;}
  __pyx_4 = PyInt_FromLong(((long)(&__pyx_v_ext))); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 128; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 128; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_2);
  Py_INCREF(__pyx_k15p);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_k15p);
  PyTuple_SET_ITEM(__pyx_5, 2, __pyx_3);
  PyTuple_SET_ITEM(__pyx_5, 3, __pyx_4);
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_4 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_5); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 128; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":129 */
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_ExtendedStatus); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
  __pyx_4 = PyObject_CallObject(__pyx_3, 0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_v_xStatus);
  __pyx_v_xStatus = __pyx_4;
  __pyx_4 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":130 */
  __pyx_1 = PyInt_FromLong(__pyx_v_ext.flags); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 130; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_xStatus, __pyx_n_flags, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 130; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":131 */
  if (PyObject_SetAttr(__pyx_v_xStatus, __pyx_n_wParam, Py_None) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":132 */
  if (PyObject_SetAttr(__pyx_v_xStatus, __pyx_n_lParam, Py_None) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 132; goto __pyx_L1;}

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":133 */
  __pyx_5 = PyInt_FromLong(__pyx_v_tmpStatus); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_xStatus, __pyx_n_status, __pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":134 */
  __pyx_2 = PyString_FromString(__pyx_v_name); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_xStatus, __pyx_n_name, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":135 */
  __pyx_3 = PyString_FromString(__pyx_v_message); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_xStatus, __pyx_n_message, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":137 */
  Py_INCREF(__pyx_v_xStatus);
  __pyx_r = __pyx_v_xStatus;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("status.GetXStatusEx");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_wParam);
  Py_DECREF(__pyx_v_lParam);
  Py_DECREF(__pyx_v_xStatus);
  return __pyx_r;
}

static PyObject *__pyx_f_6status_SetXStatusEx(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6status_SetXStatusEx[] = "SetXStatusEx(protocol, xMode, name, statusMessage)\n	Changes the extended status to xMode. \'xName\' is the name of the extended status and \'xMessage\' is the status message. \n	";
static PyObject *__pyx_f_6status_SetXStatusEx(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char *__pyx_v_protocol;
  PyObject *__pyx_v_xMode = 0;
  PyObject *__pyx_v_xName = 0;
  PyObject *__pyx_v_xMessage = 0;
  ICQ_CUSTOM_STATUS __pyx_v_ext;
  int __pyx_v_tmpStatus;
  PyObject *__pyx_r;
  int __pyx_1;
  char *__pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  static char *__pyx_argnames[] = {"protocol","xMode","xName","xMessage",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "sOOO", __pyx_argnames, &__pyx_v_protocol, &__pyx_v_xMode, &__pyx_v_xName, &__pyx_v_xMessage)) return 0;
  Py_INCREF(__pyx_v_xMode);
  Py_INCREF(__pyx_v_xName);
  Py_INCREF(__pyx_v_xMessage);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":146 */
  __pyx_1 = PyInt_AsLong(__pyx_v_xMode); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 146; goto __pyx_L1;}
  __pyx_v_tmpStatus = __pyx_1;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":147 */
  __pyx_v_ext.cbSize = (sizeof(ICQ_CUSTOM_STATUS));

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":148 */
  __pyx_v_ext.flags = 7;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":149 */
  __pyx_v_ext.wParam = NULL;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":150 */
  __pyx_v_ext.lParam = NULL;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":151 */
  __pyx_v_ext.status = (&__pyx_v_tmpStatus);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":152 */
  __pyx_2 = PyString_AsString(__pyx_v_xName); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
  __pyx_v_ext.pszName = __pyx_2;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":153 */
  __pyx_2 = PyString_AsString(__pyx_v_xMessage); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 153; goto __pyx_L1;}
  __pyx_v_ext.pszMessage = __pyx_2;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":155 */
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_CallProtocolService); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 155; goto __pyx_L1;}
  __pyx_4 = PyString_FromString(__pyx_v_protocol); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 155; goto __pyx_L1;}
  __pyx_5 = PyInt_FromLong(0); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 155; goto __pyx_L1;}
  __pyx_6 = PyInt_FromLong(((long)(&__pyx_v_ext))); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 155; goto __pyx_L1;}
  __pyx_7 = PyTuple_New(4); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 155; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_7, 0, __pyx_4);
  Py_INCREF(__pyx_k23p);
  PyTuple_SET_ITEM(__pyx_7, 1, __pyx_k23p);
  PyTuple_SET_ITEM(__pyx_7, 2, __pyx_5);
  PyTuple_SET_ITEM(__pyx_7, 3, __pyx_6);
  __pyx_4 = 0;
  __pyx_5 = 0;
  __pyx_6 = 0;
  __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_7); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 155; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_7); __pyx_7 = 0;
  __pyx_r = __pyx_4;
  __pyx_4 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  __Pyx_AddTraceback("status.SetXStatusEx");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_xMode);
  Py_DECREF(__pyx_v_xName);
  Py_DECREF(__pyx_v_xMessage);
  return __pyx_r;
}

static struct PyMethodDef __pyx_methods[] = {
  {"CallProtocolService", (PyCFunction)__pyx_f_6status_CallProtocolService, METH_VARARGS|METH_KEYWORDS, 0},
  {"GetStatus", (PyCFunction)__pyx_f_6status_GetStatus, METH_VARARGS|METH_KEYWORDS, __pyx_doc_6status_GetStatus},
  {"SetStatus", (PyCFunction)__pyx_f_6status_SetStatus, METH_VARARGS|METH_KEYWORDS, __pyx_doc_6status_SetStatus},
  {"SetStatusMessage", (PyCFunction)__pyx_f_6status_SetStatusMessage, METH_VARARGS|METH_KEYWORDS, __pyx_doc_6status_SetStatusMessage},
  {"GetXStatus", (PyCFunction)__pyx_f_6status_GetXStatus, METH_VARARGS|METH_KEYWORDS, __pyx_doc_6status_GetXStatus},
  {"SetXStatus", (PyCFunction)__pyx_f_6status_SetXStatus, METH_VARARGS|METH_KEYWORDS, __pyx_doc_6status_SetXStatus},
  {"GetXStatusEx", (PyCFunction)__pyx_f_6status_GetXStatusEx, METH_VARARGS|METH_KEYWORDS, __pyx_doc_6status_GetXStatusEx},
  {"SetXStatusEx", (PyCFunction)__pyx_f_6status_SetXStatusEx, METH_VARARGS|METH_KEYWORDS, __pyx_doc_6status_SetXStatusEx},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initstatus(void); /*proto*/
PyMODINIT_FUNC initstatus(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("status", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":9 */
  __pyx_1 = __Pyx_Import(__pyx_n_MirPy, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_MirPy, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":13 */
  __pyx_1 = PyInt_FromLong(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_STATUS_CONNECTING, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":14 */
  __pyx_1 = PyInt_FromLong(40071); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 14; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_STATUS_OFFLINE, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 14; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":15 */
  __pyx_1 = PyInt_FromLong(40072); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_STATUS_ONLINE, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":16 */
  __pyx_1 = PyInt_FromLong(40073); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_STATUS_AWAY, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":17 */
  __pyx_1 = PyInt_FromLong(40074); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_STATUS_DND, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":18 */
  __pyx_1 = PyInt_FromLong(40075); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_STATUS_NA, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":19 */
  __pyx_1 = PyInt_FromLong(40076); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_STATUS_OCCUPIED, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":20 */
  __pyx_1 = PyInt_FromLong(40077); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_STATUS_FREECHAT, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":21 */
  __pyx_1 = PyInt_FromLong(40078); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 21; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_STATUS_INVISILE, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 21; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":22 */
  __pyx_1 = PyInt_FromLong(40079); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 22; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_STATUS_ONTHEPHONE, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 22; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":23 */
  __pyx_1 = PyInt_FromLong(40080); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_STATUS_OUTTOLUNCH, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":24 */
  __pyx_1 = PyInt_FromLong(40081); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_STATUS_IDLE, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":40 */
  __pyx_1 = PyDict_New(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  if (PyDict_SetItemString(__pyx_1, "__doc__", __pyx_k36p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  __pyx_3 = __Pyx_CreateClass(__pyx_2, __pyx_1, __pyx_n_ExtendedStatus, "status"); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyCFunction_New(&__pyx_mdef_6status_14ExtendedStatus___init__, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_2, 0, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n___init__, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n_ExtendedStatus, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":57 */
  __pyx_2 = PyDict_New(); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
  Py_INCREF(PyExc_Exception);
  PyTuple_SET_ITEM(__pyx_4, 0, PyExc_Exception);
  __pyx_3 = __Pyx_CreateClass(__pyx_4, __pyx_2, __pyx_n_ProtocolNotFoundError, "status"); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n_ProtocolNotFoundError, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\status\pyrex\status.pyx":139 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("status");
}

static char *__pyx_filenames[] = {
  "status.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static int __Pyx_GetException(PyObject **type, PyObject **value, PyObject **tb) {
    PyThreadState *tstate = PyThreadState_Get();
    PyErr_Fetch(type, value, tb);
    PyErr_NormalizeException(type, value, tb);
    if (PyErr_Occurred())
        goto bad;
    Py_INCREF(*type);
    Py_INCREF(*value);
    Py_INCREF(*tb);
    Py_XDECREF(tstate->exc_type);
    Py_XDECREF(tstate->exc_value);
    Py_XDECREF(tstate->exc_traceback);
    tstate->exc_type = *type;
    tstate->exc_value = *value;
    tstate->exc_traceback = *tb;
    return 0;
bad:
    Py_XDECREF(*type);
    Py_XDECREF(*value);
    Py_XDECREF(*tb);
    return -1;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    #if PY_VERSION_HEX < 0x02050000
    if (!PyClass_Check(type))
    #else
    if (!PyType_Check(type))
    #endif
    {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        #if PY_VERSION_HEX < 0x02050000
            if (PyInstance_Check(type)) {
                type = (PyObject*) ((PyInstanceObject*)type)->in_class;
                Py_INCREF(type);
            }
            else {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception must be an old-style class or instance");
                goto raise_error;
            }
        #else
            type = (PyObject*) type->ob_type;
            Py_INCREF(type);
            if (!PyType_IsSubtype((PyTypeObject *)type, (PyTypeObject *)PyExc_BaseException)) {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception class must be a subclass of BaseException");
                goto raise_error;
            }
        #endif
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        if (t->i)
            PyString_InternInPlace(t->p);
        ++t;
    }
    return 0;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_CreateClass(
    PyObject *bases, PyObject *dict, PyObject *name, char *modname)
{
    PyObject *py_modname;
    PyObject *result = 0;
    
    py_modname = PyString_FromString(modname);
    if (!py_modname)
        goto bad;
    if (PyDict_SetItemString(dict, "__module__", py_modname) < 0)
        goto bad;
    result = PyClass_New(bases, dict, name);
bad:
    Py_XDECREF(py_modname);
    return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
