/* Generated by Pyrex 0.9.8.5 on Thu Oct 30 10:45:36 2008 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "m_contacts.h"


typedef struct {PyObject **p; int i; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from contacts */


/* Declarations from implementation of contacts */

typedef unsigned char __pyx_t_8contacts_BYTE;

typedef unsigned long __pyx_t_8contacts_DWORD;

typedef unsigned short __pyx_t_8contacts_WORD;

enum  {
  __pyx_e_8contacts_CNF_FIRSTNAME = 1,
  __pyx_e_8contacts_CNF_LASTNAME = 2,
  __pyx_e_8contacts_CNF_NICK = 3,
  __pyx_e_8contacts_CNF_CUSTOMNICK = 4,
  __pyx_e_8contacts_CNF_EMAIL = 5,
  __pyx_e_8contacts_CNF_CITY = 6,
  __pyx_e_8contacts_CNF_STATE = 7,
  __pyx_e_8contacts_CNF_COUNTRY = 8,
  __pyx_e_8contacts_CNF_PHONE = 9,
  __pyx_e_8contacts_CNF_HOMEPAGE = 10,
  __pyx_e_8contacts_CNF_ABOUT = 11,
  __pyx_e_8contacts_CNF_GENDER = 12,
  __pyx_e_8contacts_CNF_AGE = 13,
  __pyx_e_8contacts_CNF_FIRSTLAST = 14,
  __pyx_e_8contacts_CNF_UNIQUEID = 15,
  __pyx_e_8contacts_CNF_DISPLAY = 16,
  __pyx_e_8contacts_CNF_DISPLAYNC = 17,
  __pyx_e_8contacts_CNF_UNICODE = 0x80
};

enum  {
  __pyx_e_8contacts_CNTF_BYTE = 1,
  __pyx_e_8contacts_CNTF_WORD = 2,
  __pyx_e_8contacts_CNTF_DWORD = 3,
  __pyx_e_8contacts_CNTF_ASCIIZ = 4
};

static PyObject *__pyx_f_8contacts_GetInfo(CONTACTINFO,PyObject *); /*proto*/

static char __pyx_k1[] = "";
static char __pyx_k2[] = "MirPy";
static char __pyx_k3[] = "CallService";
static char __pyx_k4[] = "Miranda/Contact/GetContactInfo";
static char __pyx_k5[] = "Contact";
static char __pyx_k6[] = "firstName";
static char __pyx_k7[] = "lastName";
static char __pyx_k8[] = "nick";
static char __pyx_k9[] = "customNick";
static char __pyx_k10[] = "email";
static char __pyx_k11[] = "city";
static char __pyx_k12[] = "state";
static char __pyx_k13[] = "country";
static char __pyx_k14[] = "phone";
static char __pyx_k15[] = "homepage";
static char __pyx_k16[] = "about";
static char __pyx_k17[] = "gender";
static char __pyx_k18[] = "age";
static char __pyx_k19[] = "protocol";
static char __pyx_k20[] = "uniqueID";
static char __pyx_k21[] = "Contains information about a contact\n	firstName   - First name.\n	lastName    - Last name.\n	nick        - Contact\'s nick.\n	customNick  - Contact\'s custom nick, clist nick.\n	email       - Email (string or 0).\n	city        - City (string or 0).\n	state       - State (string or 0).\n	country     - Country (string or 0).\n	phone       - Contact\'s phone (string or 0).\n	homepage    - Contact\'s home page (string or 0).\n	about       - About info (string or 0).\n	gender      - Contact\'s gender (char \'M\', \'F\' or 0)\n	age         - Age (0 means unknown).\n	protocol    - The protocol the contact is on (string or 0).\n	uniqueID    - Contact\'s unique ID (depends on the protocol)\n	";
static char __pyx_k22[] = "__init__";

static PyObject *__pyx_n_CallService;
static PyObject *__pyx_n_Contact;
static PyObject *__pyx_n_MirPy;
static PyObject *__pyx_n___init__;
static PyObject *__pyx_n_about;
static PyObject *__pyx_n_age;
static PyObject *__pyx_n_city;
static PyObject *__pyx_n_country;
static PyObject *__pyx_n_customNick;
static PyObject *__pyx_n_email;
static PyObject *__pyx_n_firstName;
static PyObject *__pyx_n_gender;
static PyObject *__pyx_n_homepage;
static PyObject *__pyx_n_lastName;
static PyObject *__pyx_n_nick;
static PyObject *__pyx_n_phone;
static PyObject *__pyx_n_protocol;
static PyObject *__pyx_n_state;
static PyObject *__pyx_n_uniqueID;

static PyObject *__pyx_k1p;
static PyObject *__pyx_k4p;
static PyObject *__pyx_k21p;

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_n_CallService, 1, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_n_Contact, 1, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_n_MirPy, 1, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_n___init__, 1, __pyx_k22, sizeof(__pyx_k22)},
  {&__pyx_n_about, 1, __pyx_k16, sizeof(__pyx_k16)},
  {&__pyx_n_age, 1, __pyx_k18, sizeof(__pyx_k18)},
  {&__pyx_n_city, 1, __pyx_k11, sizeof(__pyx_k11)},
  {&__pyx_n_country, 1, __pyx_k13, sizeof(__pyx_k13)},
  {&__pyx_n_customNick, 1, __pyx_k9, sizeof(__pyx_k9)},
  {&__pyx_n_email, 1, __pyx_k10, sizeof(__pyx_k10)},
  {&__pyx_n_firstName, 1, __pyx_k6, sizeof(__pyx_k6)},
  {&__pyx_n_gender, 1, __pyx_k17, sizeof(__pyx_k17)},
  {&__pyx_n_homepage, 1, __pyx_k15, sizeof(__pyx_k15)},
  {&__pyx_n_lastName, 1, __pyx_k7, sizeof(__pyx_k7)},
  {&__pyx_n_nick, 1, __pyx_k8, sizeof(__pyx_k8)},
  {&__pyx_n_phone, 1, __pyx_k14, sizeof(__pyx_k14)},
  {&__pyx_n_protocol, 1, __pyx_k19, sizeof(__pyx_k19)},
  {&__pyx_n_state, 1, __pyx_k12, sizeof(__pyx_k12)},
  {&__pyx_n_uniqueID, 1, __pyx_k20, sizeof(__pyx_k20)},
  {&__pyx_k1p, 0, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_k4p, 0, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_k21p, 0, __pyx_k21, sizeof(__pyx_k21)},
  {0, 0, 0, 0}
};



/* Implementation of contacts */

static PyObject *__pyx_f_8contacts_7Contact___init__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyMethodDef __pyx_mdef_8contacts_7Contact___init__ = {"__init__", (PyCFunction)__pyx_f_8contacts_7Contact___init__, METH_VARARGS|METH_KEYWORDS, 0};
static PyObject *__pyx_f_8contacts_7Contact___init__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_firstName;
  PyObject *__pyx_v_lastName;
  PyObject *__pyx_v_nick;
  PyObject *__pyx_v_customNick;
  PyObject *__pyx_v_email;
  PyObject *__pyx_v_city;
  PyObject *__pyx_v_state;
  PyObject *__pyx_v_country;
  PyObject *__pyx_v_phone;
  PyObject *__pyx_v_homepage;
  PyObject *__pyx_v_about;
  PyObject *__pyx_v_gender;
  PyObject *__pyx_v_age;
  PyObject *__pyx_v_protocol;
  PyObject *__pyx_v_uniqueID;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"self",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_self)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_firstName = Py_None; Py_INCREF(Py_None);
  __pyx_v_lastName = Py_None; Py_INCREF(Py_None);
  __pyx_v_nick = Py_None; Py_INCREF(Py_None);
  __pyx_v_customNick = Py_None; Py_INCREF(Py_None);
  __pyx_v_email = Py_None; Py_INCREF(Py_None);
  __pyx_v_city = Py_None; Py_INCREF(Py_None);
  __pyx_v_state = Py_None; Py_INCREF(Py_None);
  __pyx_v_country = Py_None; Py_INCREF(Py_None);
  __pyx_v_phone = Py_None; Py_INCREF(Py_None);
  __pyx_v_homepage = Py_None; Py_INCREF(Py_None);
  __pyx_v_about = Py_None; Py_INCREF(Py_None);
  __pyx_v_gender = Py_None; Py_INCREF(Py_None);
  __pyx_v_age = Py_None; Py_INCREF(Py_None);
  __pyx_v_protocol = Py_None; Py_INCREF(Py_None);
  __pyx_v_uniqueID = Py_None; Py_INCREF(Py_None);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":69 */
  Py_INCREF(__pyx_k1p);
  Py_DECREF(__pyx_v_firstName);
  __pyx_v_firstName = __pyx_k1p;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":70 */
  Py_INCREF(__pyx_k1p);
  Py_DECREF(__pyx_v_lastName);
  __pyx_v_lastName = __pyx_k1p;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":71 */
  Py_INCREF(__pyx_k1p);
  Py_DECREF(__pyx_v_nick);
  __pyx_v_nick = __pyx_k1p;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":72 */
  Py_INCREF(__pyx_k1p);
  Py_DECREF(__pyx_v_customNick);
  __pyx_v_customNick = __pyx_k1p;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":73 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; goto __pyx_L1;}
  Py_DECREF(__pyx_v_email);
  __pyx_v_email = __pyx_1;
  __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":74 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
  Py_DECREF(__pyx_v_city);
  __pyx_v_city = __pyx_1;
  __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":75 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
  Py_DECREF(__pyx_v_state);
  __pyx_v_state = __pyx_1;
  __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":76 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  Py_DECREF(__pyx_v_country);
  __pyx_v_country = __pyx_1;
  __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":77 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
  Py_DECREF(__pyx_v_phone);
  __pyx_v_phone = __pyx_1;
  __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":78 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
  Py_DECREF(__pyx_v_homepage);
  __pyx_v_homepage = __pyx_1;
  __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":79 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; goto __pyx_L1;}
  Py_DECREF(__pyx_v_about);
  __pyx_v_about = __pyx_1;
  __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":80 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  Py_DECREF(__pyx_v_gender);
  __pyx_v_gender = __pyx_1;
  __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":81 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
  Py_DECREF(__pyx_v_age);
  __pyx_v_age = __pyx_1;
  __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":82 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  Py_DECREF(__pyx_v_protocol);
  __pyx_v_protocol = __pyx_1;
  __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":83 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
  Py_DECREF(__pyx_v_uniqueID);
  __pyx_v_uniqueID = __pyx_1;
  __pyx_1 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("contacts.Contact.__init__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_firstName);
  Py_DECREF(__pyx_v_lastName);
  Py_DECREF(__pyx_v_nick);
  Py_DECREF(__pyx_v_customNick);
  Py_DECREF(__pyx_v_email);
  Py_DECREF(__pyx_v_city);
  Py_DECREF(__pyx_v_state);
  Py_DECREF(__pyx_v_country);
  Py_DECREF(__pyx_v_phone);
  Py_DECREF(__pyx_v_homepage);
  Py_DECREF(__pyx_v_about);
  Py_DECREF(__pyx_v_gender);
  Py_DECREF(__pyx_v_age);
  Py_DECREF(__pyx_v_protocol);
  Py_DECREF(__pyx_v_uniqueID);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_8contacts_GetInfo(CONTACTINFO __pyx_v_ctInfo,PyObject *__pyx_v_flag) {
  PyObject *__pyx_r;
  __pyx_t_8contacts_BYTE __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  int __pyx_6;
  Py_INCREF(__pyx_v_flag);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":86 */
  __pyx_1 = PyInt_AsLong(__pyx_v_flag); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  __pyx_v_ctInfo.dwFlag = __pyx_1;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":87 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_n_CallService); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
  __pyx_4 = PyInt_FromLong(((long)(&__pyx_v_ctInfo))); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
  Py_INCREF(__pyx_k4p);
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_k4p);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_2);
  PyTuple_SET_ITEM(__pyx_5, 2, __pyx_4);
  __pyx_2 = 0;
  __pyx_4 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_3, __pyx_5); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":88 */
  __pyx_6 = (__pyx_v_ctInfo.type == __pyx_e_8contacts_CNTF_BYTE);
  if (__pyx_6) {
    __pyx_4 = PyInt_FromLong(__pyx_v_ctInfo.bVal); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
    __pyx_r = __pyx_4;
    __pyx_4 = 0;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_6 = (__pyx_v_ctInfo.type == __pyx_e_8contacts_CNTF_WORD);
  if (__pyx_6) {
    __pyx_3 = PyInt_FromLong(__pyx_v_ctInfo.wVal); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
    __pyx_r = __pyx_3;
    __pyx_3 = 0;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_6 = (__pyx_v_ctInfo.type == __pyx_e_8contacts_CNTF_DWORD);
  if (__pyx_6) {
    __pyx_5 = PyLong_FromUnsignedLong(__pyx_v_ctInfo.dVal); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
    __pyx_r = __pyx_5;
    __pyx_5 = 0;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_6 = (__pyx_v_ctInfo.type == __pyx_e_8contacts_CNTF_ASCIIZ);
  if (__pyx_6) {
    __pyx_2 = PyString_FromString(__pyx_v_ctInfo.pszVal); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
    __pyx_r = __pyx_2;
    __pyx_2 = 0;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":96 */
  __pyx_4 = PyInt_FromLong(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
  __pyx_r = __pyx_4;
  __pyx_4 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("contacts.GetInfo");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_flag);
  return __pyx_r;
}

static PyObject *__pyx_f_8contacts_GetContact(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_8contacts_GetContact(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_hContact = 0;
  char __pyx_v_buffer[4096];
  CONTACTINFO __pyx_v_ctInfo;
  PyObject *__pyx_v_contact;
  PyObject *__pyx_r;
  long __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  int __pyx_6;
  static char *__pyx_argnames[] = {"hContact",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_hContact)) return 0;
  Py_INCREF(__pyx_v_hContact);
  __pyx_v_contact = Py_None; Py_INCREF(Py_None);

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":100 */
  (__pyx_v_buffer[0]) = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":102 */
  __pyx_v_ctInfo.cbSize = (sizeof(CONTACTINFO));

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":103 */
  __pyx_1 = PyInt_AsLong(__pyx_v_hContact); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; goto __pyx_L1;}
  __pyx_v_ctInfo.hContact = __pyx_1;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":104 */
  __pyx_v_ctInfo.cchVal = 4096;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":105 */
  __pyx_v_ctInfo.pszVal = __pyx_v_buffer;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":106 */
  __pyx_v_ctInfo.szProto = NULL;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":108 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_Contact); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
  __pyx_3 = PyObject_CallObject(__pyx_2, 0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_v_contact);
  __pyx_v_contact = __pyx_3;
  __pyx_3 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":109 */
  __pyx_2 = PyInt_FromLong(__pyx_e_8contacts_CNF_FIRSTNAME); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  __pyx_3 = __pyx_f_8contacts_GetInfo(__pyx_v_ctInfo,__pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_v_contact, __pyx_n_firstName, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":111 */
  __pyx_2 = PyInt_FromLong(__pyx_e_8contacts_CNF_LASTNAME); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
  __pyx_3 = __pyx_f_8contacts_GetInfo(__pyx_v_ctInfo,__pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_v_contact, __pyx_n_lastName, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":113 */
  __pyx_2 = PyInt_FromLong(__pyx_e_8contacts_CNF_NICK); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
  __pyx_3 = __pyx_f_8contacts_GetInfo(__pyx_v_ctInfo,__pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_v_contact, __pyx_n_nick, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":115 */
  __pyx_2 = PyInt_FromLong(__pyx_e_8contacts_CNF_CUSTOMNICK); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
  __pyx_3 = __pyx_f_8contacts_GetInfo(__pyx_v_ctInfo,__pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_v_contact, __pyx_n_customNick, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":117 */
  __pyx_2 = PyInt_FromLong(__pyx_e_8contacts_CNF_EMAIL); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  __pyx_3 = __pyx_f_8contacts_GetInfo(__pyx_v_ctInfo,__pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_v_contact, __pyx_n_email, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":119 */
  __pyx_2 = PyInt_FromLong(__pyx_e_8contacts_CNF_CITY); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
  __pyx_3 = __pyx_f_8contacts_GetInfo(__pyx_v_ctInfo,__pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_v_contact, __pyx_n_city, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":121 */
  __pyx_2 = PyInt_FromLong(__pyx_e_8contacts_CNF_STATE); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 121; goto __pyx_L1;}
  __pyx_3 = __pyx_f_8contacts_GetInfo(__pyx_v_ctInfo,__pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 121; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_v_contact, __pyx_n_state, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 121; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":123 */
  __pyx_2 = PyInt_FromLong(__pyx_e_8contacts_CNF_COUNTRY); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; goto __pyx_L1;}
  __pyx_3 = __pyx_f_8contacts_GetInfo(__pyx_v_ctInfo,__pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_v_contact, __pyx_n_country, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":125 */
  __pyx_2 = PyInt_FromLong(__pyx_e_8contacts_CNF_PHONE); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
  __pyx_3 = __pyx_f_8contacts_GetInfo(__pyx_v_ctInfo,__pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_v_contact, __pyx_n_phone, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":127 */
  __pyx_2 = PyInt_FromLong(__pyx_e_8contacts_CNF_HOMEPAGE); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  __pyx_3 = __pyx_f_8contacts_GetInfo(__pyx_v_ctInfo,__pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_v_contact, __pyx_n_homepage, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":129 */
  __pyx_2 = PyInt_FromLong(__pyx_e_8contacts_CNF_ABOUT); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
  __pyx_3 = __pyx_f_8contacts_GetInfo(__pyx_v_ctInfo,__pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_v_contact, __pyx_n_about, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":131 */
  __pyx_2 = PyInt_FromLong(__pyx_e_8contacts_CNF_GENDER); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  __pyx_3 = __pyx_f_8contacts_GetInfo(__pyx_v_ctInfo,__pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_v_contact, __pyx_n_gender, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":133 */
  __pyx_v_ctInfo.dwFlag = __pyx_e_8contacts_CNF_AGE;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":134 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_MirPy); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_n_CallService); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
  __pyx_4 = PyInt_FromLong(((long)(&__pyx_v_ctInfo))); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
  Py_INCREF(__pyx_k4p);
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_k4p);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_2);
  PyTuple_SET_ITEM(__pyx_5, 2, __pyx_4);
  __pyx_2 = 0;
  __pyx_4 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_3, __pyx_5); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":135 */
  __pyx_6 = (__pyx_v_ctInfo.type == __pyx_e_8contacts_CNTF_BYTE);
  if (__pyx_6) {
    __pyx_4 = PyInt_FromLong(__pyx_v_ctInfo.bVal); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 136; goto __pyx_L1;}
    if (PyObject_SetAttr(__pyx_v_contact, __pyx_n_age, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 136; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    goto __pyx_L2;
  }
  /*else*/ {
    __pyx_3 = PyInt_FromLong(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 138; goto __pyx_L1;}
    if (PyObject_SetAttr(__pyx_v_contact, __pyx_n_age, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 138; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
  }
  __pyx_L2:;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":139 */
  __pyx_6 = (__pyx_v_ctInfo.szProto != NULL);
  if (__pyx_6) {
    __pyx_5 = PyString_FromString(__pyx_v_ctInfo.szProto); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
    if (PyObject_SetAttr(__pyx_v_contact, __pyx_n_protocol, __pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    goto __pyx_L3;
  }
  /*else*/ {
    __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
    if (PyObject_SetAttr(__pyx_v_contact, __pyx_n_protocol, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
  }
  __pyx_L3:;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":144 */
  __pyx_4 = PyInt_FromLong(__pyx_e_8contacts_CNF_UNIQUEID); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 144; goto __pyx_L1;}
  __pyx_3 = __pyx_f_8contacts_GetInfo(__pyx_v_ctInfo,__pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 144; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (PyObject_SetAttr(__pyx_v_contact, __pyx_n_uniqueID, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 144; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":145 */
  Py_INCREF(__pyx_v_contact);
  __pyx_r = __pyx_v_contact;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("contacts.GetContact");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_contact);
  Py_DECREF(__pyx_v_hContact);
  return __pyx_r;
}

static struct PyMethodDef __pyx_methods[] = {
  {"GetContact", (PyCFunction)__pyx_f_8contacts_GetContact, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initcontacts(void); /*proto*/
PyMODINIT_FUNC initcontacts(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("contacts", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":5 */
  __pyx_1 = __Pyx_Import(__pyx_n_MirPy, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 5; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_MirPy, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 5; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":50 */
  __pyx_1 = PyDict_New(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  if (PyDict_SetItemString(__pyx_1, "__doc__", __pyx_k21p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  __pyx_3 = __Pyx_CreateClass(__pyx_2, __pyx_1, __pyx_n_Contact, "contacts"); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyCFunction_New(&__pyx_mdef_8contacts_7Contact___init__, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_2, 0, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n___init__, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n_Contact, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "D:\home\work\miranda related\miranda\plugins\MirPy\modules\contacts\pyrex\contacts.pyx":98 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("contacts");
}

static char *__pyx_filenames[] = {
  "contacts.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        if (t->i)
            PyString_InternInPlace(t->p);
        ++t;
    }
    return 0;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_CreateClass(
    PyObject *bases, PyObject *dict, PyObject *name, char *modname)
{
    PyObject *py_modname;
    PyObject *result = 0;
    
    py_modname = PyString_FromString(modname);
    if (!py_modname)
        goto bad;
    if (PyDict_SetItemString(dict, "__module__", py_modname) < 0)
        goto bad;
    result = PyClass_New(bases, dict, name);
bad:
    Py_XDECREF(py_modname);
    return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
